#!/usr/bin/env python3
"""
Generate propagation map YAML files for each layer.

Propagation maps help developers understand what must be updated when modifying
a layer or module. They analyze ADR frontmatter and generate actionable checklists.

Usage:
    python scripts/ADR_scripts/generate_propagation_maps.py
    python scripts/ADR_scripts/generate_propagation_maps.py --layer layer3_execution
    python scripts/ADR_scripts/generate_propagation_maps.py --validate
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Set


class PropagationMapGenerator:
    def __init__(self, base_path: Path = Path.cwd()):
        self.base_path = base_path
        self.decisions_path = base_path / "docs" / "architecture" / "decisions"
        self.index_path = self.decisions_path / "00-meta" / "adr_index.json"
        self.output_dir = self.decisions_path / "00-meta" / "propagation_maps"
        self.index_data = None

    def load_index(self) -> None:
        """Load ADR index JSON."""
        if not self.index_path.exists():
            print(f"❌ Index not found: {self.index_path}", file=sys.stderr)
            print("   💡 Run: python scripts/ADR_scripts/build_adr_index.py", file=sys.stderr)
            sys.exit(1)

        with open(self.index_path, "r", encoding="utf-8") as f:
            self.index_data = json.load(f)

        print(f"📊 Loaded index: {self.index_data['total_adrs']} ADRs")

    def get_layer_adrs(self, layer: str) -> List[Dict]:
        """Get all ADRs affecting a specific layer."""
        return [adr for adr in self.index_data["adrs"] if layer in adr.get("affected_layers", [])]

    def get_layer_modules(self, layer: str) -> Set[str]:
        """Extract unique modules for a layer from ADRs."""
        modules = set()
        for adr in self.index_data["adrs"]:
            if layer in adr.get("affected_layers", []):
                for module in adr.get("affected_modules", []):
                    # Filter to layer-specific modules
                    layer_prefix = f"k1/{layer.replace('layer', 'l')}"
                    if module.startswith(layer_prefix):
                        modules.add(module)
        return modules

    def generate_layer_map(self, layer: str) -> str:
        """Generate propagation map YAML for a layer."""
        layer_adrs = self.get_layer_adrs(layer)
        layer_modules = sorted(self.get_layer_modules(layer))

        # Layer metadata
        layer_name_map = {
            "layer1_input": "Layer 1: Input Processing",
            "layer2_orchestration": "Layer 2: Orchestration",
            "layer3_execution": "Layer 3: Execution",
            "layer4_runtime": "Layer 4: Runtime Core",
            "layer5_infrastructure": "Layer 5: Infrastructure",
        }

        layer_description_map = {
            "layer1_input": "Stream processing, ASR ingress, voice pipeline",
            "layer2_orchestration": "Planner, Orchestrator, Agent Lifecycle FSM",
            "layer3_execution": "Agent Fabric, Model Hub, Tools, Dialogue Management",
            "layer4_runtime": "SessionState, Leases, Flow Engine, Learning Loop",
            "layer5_infrastructure": "Scheduler, Backpressure, Thermal Management, Observability",
        }

        yaml_content = f"""# {layer_name_map.get(layer, layer)} - Propagation Map
# Auto-generated by generate_propagation_maps.py
# Last updated: {datetime.now().isoformat()}
#
# Purpose: Track architectural propagation when modifying {layer}
# Usage: python scripts/ADR_scripts/check_propagation.py --layer {layer}

layer: {layer}
description: "{layer_description_map.get(layer, 'Layer description')}"
total_adrs: {len(layer_adrs)}
total_modules: {len(layer_modules)}

# Modules in this layer
modules:
"""

        for module in layer_modules:
            yaml_content += f"  - {module}\n"

        yaml_content += f"""
# ADRs affecting this layer
affected_adrs:
"""

        for adr in sorted(layer_adrs, key=lambda x: x.get("adr_number", "")):
            status = adr.get("status", "UNKNOWN")
            yaml_content += f"""
  - adr_number: "{adr.get('adr_number', '')}"
    title: "{adr.get('title', '')}"
    status: {status}
    file_path: "{adr.get('file_path', '')}"
    concerns: {adr.get('concerns', [])}
"""

        # Propagation scenarios (generic templates)
        yaml_content += f"""
# Common propagation scenarios
scenarios:
  - scenario: "Add new module to {layer}"
    description: "When adding a new module to {layer}"
    checklist:
      adrs_to_review:
"""

        # Find architecture ADRs
        arch_adrs = [adr for adr in layer_adrs if "architecture" in adr.get("concerns", [])]
        for adr in arch_adrs[:3]:  # Top 3 architecture ADRs
            yaml_content += f"        - ADR-{adr.get('adr_number', '')}: {adr.get('title', '')}\n"

        yaml_content += f"""      contracts_to_update:
        - "k1/contracts/flatbuffers/{layer}/*.fbs"
        - "k1/contracts/api/*.yaml"
      tests_to_add:
        - "tests/k1/{layer.replace('layer', 'l')}/test_new_module.py"
      diagrams_to_update:
        - "architecture_diagrams/k1/k1_complete_with_flows.mmd"

  - scenario: "Modify existing module in {layer}"
    description: "When changing behavior of existing {layer} module"
    checklist:
      adrs_to_review:
"""

        # Find performance ADRs
        perf_adrs = [adr for adr in layer_adrs if "performance" in adr.get("concerns", [])]
        for adr in perf_adrs[:2]:  # Top 2 performance ADRs
            yaml_content += f"        - ADR-{adr.get('adr_number', '')}: {adr.get('title', '')}\n"

        yaml_content += f"""      contracts_to_validate:
        - "Ensure backward compatibility with existing schemas"
      tests_to_update:
        - "Update integration tests for modified module"
        - "Verify performance budgets still met"

  - scenario: "Remove module from {layer}"
    description: "When deprecating/removing a {layer} module"
    checklist:
      adrs_to_update:
        - "Update ADR-0004 module count"
        - "Document deprecation timeline"
      contracts_to_deprecate:
        - "Mark schemas as deprecated (90-day policy)"
      migration_guide:
        - "Create migration guide for users"
      tests_to_remove:
        - "Archive tests after deprecation period"

# Layer dependencies
upstream_dependencies:
"""

        # Determine upstream dependencies
        if layer == "layer1_input":
            yaml_content += "  # Layer 1 has no upstream K1 dependencies (ingress layer)\n"
        elif layer == "layer2_orchestration":
            yaml_content += "  - layer1_input  # Receives input from Layer 1\n"
        elif layer == "layer3_execution":
            yaml_content += "  - layer2_orchestration  # Receives orchestration decisions\n"
            yaml_content += "  - layer4_runtime  # Accesses SessionState, Leases\n"
        elif layer == "layer4_runtime":
            yaml_content += "  - layer5_infrastructure  # Uses scheduler, backpressure\n"
        elif layer == "layer5_infrastructure":
            yaml_content += "  # Layer 5 has no upstream K1 dependencies (foundation layer)\n"

        yaml_content += """
downstream_dependencies:
"""

        # Determine downstream dependencies
        if layer == "layer5_infrastructure":
            yaml_content += "  - layer4_runtime  # Layer 4 uses Layer 5 services\n"
            yaml_content += "  - layer3_execution  # Layer 3 uses Layer 5 services\n"
        elif layer == "layer4_runtime":
            yaml_content += "  - layer3_execution  # Layer 3 accesses SessionState\n"
        elif layer == "layer3_execution":
            yaml_content += "  - layer2_orchestration  # Layer 2 hires agents from Layer 3\n"
        elif layer == "layer2_orchestration":
            yaml_content += "  - layer1_input  # Layer 1 sends events to Layer 2\n"
        elif layer == "layer1_input":
            yaml_content += "  - layer2_orchestration  # Layer 2 receives input\n"

        yaml_content += """
# Cross-cutting concerns
cross_cutting:
  - "All layer changes must update contracts in 07-contracts-serialization/"
  - "All layer changes must follow Actor Model patterns (ADR-0002)"
  - "All layer changes must update performance budgets (ADR-0024)"
  - "All layer changes must add observability (ADR-0029, ADR-0030)"
"""

        return yaml_content

    def generate_all_maps(self) -> None:
        """Generate propagation maps for all 5 layers."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        layers = [
            "layer1_input",
            "layer2_orchestration",
            "layer3_execution",
            "layer4_runtime",
            "layer5_infrastructure",
        ]

        print(f"\n🔄 Generating propagation maps...")
        print(f"📁 Output directory: {self.output_dir}\n")

        generated = []
        for layer in layers:
            output_file = self.output_dir / f"{layer}.yml"

            yaml_content = self.generate_layer_map(layer)

            with open(output_file, "w", encoding="utf-8") as f:
                f.write(yaml_content)

            layer_adrs = self.get_layer_adrs(layer)
            layer_modules = self.get_layer_modules(layer)

            print(f"✅ Created {output_file.relative_to(self.base_path)}")
            print(f"   📊 {len(layer_adrs)} ADRs, {len(layer_modules)} modules")

            generated.append(output_file)

        return generated

    def validate_maps(self) -> bool:
        """Validate that propagation maps exist and are up-to-date."""
        print("\n🔍 Validating propagation maps...\n")

        layers = [
            "layer1_input",
            "layer2_orchestration",
            "layer3_execution",
            "layer4_runtime",
            "layer5_infrastructure",
        ]

        all_valid = True
        for layer in layers:
            map_file = self.output_dir / f"{layer}.yml"

            if not map_file.exists():
                print(f"❌ Missing: {layer}.yml")
                all_valid = False
                continue

            # Check if file is recent (modified within last 7 days)
            import time

            file_age_days = (time.time() - map_file.stat().st_mtime) / 86400

            if file_age_days > 7:
                print(f"⚠️  Stale: {layer}.yml (last updated {int(file_age_days)} days ago)")
                all_valid = False
            else:
                print(f"✅ Valid: {layer}.yml")

        if all_valid:
            print("\n✅ All propagation maps are valid")
        else:
            print("\n⚠️  Some propagation maps need updating")
            print("   💡 Run: python scripts/ADR_scripts/generate_propagation_maps.py")

        return all_valid


def main():
    parser = argparse.ArgumentParser(
        description="Generate propagation map YAML files for each layer"
    )
    parser.add_argument(
        "--layer",
        help="Generate map for specific layer only",
        choices=[
            "layer1_input",
            "layer2_orchestration",
            "layer3_execution",
            "layer4_runtime",
            "layer5_infrastructure",
        ],
    )
    parser.add_argument(
        "--validate", action="store_true", help="Validate existing maps (no regeneration)"
    )
    parser.add_argument(
        "--base-path",
        type=Path,
        default=Path.cwd(),
        help="Base repository path (default: current directory)",
    )

    args = parser.parse_args()

    generator = PropagationMapGenerator(args.base_path)

    if args.validate:
        success = generator.validate_maps()
        sys.exit(0 if success else 1)

    # Load index
    generator.load_index()

    # Generate maps
    if args.layer:
        # Single layer
        output_file = generator.output_dir / f"{args.layer}.yml"
        generator.output_dir.mkdir(parents=True, exist_ok=True)

        yaml_content = generator.generate_layer_map(args.layer)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(yaml_content)

        layer_adrs = generator.get_layer_adrs(args.layer)
        layer_modules = generator.get_layer_modules(args.layer)

        print(f"\n✅ Created {output_file.relative_to(generator.base_path)}")
        print(f"   📊 {len(layer_adrs)} ADRs, {len(layer_modules)} modules")
    else:
        # All layers
        generated = generator.generate_all_maps()

        print(f"\n{'=' * 60}")
        print("✅ Propagation maps generation complete")
        print(f"{'=' * 60}")
        print(f"\n📁 Maps location: {generator.output_dir.relative_to(generator.base_path)}")
        print(f"📊 Generated {len(generated)} layer maps")
        print("\n💡 Usage:")
        print("   python scripts/ADR_scripts/check_propagation.py --layer layer3_execution")
        print("   python scripts/ADR_scripts/generate_propagation_maps.py --validate")


if __name__ == "__main__":
    main()
