"""Header stamped onto every generated artifact under ``bridge/_generated/``.

Format is deterministic so the no-diff CI gate can detect drift caused by
manifest revisions without false positives from clock skew or absolute
paths.
"""

from __future__ import annotations

CODEGEN_INVOCATION = "python -m tooling.contracts.codegen"


def render_header(*, manifest_bundle_sha: str, source_manifest: str) -> str:
    """Render the canonical 3-line autogenerated header.

    The literal text — including spaces and order — is part of the contract
    between codegen and the no-diff gate. Do not reformat.
    """
    return (
        "# AUTOGENERATED \u2014 DO NOT EDIT \u2014 "
        f"regenerate with: {CODEGEN_INVOCATION}\n"
        f"# manifest_bundle_sha: {manifest_bundle_sha}\n"
        f"# source manifest: {source_manifest}\n"
    )
