"""
Actor Fabric Mailbox — Base MPSC Queue Implementation

Core MPSC (Multiple Producers, Single Consumer) queue for actor-to-actor messaging.
Performance budget: <0.5ms P95 enqueue/dequeue latency.

Research Foundation:
- Actor Model (Hewitt 1973): Message passing concurrency
- MPSC Queue (Michael & Scott 1996): Lock-free data structures

Related ADRs:
- ADR-0002: Actor Model for Agent Isolation (mailbox architecture)
- ADR-0011: FlatBuffers for Serialization (message format)

Implementation Status: Production-ready (Issue 2.1 complete)
"""

import asyncio
import time
from dataclasses import dataclass
from typing import Optional

# Import generated FlatBuffers message envelope types
# These are generated by flatc compiler from message_envelope.fbs
# Generated files are in k1/l4_runtime/actor_fabric/mailbox/model/
try:
    from k1.l4_runtime.actor_fabric.mailbox.model.MessageEnvelope import MessageEnvelope
    from k1.l4_runtime.actor_fabric.mailbox.model.MessagePriority import MessagePriority
except ImportError as e:
    # Fallback: If imports fail, provide stub types for development
    # Real implementation requires flatc compilation
    MessageEnvelope = None  # type: ignore
    MessagePriority = None  # type: ignore
    print(
        f"Warning: FlatBuffers types not found. Run: flatc --python message_envelope.fbs ({e})"
    )


@dataclass
class EnqueueResult:
    """Result of enqueue operation.

    Attributes:
        success: True if message was enqueued, False if rejected
        reason: Optional reason for rejection (e.g., "queue_full", "ttl_expired")
    """

    success: bool
    reason: Optional[str] = None


class MessageQueue:
    """MPSC queue for actor mailbox message passing.

    Thread-safe, lock-free message queue using asyncio.Queue. Supports:
    - Multiple producers (any actor can send)
    - Single consumer (owning actor dequeues)
    - Configurable capacity (default 1024)
    - TTL-based message expiry
    - Performance budget: <0.5ms P95 enqueue/dequeue

    Architecture:
        Uses asyncio.Queue for thread-safe MPSC semantics. Queue is bounded
        with configurable capacity. Messages are MessageEnvelope FlatBuffers.

    Performance Characteristics:
        - Enqueue: <0.5ms P95 (async put, no blocking)
        - Dequeue: <0.5ms P95 (async get)
        - Size: O(1) (queue.qsize())
        - Memory: O(capacity) (bounded queue)

    Example:
        >>> queue = MessageQueue(capacity=1024)
        >>>
        >>> # Producer (any actor)
        >>> import flatbuffers
        >>> builder = flatbuffers.Builder(2048)
        >>> # ... build MessageEnvelope ...
        >>> message_bytes = bytes(builder.Output())
        >>> result = await queue.enqueue(message_bytes)
        >>>
        >>> # Consumer (owning actor)
        >>> message_bytes = await queue.dequeue()
        >>> msg = MessageEnvelope.GetRootAsMessageEnvelope(message_bytes, 0)
        >>> print(f"From: {msg.SenderId().decode()}")

    Thread Safety:
        asyncio.Queue is thread-safe for async operations. Multiple producers
        can enqueue concurrently. Single consumer dequeues sequentially.

    Related ADRs:
        - ADR-0002: Actor Model (mailbox architecture)
        - ADR-0011: FlatBuffers (message format)
    """

    def __init__(self, capacity: int = 1024, validate_envelope: bool = True):
        """Initialize MPSC message queue.

        Args:
            capacity: Maximum number of messages in queue (default 1024)
            validate_envelope: If True, validate FlatBuffers MessageEnvelope and TTL.
                             Set False when wrapping messages with custom metadata.

        Performance:
            - Initialization: O(1)
            - Memory: O(capacity) pre-allocated
        """
        self._capacity = capacity
        self._queue: asyncio.Queue = asyncio.Queue(maxsize=capacity)
        self._validate_envelope = validate_envelope

        # Metrics tracking
        self._enqueue_count: int = 0
        self._dequeue_count: int = 0
        self._rejected_count: int = 0

    async def enqueue(self, message: bytes) -> EnqueueResult:
        """Enqueue message to mailbox (non-blocking).

        Args:
            message: Serialized MessageEnvelope (FlatBuffers bytes)

        Returns:
            EnqueueResult with success=True if enqueued, success=False if rejected

        Performance:
            - Latency: <0.5ms P95
            - Rejects immediately if queue full (no blocking)

        Example:
            >>> result = await queue.enqueue(message_bytes)
            >>> if result.success:
            >>>     print("Message enqueued")
            >>> else:
            >>>     print(f"Rejected: {result.reason}")

        Thread Safety:
            Safe for concurrent calls from multiple producers.
        """
        # Check capacity before attempting enqueue
        if self._queue.qsize() >= self._capacity:
            self._rejected_count += 1
            return EnqueueResult(success=False, reason="queue_full")

        # Only validate FlatBuffers MessageEnvelope when asked AND MessageEnvelope exists
        if self._validate_envelope and MessageEnvelope is not None:
            try:
                msg = MessageEnvelope.GetRootAsMessageEnvelope(message, 0)
                created_at = msg.CreatedAt()
                ttl_ms = msg.TtlMs()

                # Check if message expired (only if TTL > 0)
                if ttl_ms > 0:
                    current_time_ms = int(time.time() * 1000)
                    if created_at + ttl_ms < current_time_ms:
                        self._rejected_count += 1
                        return EnqueueResult(success=False, reason="ttl_expired")
            except Exception as e:
                # If deserialization fails, reject message
                self._rejected_count += 1
                return EnqueueResult(success=False, reason=f"invalid_message: {e}")

        # Enqueue message (non-blocking put_nowait)
        try:
            self._queue.put_nowait(message)
            self._enqueue_count += 1
            return EnqueueResult(success=True)
        except asyncio.QueueFull:
            # Race condition: queue filled between size check and put
            self._rejected_count += 1
            return EnqueueResult(success=False, reason="queue_full")

    async def dequeue(self) -> Optional[bytes]:
        """Dequeue message from mailbox (blocking until message available).

        Returns:
            Serialized MessageEnvelope (FlatBuffers bytes), or None if queue empty

        Performance:
            - Latency: <0.5ms P95 (when message available)
            - Blocks if queue empty (awaits next message)

        Example:
            >>> message_bytes = await queue.dequeue()
            >>> if message_bytes:
            >>>     msg = MessageEnvelope.GetRootAsMessageEnvelope(message_bytes, 0)
            >>>     print(f"Received: {msg.MessageType()}")

        Thread Safety:
            Safe for single consumer (owning actor).
        """
        try:
            message = await self._queue.get()
            self._dequeue_count += 1
            return message
        except asyncio.CancelledError:
            # Actor shutdown: return None
            return None

    def size(self) -> int:
        """Get current queue depth.

        Returns:
            Number of messages currently in queue

        Performance:
            - Latency: O(1)

        Example:
            >>> depth = queue.size()
            >>> print(f"Queue depth: {depth}")
        """
        return self._queue.qsize()

    def capacity(self) -> int:
        """Get queue capacity.

        Returns:
            Maximum number of messages queue can hold

        Performance:
            - Latency: O(1)

        Example:
            >>> cap = queue.capacity()
            >>> print(f"Capacity: {cap}")
        """
        return self._capacity

    def is_empty(self) -> bool:
        """Check if queue is empty.

        Returns:
            True if queue has no messages, False otherwise

        Performance:
            - Latency: O(1)
        """
        return self._queue.empty()

    def is_full(self) -> bool:
        """Check if queue is full.

        Returns:
            True if queue is at capacity, False otherwise

        Performance:
            - Latency: O(1)
        """
        return self._queue.qsize() >= self._capacity

    def usage_percent(self) -> float:
        """Get queue usage percentage.

        Returns:
            Queue depth as percentage of capacity (0.0 to 100.0)

        Example:
            >>> usage = queue.usage_percent()
            >>> if usage > 80.0:
            >>>     print("High queue pressure")
        """
        return (self._queue.qsize() / self._capacity) * 100.0

    def metrics(self) -> dict:
        """Get queue metrics for observability.

        Returns:
            Dictionary with enqueue/dequeue/rejected counts and queue depth

        Example:
            >>> metrics = queue.metrics()
            >>> print(f"Enqueued: {metrics['enqueue_count']}")
            >>> print(f"Dequeued: {metrics['dequeue_count']}")
            >>> print(f"Rejected: {metrics['rejected_count']}")
            >>> print(f"Current depth: {metrics['size']}")
        """
        return {
            "enqueue_count": self._enqueue_count,
            "dequeue_count": self._dequeue_count,
            "rejected_count": self._rejected_count,
            "size": self.size(),
            "capacity": self._capacity,
            "usage_percent": self.usage_percent(),
            "is_empty": self.is_empty(),
            "is_full": self.is_full(),
        }

    def __repr__(self) -> str:
        """String representation for debugging.

        Returns:
            Human-readable queue status

        Example:
            >>> print(queue)
            MessageQueue(size=42/1024, enqueued=1523, dequeued=1481, rejected=0)
        """
        return (
            f"MessageQueue("
            f"size={self.size()}/{self._capacity}, "
            f"enqueued={self._enqueue_count}, "
            f"dequeued={self._dequeue_count}, "
            f"rejected={self._rejected_count})"
        )


# Example usage (for documentation)
if __name__ == "__main__":
    import asyncio

    import flatbuffers

    from k1.actor_fabric.MessageType import MessageType

    async def example():
        # Create queue
        queue = MessageQueue(capacity=1024)

        # Create message envelope
        builder = flatbuffers.Builder(2048)

        sender_id = builder.CreateString("agent-123")
        receiver_id = builder.CreateString("orchestrator-main")
        trace_id = builder.CreateString("trace-abc")
        payload = builder.CreateByteVector(b"test payload")

        MessageEnvelope.Start(builder)
        MessageEnvelope.AddSenderId(builder, sender_id)
        MessageEnvelope.AddReceiverId(builder, receiver_id)
        MessageEnvelope.AddMessageType(builder, MessageType.TASK_ANNOUNCEMENT)
        MessageEnvelope.AddPriority(builder, MessagePriority.REALTIME)
        MessageEnvelope.AddPayload(builder, payload)
        MessageEnvelope.AddTtlMs(builder, 5000)
        MessageEnvelope.AddCreatedAt(builder, int(time.time() * 1000))
        MessageEnvelope.AddTraceId(builder, trace_id)
        MessageEnvelope.AddVersion(builder, 1)
        envelope = MessageEnvelope.End(builder)

        builder.Finish(envelope)
        message_bytes = bytes(builder.Output())

        # Enqueue
        result = await queue.enqueue(message_bytes)
        print(f"Enqueue result: {result}")

        # Dequeue
        received = await queue.dequeue()
        if received:
            msg = MessageEnvelope.GetRootAsMessageEnvelope(received, 0)
            print(f"Received from: {msg.SenderId().decode()}")
            print(f"Type: {msg.MessageType()}")

        # Metrics
        print(f"Queue metrics: {queue.metrics()}")

    asyncio.run(example())

    asyncio.run(example())

    asyncio.run(example())
    asyncio.run(example())
