# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/feedback.envelope.v1.yaml

"""Generated Protocol for the ``feedback.envelope.v1`` contract.

Imported by the k1 kernel where strong typing on the
publish/handle surface is needed (e.g. memory_writer batch emitters
type-checking against the published shape).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from bridge._generated.k1.models.feedback_envelope_v1 import (
    FeedbackEnvelopeV1,
)


@runtime_checkable
class IFeedbackEnvelopeV1Port(Protocol):
    """Per-contract obs publishing interface for ``feedback.envelope.v1``.

    MS-3e: posts ``{kind=``feedback``, body}`` to ``/k0/obs.emit``.
    """

    __topic__: str
    __schema_uri__: str
    __obs_kind__: str

    async def publish(self, payload: FeedbackEnvelopeV1) -> object: ...
