# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/memory.write.v1.yaml

"""Generated Protocol for the ``memory.write.v1`` contract.

Imported by the k1 kernel where strong typing on the
publish/handle surface is needed (e.g. memory_writer batch emitters
type-checking against the published shape).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from bridge._generated.k1.models.memory_write_v1 import (
    MemoryWriteV1,
)


@runtime_checkable
class IMemoryWriteV1Port(Protocol):
    """Per-contract publishing interface for ``memory.write.v1``."""

    __topic__: str
    __schema_uri__: str

    async def memory_write_v1(self, payload: MemoryWriteV1) -> object: ...
