# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/observability.payload.v1.yaml

"""Generated Protocol for the ``observability.payload.v1`` contract.

Imported by the k1 kernel where strong typing on the
publish/handle surface is needed (e.g. memory_writer batch emitters
type-checking against the published shape).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from bridge._generated.k1.models.observability_payload_v1 import (
    ObservabilityPayloadV1,
)


@runtime_checkable
class IObservabilityPayloadV1Port(Protocol):
    """Per-contract obs publishing interface for ``observability.payload.v1``.

    MS-3e: posts ``{kind=``metrics``, body}`` to ``/k0/obs.emit``.
    """

    __topic__: str
    __schema_uri__: str
    __obs_kind__: str

    async def publish(self, payload: ObservabilityPayloadV1) -> object: ...
