# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/recall.request.v1.yaml

"""Generated Protocol for the ``recall.request.v1`` contract.

Imported by the k1 kernel where strong typing on the
publish/handle surface is needed (e.g. memory_writer batch emitters
type-checking against the published shape).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from bridge._generated.k1.models.recall_request_v1 import (
    RecallRequestV1,
)
from bridge._generated.k1.models.recall_response_v1 import (
    RecallResponseV1,
)


@runtime_checkable
class IRecallRequestV1Port(Protocol):
    """Per-contract publishing interface for ``recall.request.v1``."""

    __topic__: str
    __schema_uri__: str

    async def request(self, payload: RecallRequestV1) -> RecallResponseV1: ...
