# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k0: 4 topic(s)

"""Auto-generated client stub for kernel ``k0``."""

from __future__ import annotations

from typing import Any


class K0BridgeClient:
    """Generated thin client. Real transport binding lands in MS-3a."""

    __transport__ = "in_process"

    def __init__(self, runtime: Any) -> None:
        self._runtime = runtime

    async def memory_write_v1(self, payload: Any) -> Any:
        """Publish to ``memory.write.v1`` (transport=http)."""
        raise NotImplementedError(
            "Generated stub: contract memory.write.v1 not wired yet."
        )
    async def recall_request_v1(self, payload: Any) -> Any:
        """Publish to ``recall.request.v1`` (transport=http)."""
        raise NotImplementedError(
            "Generated stub: contract recall.request.v1 not wired yet."
        )
