# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: k0: 4 topic(s)

"""Auto-generated handler registry for kernel ``k0``."""

from __future__ import annotations

from typing import Any, Callable


def register_handlers(runtime: Any, impl: Any) -> None:
    """Wire ``impl`` methods into ``runtime`` for kernel ``k0``.

    Compile-time check: every topic listed in the manifests for this kernel
    must have a corresponding ``impl.<method>`` callable.
    """
    expected_methods = [
        "memory_write_v1",
        "recall_request_v1",
    ]
    missing = [m for m in expected_methods if not callable(getattr(impl, m, None))]
    if missing:
        raise TypeError(
            "impl is missing required methods for kernel 'k0': "
            + ", ".join(missing)
        )
