# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: k0: 4 topic(s)

"""Auto-generated package index for kernel ``k0``.

Lists every contract topic routed to / from this kernel.
"""

from __future__ import annotations

TOPICS: tuple[str, ...] = (
    "feedback.envelope.v1",
    "memory.write.v1",
    "observability.payload.v1",
    "recall.request.v1",
)
