# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k0: 4 topic(s)

"""Auto-generated package index for kernel ``k0``.

Lists every contract topic routed to / from this kernel.
"""

from __future__ import annotations

TOPICS: tuple[str, ...] = (
    "feedback.envelope.v1",
    "memory.write.v1",
    "observability.payload.v1",
    "recall.request.v1",
)
