# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k0: 4 topic(s)

"""Auto-generated port protocol for kernel ``k0``."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IK0BridgePort(Protocol):
    """Generated facade. Methods are added once contracts ship payloads."""

    async def memory_write_v1(self, payload: Any) -> Any:
        """Handle topic ``memory.write.v1``."""
        ...
    async def recall_request_v1(self, payload: Any) -> Any:
        """Handle topic ``recall.request.v1``."""
        ...
