# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: k0: 4 topic(s)

"""Auto-generated port protocol for kernel ``k0``."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IK0BridgePort(Protocol):
    """Generated facade. Methods are added once contracts ship payloads."""

    async def memory_write_v1(self, payload: Any) -> Any:
        """Handle topic ``memory.write.v1``."""
        ...
    async def recall_request_v1(self, payload: Any) -> Any:
        """Handle topic ``recall.request.v1``."""
        ...
