"""
Anniversary Demo Tools
======================

Tool implementations for the 30-turn demo.
"""

from poc.session_state_demo.anniversary_demo.tools.calendar import (
    CALENDAR_TOOLS,
    CalendarEvent,
    CalendarStore,
    EventVisibility,
    Reminder,
    ReminderStatus,
    TripSummary,
    create_calendar_event,
    execute_calendar_tool,
    generate_trip_summary,
    get_demo_trip_summary,
    schedule_reminder,
)
from poc.session_state_demo.anniversary_demo.tools.clarification import (
    ClarificationGenerator,
    ClarificationResult,
    create_clarification_generator,
)
from poc.session_state_demo.anniversary_demo.tools.family import (
    FAMILY_TOOLS,
    CheckinStatus,
    FamilyMember,
    FamilyMessage,
    FamilyMessageStore,
    MessagePriority,
    MessageStatus,
    ScheduledCheckin,
    compose_weekend_instructions,
    execute_family_tool,
    get_family_member_info,
    schedule_family_checkin,
    send_family_message,
    simulate_checkin_response,
)
from poc.session_state_demo.anniversary_demo.tools.gap_detection import (
    ClarificationRequest,
    GapAnalysis,
    LLMGapDetector,
    create_gap_detector,
)
from poc.session_state_demo.anniversary_demo.tools.monitors import (
    MONITOR_TOOLS,
    AlertSeverity,
    BackgroundMonitor,
    MonitorAlert,
    MonitorStatus,
    MonitorStore,
    MonitorType,
    WeatherForecast,
    check_monitors,
    execute_monitor_tool,
    get_initial_forecast,
    get_monitor_status,
    get_updated_forecast,
    get_weather_forecast,
    list_active_monitors,
    start_background_monitor,
    stop_background_monitor,
)
from poc.session_state_demo.anniversary_demo.tools.registry import (
    ParamSchema,
    ParamType,
    ToolRegistry,
    ToolSchema,
    ValidationResult,
    create_demo_registry,
    get_registry,
)
from poc.session_state_demo.anniversary_demo.tools.retry_flow import (
    PendingClarification,
    RetryOrchestrator,
    RetryResult,
    ToolAttemptResult,
    create_retry_orchestrator,
)
from poc.session_state_demo.anniversary_demo.tools.travel import (
    TRAVEL_TOOLS,
    BookingConfirmation,
    BookingStatus,
    BookingStore,
    book_accommodation,
    book_restaurant,
    book_spa_service,
    execute_travel_tool,
    get_accommodation_details,
    get_restaurant_details,
    plan_route,
    search_accommodations,
    search_activities,
    search_restaurants,
)
from poc.session_state_demo.anniversary_demo.tools.validation import (
    ToolCall,
    ToolCallValidator,
    ValidatedToolCall,
    ValidationBatch,
    ValidationMiddleware,
)

__all__ = [
    # Registry
    "ToolRegistry",
    "ToolSchema",
    "ParamSchema",
    "ParamType",
    "ValidationResult",
    "create_demo_registry",
    "get_registry",
    # Validation
    "ToolCall",
    "ToolCallValidator",
    "ValidatedToolCall",
    "ValidationBatch",
    "ValidationMiddleware",
    # Gap Detection
    "GapAnalysis",
    "LLMGapDetector",
    "ClarificationRequest",
    "create_gap_detector",
    # Clarification
    "ClarificationGenerator",
    "ClarificationResult",
    "create_clarification_generator",
    # Retry Flow
    "PendingClarification",
    "RetryOrchestrator",
    "RetryResult",
    "ToolAttemptResult",
    "create_retry_orchestrator",
    # Travel Tools
    "TRAVEL_TOOLS",
    "BookingConfirmation",
    "BookingStatus",
    "BookingStore",
    "execute_travel_tool",
    "search_accommodations",
    "get_accommodation_details",
    "book_accommodation",
    "search_restaurants",
    "get_restaurant_details",
    "book_restaurant",
    "plan_route",
    "search_activities",
    "book_spa_service",
    # Family Tools
    "FAMILY_TOOLS",
    "FamilyMessage",
    "FamilyMessageStore",
    "FamilyMember",
    "MessagePriority",
    "MessageStatus",
    "ScheduledCheckin",
    "CheckinStatus",
    "send_family_message",
    "schedule_family_checkin",
    "get_family_member_info",
    "execute_family_tool",
    "compose_weekend_instructions",
    "simulate_checkin_response",
    # Calendar Tools
    "CALENDAR_TOOLS",
    "CalendarEvent",
    "CalendarStore",
    "EventVisibility",
    "Reminder",
    "ReminderStatus",
    "TripSummary",
    "create_calendar_event",
    "schedule_reminder",
    "generate_trip_summary",
    "get_demo_trip_summary",
    "execute_calendar_tool",
    # Monitor Tools
    "MONITOR_TOOLS",
    "AlertSeverity",
    "BackgroundMonitor",
    "MonitorAlert",
    "MonitorStatus",
    "MonitorStore",
    "MonitorType",
    "WeatherForecast",
    "check_monitors",
    "execute_monitor_tool",
    "get_initial_forecast",
    "get_monitor_status",
    "get_updated_forecast",
    "get_weather_forecast",
    "list_active_monitors",
    "start_background_monitor",
    "stop_background_monitor",
]
