"""
Background Monitor Tools
=========================

Tools for starting and stopping background monitors that run
independently of the conversation. Key for the "two-way concierge"
architecture.

Demo Feature:
- Weather monitor triggers at Turn 24 with forecast change
- Enables proactive notification while user continues chatting

Tools:
- start_background_monitor: Start weather/price/availability monitor
- stop_background_monitor: Cancel a running monitor
- Weather monitor: Simulated forecast with change at Turn 24
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import Any, Dict, List, Optional

# ============================================================================
# Monitor Types and Status
# ============================================================================


class MonitorType(Enum):
    """Types of background monitors available."""

    WEATHER = "weather"
    PRICE = "price"
    AVAILABILITY = "availability"
    OVEN = "oven"
    LAUNDRY = "laundry"
    SMOKE_DETECTOR = "smoke_detector"
    DOORBELL = "doorbell"
    THERMOSTAT = "thermostat"
    BABY_MONITOR = "baby_monitor"


class MonitorStatus(Enum):
    """Current status of a monitor."""

    PENDING = auto()  # Created but not started
    RUNNING = auto()  # Actively monitoring
    PAUSED = auto()  # Temporarily stopped
    COMPLETED = auto()  # Finished (for finite monitors)
    CANCELLED = auto()  # User cancelled
    ERROR = auto()  # Failed with error


class AlertSeverity(Enum):
    """Severity level for monitor alerts."""

    INFO = "info"  # Informational update
    WARNING = "warning"  # Potentially concerning
    URGENT = "urgent"  # Requires attention


# ============================================================================
# Data Classes
# ============================================================================


@dataclass
class WeatherForecast:
    """Weather forecast for a specific date."""

    date: str
    condition: str  # sunny, cloudy, rainy, stormy
    high_temp_f: int
    low_temp_f: int
    precipitation_chance: int  # 0-100
    description: str

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "date": self.date,
            "condition": self.condition,
            "high_temp_f": self.high_temp_f,
            "low_temp_f": self.low_temp_f,
            "precipitation_chance": self.precipitation_chance,
            "description": self.description,
        }


@dataclass
class MonitorAlert:
    """Alert generated by a background monitor."""

    alert_id: str
    monitor_id: str
    monitor_type: MonitorType
    severity: AlertSeverity
    message: str
    data: Dict[str, Any]
    created_at: datetime = field(default_factory=datetime.now)
    acknowledged: bool = False
    suggested_action: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "monitor_id": self.monitor_id,
            "monitor_type": self.monitor_type.value,
            "severity": self.severity.value,
            "message": self.message,
            "data": self.data,
            "created_at": self.created_at.isoformat(),
            "acknowledged": self.acknowledged,
            "suggested_action": self.suggested_action,
        }


@dataclass
class BackgroundMonitor:
    """Represents an active background monitor."""

    monitor_id: str
    monitor_type: MonitorType
    target: str  # Location, item, etc.
    status: MonitorStatus = MonitorStatus.PENDING
    created_at: datetime = field(default_factory=datetime.now)
    started_at: Optional[datetime] = None
    stopped_at: Optional[datetime] = None
    check_count: int = 0
    last_check_at: Optional[datetime] = None
    dates: List[str] = field(default_factory=list)
    alert_conditions: List[str] = field(default_factory=list)
    alerts: List[MonitorAlert] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "monitor_id": self.monitor_id,
            "monitor_type": self.monitor_type.value,
            "target": self.target,
            "status": self.status.name,
            "created_at": self.created_at.isoformat(),
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "stopped_at": self.stopped_at.isoformat() if self.stopped_at else None,
            "check_count": self.check_count,
            "dates": self.dates,
            "alert_conditions": self.alert_conditions,
            "alerts_count": len(self.alerts),
        }


# ============================================================================
# Monitor Store (Singleton)
# ============================================================================


class MonitorStore:
    """
    Singleton store for background monitors.
    Tracks all active and historical monitors.
    """

    _instance: Optional["MonitorStore"] = None

    def __new__(cls) -> "MonitorStore":
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._monitors: Dict[str, BackgroundMonitor] = {}
            cls._instance._alerts: List[MonitorAlert] = []
            cls._instance._demo_turn: int = 0  # For weather trigger
        return cls._instance

    @classmethod
    def reset(cls) -> None:
        """Reset the singleton for testing."""
        cls._instance = None

    def add_monitor(self, monitor: BackgroundMonitor) -> None:
        """Add a monitor to the store."""
        self._monitors[monitor.monitor_id] = monitor

    def get_monitor(self, monitor_id: str) -> Optional[BackgroundMonitor]:
        """Get a monitor by ID."""
        return self._monitors.get(monitor_id)

    def get_active_monitors(self) -> List[BackgroundMonitor]:
        """Get all active monitors."""
        return [
            m
            for m in self._monitors.values()
            if m.status in (MonitorStatus.RUNNING, MonitorStatus.PENDING)
        ]

    def get_monitors_by_type(self, monitor_type: MonitorType) -> List[BackgroundMonitor]:
        """Get all monitors of a specific type."""
        return [m for m in self._monitors.values() if m.monitor_type == monitor_type]

    def get_all_monitors(self) -> List[BackgroundMonitor]:
        """Get all monitors."""
        return list(self._monitors.values())

    def add_alert(self, alert: MonitorAlert) -> None:
        """Add an alert."""
        self._alerts.append(alert)
        # Also add to the monitor
        if monitor := self._monitors.get(alert.monitor_id):
            monitor.alerts.append(alert)

    def get_pending_alerts(self) -> List[MonitorAlert]:
        """Get unacknowledged alerts."""
        return [a for a in self._alerts if not a.acknowledged]

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Mark an alert as acknowledged."""
        for alert in self._alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def set_demo_turn(self, turn: int) -> None:
        """Set the current demo turn for weather simulation."""
        self._demo_turn = turn

    def get_demo_turn(self) -> int:
        """Get the current demo turn."""
        return self._demo_turn


# ============================================================================
# Weather Simulation Data
# ============================================================================


def get_initial_forecast(location: str, dates: List[str]) -> List[WeatherForecast]:
    """
    Get the initial weather forecast (before Turn 24).
    Shows beautiful weather for the weekend.
    """
    forecasts = []

    for i, date in enumerate(dates):
        if "saturday" in date.lower() or i == 0:
            forecasts.append(
                WeatherForecast(
                    date=date,
                    condition="sunny",
                    high_temp_f=72,
                    low_temp_f=55,
                    precipitation_chance=5,
                    description=f"Beautiful day in {location}. Clear skies and warm.",
                )
            )
        elif "sunday" in date.lower() or i == 1:
            # Initially shows good weather
            forecasts.append(
                WeatherForecast(
                    date=date,
                    condition="sunny",
                    high_temp_f=70,
                    low_temp_f=54,
                    precipitation_chance=10,
                    description=f"Another lovely day in {location}. Perfect for outdoor activities.",
                )
            )
        else:
            forecasts.append(
                WeatherForecast(
                    date=date,
                    condition="partly_cloudy",
                    high_temp_f=68,
                    low_temp_f=52,
                    precipitation_chance=15,
                    description="Mostly pleasant with some clouds.",
                )
            )

    return forecasts


def get_updated_forecast(location: str, dates: List[str]) -> List[WeatherForecast]:
    """
    Get the updated weather forecast (at Turn 24).
    Shows rain coming Sunday afternoon - triggers proactive alert!
    """
    forecasts = []

    for i, date in enumerate(dates):
        if "saturday" in date.lower() or i == 0:
            # Saturday still looks great
            forecasts.append(
                WeatherForecast(
                    date=date,
                    condition="sunny",
                    high_temp_f=72,
                    low_temp_f=55,
                    precipitation_chance=5,
                    description=f"Beautiful day in {location}. Clear skies and warm.",
                )
            )
        elif "sunday" in date.lower() or i == 1:
            # Sunday afternoon rain incoming!
            forecasts.append(
                WeatherForecast(
                    date=date,
                    condition="rainy",
                    high_temp_f=65,
                    low_temp_f=50,
                    precipitation_chance=60,
                    description="Morning partly cloudy, but 60% chance of rain Sunday afternoon. Consider indoor activities after lunch.",
                )
            )
        else:
            forecasts.append(
                WeatherForecast(
                    date=date,
                    condition="rainy",
                    high_temp_f=62,
                    low_temp_f=48,
                    precipitation_chance=70,
                    description="Rain expected.",
                )
            )

    return forecasts


def check_weather_alerts(
    monitor: BackgroundMonitor,
    old_forecast: List[WeatherForecast],
    new_forecast: List[WeatherForecast],
) -> Optional[MonitorAlert]:
    """
    Compare forecasts and generate alert if conditions changed significantly.
    Returns alert if rain/storm detected in new forecast but not in old.
    """
    for old, new in zip(old_forecast, new_forecast):
        # Check if precipitation increased significantly
        if new.precipitation_chance > old.precipitation_chance + 30:
            # Check if alert condition matches
            should_alert = False
            for condition in monitor.alert_conditions:
                if condition.lower() in ["rain", "rainy"]:
                    if new.condition == "rainy" or new.precipitation_chance >= 50:
                        should_alert = True
                        break
                elif condition.lower() in ["storm", "stormy"]:
                    if new.condition == "stormy":
                        should_alert = True
                        break

            if should_alert:
                return MonitorAlert(
                    alert_id=f"alert-{uuid.uuid4().hex[:8]}",
                    monitor_id=monitor.monitor_id,
                    monitor_type=MonitorType.WEATHER,
                    severity=AlertSeverity.WARNING,
                    message=(
                        f"Weather update for {monitor.target}: "
                        f"Saturday looks beautiful (72F, sunny), but there's now a "
                        f"{new.precipitation_chance}% chance of rain {new.date} afternoon. "
                        f"You might want to plan indoor activities for {new.date}."
                    ),
                    data={
                        "location": monitor.target,
                        "date": new.date,
                        "condition": new.condition,
                        "precipitation_chance": new.precipitation_chance,
                        "old_forecast": old.to_dict(),
                        "new_forecast": new.to_dict(),
                    },
                    suggested_action="book_spa_service",
                )

    return None


# ============================================================================
# Tool Implementations
# ============================================================================


def start_background_monitor(
    monitor_type: str,
    target: str,
    dates: Optional[List[str]] = None,
    alert_conditions: Optional[List[str]] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Start a background monitor for weather, price, or availability.

    Args:
        monitor_type: Type of monitor ("weather", "price", "availability")
        target: What to monitor (location, item, etc.)
        dates: Dates to monitor (for weather)
        alert_conditions: Conditions that trigger alerts (e.g., ["rain", "storm"])
        metadata: Additional context

    Returns:
        Dict with monitor_id, status, and confirmation message
    """
    store = MonitorStore()

    # Validate monitor type
    try:
        mt = MonitorType(monitor_type.lower())
    except ValueError:
        return {
            "success": False,
            "error": f"Invalid monitor type: {monitor_type}. Valid types: weather, price, availability",
        }

    # Create monitor
    monitor_id = f"mon-{uuid.uuid4().hex[:8]}"
    monitor = BackgroundMonitor(
        monitor_id=monitor_id,
        monitor_type=mt,
        target=target,
        status=MonitorStatus.RUNNING,
        started_at=datetime.now(),
        dates=dates or [],
        alert_conditions=alert_conditions or [],
        metadata=metadata or {},
    )

    # For weather monitors, store initial forecast
    if mt == MonitorType.WEATHER:
        initial_forecast = get_initial_forecast(target, dates or [])
        monitor.metadata["current_forecast"] = [f.to_dict() for f in initial_forecast]
        monitor.metadata["last_forecast_update"] = datetime.now().isoformat()

    store.add_monitor(monitor)

    # Build confirmation message
    if mt == MonitorType.WEATHER:
        conditions_str = ", ".join(alert_conditions) if alert_conditions else "significant changes"
        dates_str = " and ".join(dates) if dates else "upcoming days"
        message = (
            f"Weather monitor started for {target}. "
            f"I'll keep watching the forecast for {dates_str} and alert you about {conditions_str}."
        )
    elif mt == MonitorType.PRICE:
        message = (
            f"Price monitor started for {target}. I'll alert you about significant price changes."
        )
    elif mt == MonitorType.OVEN:
        message = (
            f"Oven monitor started for {target}. "
            f"I'll track the temperature and timer, and alert you when it's done or if something needs attention."
        )
    elif mt == MonitorType.LAUNDRY:
        message = (
            f"Laundry monitor started for {target}. " f"I'll let you know when the cycle is done."
        )
    elif mt == MonitorType.SMOKE_DETECTOR:
        message = (
            f"Smoke detector monitor active for {target}. "
            f"I'll alert immediately if smoke or CO is detected."
        )
    elif mt == MonitorType.DOORBELL:
        message = (
            f"Doorbell monitor active for {target}. "
            f"I'll notify you when someone is at the door."
        )
    elif mt == MonitorType.THERMOSTAT:
        message = (
            f"Thermostat monitor started for {target}. "
            f"I'll track temperature and alert on significant changes."
        )
    elif mt == MonitorType.BABY_MONITOR:
        message = (
            f"Baby monitor active for {target}. "
            f"I'll alert you on sound, motion, or temperature changes in the nursery."
        )
    else:
        message = (
            f"Availability monitor started for {target}. I'll let you know if availability changes."
        )

    return {
        "success": True,
        "monitor_id": monitor_id,
        "monitor_type": monitor_type,
        "target": target,
        "status": "running",
        "message": message,
        "dates": dates,
        "alert_conditions": alert_conditions,
    }


def stop_background_monitor(
    monitor_id: str,
    reason: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Stop a running background monitor.

    Args:
        monitor_id: ID of the monitor to stop
        reason: Optional reason for stopping

    Returns:
        Dict with success status and confirmation
    """
    store = MonitorStore()

    monitor = store.get_monitor(monitor_id)
    if not monitor:
        return {
            "success": False,
            "error": f"Monitor not found: {monitor_id}",
        }

    if monitor.status not in (MonitorStatus.RUNNING, MonitorStatus.PENDING, MonitorStatus.PAUSED):
        return {
            "success": False,
            "error": f"Monitor {monitor_id} is already stopped (status: {monitor.status.name})",
        }

    # Update monitor status
    monitor.status = MonitorStatus.CANCELLED
    monitor.stopped_at = datetime.now()
    if reason:
        monitor.metadata["cancel_reason"] = reason

    return {
        "success": True,
        "monitor_id": monitor_id,
        "previous_status": "running",
        "new_status": "cancelled",
        "message": f"{monitor.monitor_type.value.title()} monitor for {monitor.target} has been stopped.",
        "total_checks": monitor.check_count,
        "alerts_generated": len(monitor.alerts),
    }


def check_monitors(demo_turn: Optional[int] = None) -> List[MonitorAlert]:
    """
    Check all active monitors and generate alerts if conditions are met.
    This is called periodically or at specific demo turns.

    At Turn 24, the weather forecast changes to trigger the proactive alert.

    Args:
        demo_turn: Current demo turn number (for weather simulation)

    Returns:
        List of new alerts generated
    """
    store = MonitorStore()

    if demo_turn is not None:
        store.set_demo_turn(demo_turn)

    new_alerts = []
    current_turn = store.get_demo_turn()

    for monitor in store.get_active_monitors():
        if monitor.monitor_type == MonitorType.WEATHER:
            # Update check count
            monitor.check_count += 1
            monitor.last_check_at = datetime.now()

            # At Turn 24, weather changes!
            if current_turn >= 24:
                old_forecast_data = monitor.metadata.get("current_forecast", [])
                old_forecast = [
                    WeatherForecast(**f) if isinstance(f, dict) else f for f in old_forecast_data
                ]

                new_forecast = get_updated_forecast(monitor.target, monitor.dates)

                # Check for alerts
                alert = check_weather_alerts(monitor, old_forecast, new_forecast)
                if alert:
                    # Only alert once
                    if not any(a.monitor_id == monitor.monitor_id for a in store._alerts):
                        store.add_alert(alert)
                        new_alerts.append(alert)

                # Update stored forecast
                monitor.metadata["current_forecast"] = [f.to_dict() for f in new_forecast]
                monitor.metadata["last_forecast_update"] = datetime.now().isoformat()

        elif monitor.monitor_type == MonitorType.OVEN:
            monitor.check_count += 1
            monitor.last_check_at = datetime.now()
            # Simulate oven timer finishing after N checks
            checks_to_alert = monitor.metadata.get("checks_to_alert", 3)
            if monitor.check_count >= checks_to_alert and not any(
                a.monitor_id == monitor.monitor_id for a in store._alerts
            ):
                alert = MonitorAlert(
                    alert_id=f"alert-{uuid.uuid4().hex[:8]}",
                    monitor_id=monitor.monitor_id,
                    monitor_type=MonitorType.OVEN,
                    severity=AlertSeverity.WARNING,
                    message=(
                        f"Oven timer done! {monitor.target} should be ready. "
                        f"Current temperature: {monitor.metadata.get('temp_f', 375)}F. "
                        f"Please check and turn off the oven."
                    ),
                    data={
                        "target": monitor.target,
                        "temp_f": monitor.metadata.get("temp_f", 375),
                        "elapsed_minutes": monitor.metadata.get("cook_time_minutes", 45),
                    },
                    suggested_action="Turn off oven and check food",
                )
                store.add_alert(alert)
                new_alerts.append(alert)

        elif monitor.monitor_type == MonitorType.LAUNDRY:
            monitor.check_count += 1
            monitor.last_check_at = datetime.now()
            checks_to_alert = monitor.metadata.get("checks_to_alert", 3)
            if monitor.check_count >= checks_to_alert and not any(
                a.monitor_id == monitor.monitor_id for a in store._alerts
            ):
                alert = MonitorAlert(
                    alert_id=f"alert-{uuid.uuid4().hex[:8]}",
                    monitor_id=monitor.monitor_id,
                    monitor_type=MonitorType.LAUNDRY,
                    severity=AlertSeverity.INFO,
                    message=f"Laundry cycle complete for {monitor.target}. Time to move to dryer!",
                    data={"target": monitor.target, "cycle": "wash"},
                    suggested_action="Move laundry to dryer",
                )
                store.add_alert(alert)
                new_alerts.append(alert)

        elif monitor.monitor_type == MonitorType.SMOKE_DETECTOR:
            monitor.check_count += 1
            monitor.last_check_at = datetime.now()
            # Smoke detectors only alert on actual events (simulated trigger)
            if monitor.metadata.get("trigger_alert"):
                alert = MonitorAlert(
                    alert_id=f"alert-{uuid.uuid4().hex[:8]}",
                    monitor_id=monitor.monitor_id,
                    monitor_type=MonitorType.SMOKE_DETECTOR,
                    severity=AlertSeverity.URGENT,
                    message=f"SMOKE DETECTED at {monitor.target}! Check immediately.",
                    data={"target": monitor.target, "level": "elevated"},
                    suggested_action="Check the area immediately",
                )
                store.add_alert(alert)
                new_alerts.append(alert)
                monitor.metadata["trigger_alert"] = False

        elif monitor.monitor_type == MonitorType.BABY_MONITOR:
            monitor.check_count += 1
            monitor.last_check_at = datetime.now()
            if monitor.metadata.get("trigger_alert"):
                alert = MonitorAlert(
                    alert_id=f"alert-{uuid.uuid4().hex[:8]}",
                    monitor_id=monitor.monitor_id,
                    monitor_type=MonitorType.BABY_MONITOR,
                    severity=AlertSeverity.WARNING,
                    message=f"Activity detected on baby monitor for {monitor.target}. Sound level elevated.",
                    data={"target": monitor.target, "sound_level": "elevated"},
                    suggested_action="Check on baby",
                )
                store.add_alert(alert)
                new_alerts.append(alert)
                monitor.metadata["trigger_alert"] = False

    return new_alerts


def get_weather_forecast(
    location: str,
    dates: List[str],
    demo_turn: Optional[int] = None,
) -> Dict[str, Any]:
    """
    Get current weather forecast for a location.
    Forecast changes at Turn 24 for the demo.

    Args:
        location: Location to check
        dates: Dates to get forecast for
        demo_turn: Current demo turn (controls which forecast to return)

    Returns:
        Dict with forecast data
    """
    store = MonitorStore()

    if demo_turn is not None:
        store.set_demo_turn(demo_turn)

    current_turn = store.get_demo_turn()

    if current_turn >= 24:
        forecasts = get_updated_forecast(location, dates)
    else:
        forecasts = get_initial_forecast(location, dates)

    return {
        "success": True,
        "location": location,
        "forecast": [f.to_dict() for f in forecasts],
        "last_updated": datetime.now().isoformat(),
    }


def get_monitor_status(monitor_id: str) -> Dict[str, Any]:
    """
    Get the current status of a monitor.

    Args:
        monitor_id: ID of the monitor

    Returns:
        Dict with monitor details and status
    """
    store = MonitorStore()

    monitor = store.get_monitor(monitor_id)
    if not monitor:
        return {
            "success": False,
            "error": f"Monitor not found: {monitor_id}",
        }

    return {
        "success": True,
        **monitor.to_dict(),
        "pending_alerts": len([a for a in monitor.alerts if not a.acknowledged]),
    }


def list_active_monitors() -> Dict[str, Any]:
    """
    List all active background monitors.

    Returns:
        Dict with list of active monitors
    """
    store = MonitorStore()

    active = store.get_active_monitors()

    return {
        "success": True,
        "count": len(active),
        "monitors": [m.to_dict() for m in active],
    }


def execute_monitor_tool(tool_name: str, params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Execute a monitor tool by name.

    Args:
        tool_name: Name of the tool
        params: Tool parameters

    Returns:
        Tool result
    """
    tools = {
        "start_background_monitor": start_background_monitor,
        "stop_background_monitor": stop_background_monitor,
        "check_monitors": check_monitors,
        "get_weather_forecast": get_weather_forecast,
        "get_monitor_status": get_monitor_status,
        "list_active_monitors": list_active_monitors,
    }

    if tool_name not in tools:
        return {
            "success": False,
            "error": f"Unknown monitor tool: {tool_name}",
        }

    return tools[tool_name](**params)


# ============================================================================
# Tool Schemas for LLM
# ============================================================================


MONITOR_TOOLS = {
    "start_background_monitor": {
        "name": "start_background_monitor",
        "description": "Start monitoring something in the background (weather, prices, availability). Runs concurrently with conversation and alerts proactively.",
        "parameters": {
            "type": "object",
            "required": ["monitor_type", "target"],
            "properties": {
                "monitor_type": {
                    "type": "string",
                    "enum": ["weather", "price", "availability"],
                    "description": "Type of monitor to start",
                },
                "target": {
                    "type": "string",
                    "description": "What to monitor (location, item name, etc.)",
                },
                "dates": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Dates to monitor (for weather)",
                },
                "alert_conditions": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Conditions that trigger alerts (e.g., 'rain', 'storm', 'price_drop')",
                },
            },
        },
    },
    "stop_background_monitor": {
        "name": "stop_background_monitor",
        "description": "Stop a running background monitor",
        "parameters": {
            "type": "object",
            "required": ["monitor_id"],
            "properties": {
                "monitor_id": {
                    "type": "string",
                    "description": "ID of the monitor to stop",
                },
                "reason": {
                    "type": "string",
                    "description": "Reason for stopping the monitor",
                },
            },
        },
    },
    "get_monitor_status": {
        "name": "get_monitor_status",
        "description": "Get the current status of a background monitor",
        "parameters": {
            "type": "object",
            "required": ["monitor_id"],
            "properties": {
                "monitor_id": {
                    "type": "string",
                    "description": "ID of the monitor to check",
                },
            },
        },
    },
    "list_active_monitors": {
        "name": "list_active_monitors",
        "description": "List all currently active background monitors",
        "parameters": {
            "type": "object",
            "properties": {},
        },
    },
}
