# automatically generated by the FlatBuffers compiler, do not modify

# namespace: actor_fabric

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Generic message envelope for actor mailbox communication
# Performance: Serialization <1ms P95, zero-copy deserialization
# Size: ~200 bytes average (small), ~2KB max (medium)
class MessageEnvelope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMessageEnvelope(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageEnvelope()
        x.Init(buf, n + offset)
        return x

    # MessageEnvelope
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageEnvelope
    def SenderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MessageEnvelope
    def ReceiverId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MessageEnvelope
    def MessageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MessageEnvelope
    def Priority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 2

    # MessageEnvelope
    def Payload(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MessageEnvelope
    def PayloadAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # MessageEnvelope
    def PayloadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MessageEnvelope
    def PayloadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # MessageEnvelope
    def TtlMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 5000

    # MessageEnvelope
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # MessageEnvelope
    def TraceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MessageEnvelope
    def CorrelationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MessageEnvelope
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

def MessageEnvelopeStart(builder): builder.StartObject(10)
def MessageEnvelopeAddSenderId(builder, senderId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(senderId), 0)
def MessageEnvelopeAddReceiverId(builder, receiverId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(receiverId), 0)
def MessageEnvelopeAddMessageType(builder, messageType): builder.PrependInt8Slot(2, messageType, 0)
def MessageEnvelopeAddPriority(builder, priority): builder.PrependInt8Slot(3, priority, 2)
def MessageEnvelopeAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def MessageEnvelopeStartPayloadVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def MessageEnvelopeAddTtlMs(builder, ttlMs): builder.PrependUint32Slot(5, ttlMs, 5000)
def MessageEnvelopeAddCreatedAt(builder, createdAt): builder.PrependInt64Slot(6, createdAt, 0)
def MessageEnvelopeAddTraceId(builder, traceId): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)
def MessageEnvelopeAddCorrelationId(builder, correlationId): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(correlationId), 0)
def MessageEnvelopeAddVersion(builder, version): builder.PrependUint16Slot(9, version, 1)
def MessageEnvelopeEnd(builder): return builder.EndObject()
