# automatically generated by the FlatBuffers compiler, do not modify

# namespace: actor_fabric

# Message type classification
class MessageType(object):
    TASK_ANNOUNCEMENT = 0
    BID_SUBMISSION = 1
    TASK_ASSIGNMENT = 2
    TASK_COMPLETION = 3
    STATE_UPDATE = 4
    CONTROL_MESSAGE = 5
    FEEDBACK_SIGNAL = 6
    CAPABILITY_GRANT = 7
    PROTOCOL_VIOLATION = 8
    AGENT_HIRE_REQUEST = 9
    AGENT_HIRE_RESPONSE = 10
    GENERIC = 127

