# automatically generated by the FlatBuffers compiler, do not modify

# namespace: actor_fabric

# Message priority levels for mailbox routing
# Maps to 4-tier priority scheduler (Issue 2.2)
class MessagePriority(object):
    URGENT = 0
    REALTIME = 1
    INTERACTIVE = 2
    BACKGROUND = 3

