"""
k1.concierge.task.dispatch -- TaskDispatch, TaskComplete, TaskFailed dataclasses.

V2 Design Ref: Section 8.2 (TaskDispatch, TaskComplete, TaskFailed schemas)
V2 Design Ref: Section 6.2 (BACK_MAX_ITERATIONS, budget_hint derivation)

These are the canonical bus payloads for task orchestration:

    TaskDispatch  -- Front -> Back via k1.orchestration.task.dispatch.v1
    TaskComplete  -- Back -> Front via k1.orchestration.task.complete.v1
    TaskFailed    -- Back -> Front via k1.orchestration.task.failed.v1

Serialization uses JSON for POC (production would use FlatBuffers via
k1.bus.envelope). All payloads support round-trip serialization through
to_dict/from_dict and to_payload/from_payload (JSON bytes).

Key invariants:
    - TaskDispatch.intents is non-empty (at least one intent required)
    - budget_hint auto-computed from tier if not explicitly set
    - depends_on must be a valid task ID (task-...) if provided
    - safety_band defaults to AMBER (assume side effects need approval)
    - TaskComplete.status is always "success"
    - TaskFailed.status is always "error"
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import Any

from k1.concierge.task.complexity import ComplexityTier, budget_for_tier
from k1.concierge.task.intent import TaskIntent

# =========================================================================
# Safety band values (V2 Section 8.2)
# =========================================================================
_VALID_SAFETY_BANDS = frozenset({"GREEN", "AMBER", "RED"})


# =========================================================================
# TaskDispatch -- Front -> Back
# =========================================================================


@dataclass
class TaskDispatch:
    """Payload for k1.orchestration.task.dispatch.v1.

    Created by the tool dispatcher when Front calls dispatch_task()
    (V2 Section 6.1). The task_id is system-generated -- the LLM does
    not create IDs.

    Attributes:
        task_id:           Unique task identifier (UUID prefixed with "task-").
                           System-generated by the tool dispatcher.
        intents:           One or more intents to execute. Single intent is
                           the common case. Multiple = bundled (V2 Section 17.3).
        tier:              Complexity classification (LOW/MEDIUM/HIGH).
                           Determines Back's iteration budget and tool allowlist.
        budget_hint:       Max tool-call iterations for Back ReAct loop.
                           Auto-computed from tier if not explicitly set.
        reference_context: Front-resolved pronoun and reference mappings.
                           Example: {"it": "Vineyard Inn", "those dates": "June 15-17"}
                           Back reads this in STEP 1 (ORIENT) to resolve references.
        safety_band:       GREEN / AMBER / RED. Copied from SS control.safety_band.
                           Back checks this in STEP 5 (SAFETY CHECK) before invoke.
                           Default AMBER: assume side effects require approval.
        depends_on:        Task ID this depends on (chained tasks, V2 Section 17.4).
                           None = independent task.
        context_snapshot:  Relevant SessionState sections at dispatch time.
                           Provides Back with cognitive context without
                           requiring a separate SS read.
    """

    intents: list[TaskIntent]
    tier: ComplexityTier = ComplexityTier.LOW
    task_id: str = field(default_factory=lambda: f"task-{uuid.uuid4().hex[:8]}")
    budget_hint: int | None = None
    reference_context: dict[str, str] | None = None
    safety_band: str = "AMBER"
    depends_on: str | None = None
    context_snapshot: dict[str, Any] | None = None

    def __post_init__(self) -> None:
        if not self.intents:
            raise ValueError("TaskDispatch must have at least one intent")
        if self.budget_hint is None:
            self.budget_hint = budget_for_tier(self.tier)
        if self.depends_on is not None and not self.depends_on.startswith("task-"):
            raise ValueError(f"depends_on must be a task ID (task-...), got '{self.depends_on}'")
        if self.safety_band not in _VALID_SAFETY_BANDS:
            raise ValueError(
                f"safety_band must be one of {sorted(_VALID_SAFETY_BANDS)}, "
                f"got '{self.safety_band}'"
            )

    @property
    def is_bundled(self) -> bool:
        """True if this dispatch contains multiple independent intents."""
        return len(self.intents) > 1

    @property
    def is_chained(self) -> bool:
        """True if this task depends on another task's result."""
        return self.depends_on is not None

    @property
    def has_refs(self) -> bool:
        """True if any intent contains $ref placeholders."""
        return any(i.has_refs() for i in self.intents)

    def to_payload(self) -> bytes:
        """Serialize to JSON bytes for bus envelope payload."""
        return json.dumps(self.to_dict(), separators=(",", ":")).encode("utf-8")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict.

        Only includes non-default optional fields to minimize payload.
        """
        d: dict[str, Any] = {
            "task_id": self.task_id,
            "intents": [i.to_dict() for i in self.intents],
            "tier": self.tier.value,
            "budget_hint": self.budget_hint,
            "safety_band": self.safety_band,
        }
        if self.reference_context is not None:
            d["reference_context"] = self.reference_context
        if self.depends_on is not None:
            d["depends_on"] = self.depends_on
        if self.context_snapshot is not None:
            d["context_snapshot"] = self.context_snapshot
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskDispatch:
        """Deserialize from dict."""
        return cls(
            task_id=data["task_id"],
            intents=[TaskIntent.from_dict(i) for i in data["intents"]],
            tier=ComplexityTier(data["tier"]),
            budget_hint=data.get("budget_hint"),
            reference_context=data.get("reference_context"),
            safety_band=data.get("safety_band", "AMBER"),
            depends_on=data.get("depends_on"),
            context_snapshot=data.get("context_snapshot"),
        )

    @classmethod
    def from_payload(cls, payload: bytes) -> TaskDispatch:
        """Deserialize from bus envelope payload bytes."""
        return cls.from_dict(json.loads(payload.decode("utf-8")))


# =========================================================================
# TaskComplete -- Back -> Front (success path)
# =========================================================================


@dataclass
class TaskComplete:
    """Payload for k1.orchestration.task.complete.v1.

    Produced by back_handler (V2 Section 6.2) from ReactResult.data
    when submit_result(complete) is called.

    Attributes:
        task_id:                 Which task completed.
        final_answer:            Technical summary. NOT user-facing text.
                                 Example: "Booked Vineyard Inn, Sonoma. 2 nights."
                                 Front rewrites this in its own voice.
        results:                 Structured data the presenter needs. Each object
                                 has consistent keys within the result set.
        artifacts_created:       Durable outputs persisted in task_artifacts.
                                 Each entry: {type: str, summary: str, data: dict}.
        completed_before_cancel: Race condition flag. If True, the task completed
                                 after a cancel was emitted but before Back could
                                 check cancellation_check(). Front decides: present
                                 result + offer to undo, or discard.
        tool_calls:              Number of tool calls consumed (budget tracking).
    """

    task_id: str
    final_answer: str = ""
    results: list[dict[str, Any]] = field(default_factory=list)
    artifacts_created: list[dict[str, Any]] = field(default_factory=list)
    completed_before_cancel: bool = False
    tool_calls: int = 0
    tool_call_summaries: list[dict[str, Any]] = field(default_factory=list)

    def to_payload(self) -> bytes:
        """Serialize to JSON bytes for bus envelope payload."""
        return json.dumps(self.to_dict(), separators=(",", ":")).encode("utf-8")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict."""
        d: dict[str, Any] = {
            "task_id": self.task_id,
            "status": "success",
            "final_answer": self.final_answer,
            "results": self.results,
            "tool_calls": self.tool_calls,
        }
        if self.artifacts_created:
            d["artifacts_created"] = self.artifacts_created
        if self.completed_before_cancel:
            d["completed_before_cancel"] = True
        if self.tool_call_summaries:
            d["tool_call_summaries"] = self.tool_call_summaries
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskComplete:
        """Deserialize from dict."""
        return cls(
            task_id=data["task_id"],
            final_answer=data.get("final_answer", ""),
            results=data.get("results", []),
            artifacts_created=data.get("artifacts_created", []),
            completed_before_cancel=data.get("completed_before_cancel", False),
            tool_calls=data.get("tool_calls", 0),
            tool_call_summaries=data.get("tool_call_summaries", []),
        )

    @classmethod
    def from_payload(cls, payload: bytes) -> TaskComplete:
        """Deserialize from bus envelope payload bytes."""
        return cls.from_dict(json.loads(payload.decode("utf-8")))


# =========================================================================
# TaskFailed -- Back -> Front (error path)
# =========================================================================

_VALID_FAILURE_REASONS = frozenset(
    {
        "budget_exhausted",
        "cancelled",
        "capability_not_found",
        "capability_failed",
        "workflow_failed",
        "agent_failed",
        "timeout",
        "internal_error",
    }
)


@dataclass
class TaskFailed:
    """Payload for k1.orchestration.task.failed.v1.

    The most diagnostic event in the system (V2 Section 8.2).
    Carries enough context for Front to explain the failure gracefully
    and for observability to diagnose root cause without log diving.

    Attributes:
        task_id:            Which task failed.
        reason:             Why it failed. Extensible enum-like string.
        error_code:         Machine-readable error code from the failed
                            capability, if available.
        tool_history:       Summary of tool calls made before failure.
                            Each entry: {tool, args_summary, result_summary, success}.
        partial_results:    Any successful results obtained before failure.
        retries_attempted:  How many retries Back tried before giving up.
                            Max 1 retry per capability (2 total attempts).
        last_error_detail:  Human-readable error detail from the last
                            failed operation. Front translates into
                            conversational language (never shown raw).
    """

    task_id: str
    reason: str
    error_code: str | None = None
    tool_history: list[dict[str, Any]] = field(default_factory=list)
    partial_results: list[dict[str, Any]] = field(default_factory=list)
    retries_attempted: int = 0
    last_error_detail: str | None = None

    def __post_init__(self) -> None:
        if self.reason not in _VALID_FAILURE_REASONS:
            raise ValueError(
                f"TaskFailed.reason must be one of {sorted(_VALID_FAILURE_REASONS)}, "
                f"got '{self.reason}'"
            )

    def to_payload(self) -> bytes:
        """Serialize to JSON bytes for bus envelope payload."""
        return json.dumps(self.to_dict(), separators=(",", ":")).encode("utf-8")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict."""
        d: dict[str, Any] = {
            "task_id": self.task_id,
            "status": "error",
            "reason": self.reason,
        }
        if self.error_code is not None:
            d["error_code"] = self.error_code
        if self.tool_history:
            d["tool_history"] = self.tool_history
        if self.partial_results:
            d["partial_results"] = self.partial_results
        if self.retries_attempted > 0:
            d["retries_attempted"] = self.retries_attempted
        if self.last_error_detail is not None:
            d["last_error_detail"] = self.last_error_detail
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskFailed:
        """Deserialize from dict."""
        return cls(
            task_id=data["task_id"],
            reason=data["reason"],
            error_code=data.get("error_code"),
            tool_history=data.get("tool_history", []),
            partial_results=data.get("partial_results", []),
            retries_attempted=data.get("retries_attempted", 0),
            last_error_detail=data.get("last_error_detail"),
        )

    @classmethod
    def from_payload(cls, payload: bytes) -> TaskFailed:
        """Deserialize from bus envelope payload bytes."""
        return cls.from_dict(json.loads(payload.decode("utf-8")))
