# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Planning

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CommittedStep(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCommittedStep(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommittedStep()
        x.Init(buf, n + offset)
        return x

    # CommittedStep
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommittedStep
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommittedStep
    def Tool(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommittedStep
    def Agent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommittedStep
    def BandRequired(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CommittedStep
    def EstLatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CommittedStep
    def CostHint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CommittedStep
    def Needs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # CommittedStep
    def NeedsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CommittedStep
    def NeedsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def CommittedStepStart(builder): builder.StartObject(7)
def CommittedStepAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def CommittedStepAddTool(builder, tool): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tool), 0)
def CommittedStepAddAgent(builder, agent): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(agent), 0)
def CommittedStepAddBandRequired(builder, bandRequired): builder.PrependUint8Slot(3, bandRequired, 0)
def CommittedStepAddEstLatencyMs(builder, estLatencyMs): builder.PrependUint32Slot(4, estLatencyMs, 0)
def CommittedStepAddCostHint(builder, costHint): builder.PrependFloat32Slot(5, costHint, 0.0)
def CommittedStepAddNeeds(builder, needs): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(needs), 0)
def CommittedStepStartNeedsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CommittedStepEnd(builder): return builder.EndObject()
