# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Planning

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExpandedPlan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsExpandedPlan(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExpandedPlan()
        x.Init(buf, n + offset)
        return x

    # ExpandedPlan
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExpandedPlan
    def SketchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExpandedPlan
    def TurnId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExpandedPlan
    def Intent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExpandedPlan
    def Steps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from K1.Planning.FlowStep import FlowStep
            obj = FlowStep()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExpandedPlan
    def StepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExpandedPlan
    def StepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ExpandedPlan
    def Complexity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ExpandedPlan
    def AgentsRequired(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ExpandedPlan
    def AgentsRequiredLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExpandedPlan
    def AgentsRequiredIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ExpandedPlan
    def ExpandLatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ExpandedPlanStart(builder): builder.StartObject(7)
def ExpandedPlanAddSketchId(builder, sketchId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sketchId), 0)
def ExpandedPlanAddTurnId(builder, turnId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)
def ExpandedPlanAddIntent(builder, intent): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(intent), 0)
def ExpandedPlanAddSteps(builder, steps): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(steps), 0)
def ExpandedPlanStartStepsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ExpandedPlanAddComplexity(builder, complexity): builder.PrependUint8Slot(4, complexity, 0)
def ExpandedPlanAddAgentsRequired(builder, agentsRequired): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(agentsRequired), 0)
def ExpandedPlanStartAgentsRequiredVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ExpandedPlanAddExpandLatencyMs(builder, expandLatencyMs): builder.PrependUint32Slot(6, expandLatencyMs, 0)
def ExpandedPlanEnd(builder): return builder.EndObject()
