# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Planning

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FlowDef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFlowDef(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FlowDef()
        x.Init(buf, n + offset)
        return x

    # FlowDef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FlowDef
    def FlowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FlowDef
    def SketchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FlowDef
    def TurnId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FlowDef
    def Intent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FlowDef
    def Steps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from K1.Planning.CommittedStep import CommittedStep
            obj = CommittedStep()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FlowDef
    def StepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlowDef
    def StepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # FlowDef
    def Complexity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FlowDef
    def AgentsRequired(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FlowDef
    def AgentsRequiredLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FlowDef
    def AgentsRequiredIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # FlowDef
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FlowDef
    def CreatedAt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FlowDef
    def PipelineLatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def FlowDefStart(builder): builder.StartObject(10)
def FlowDefAddFlowId(builder, flowId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(flowId), 0)
def FlowDefAddSketchId(builder, sketchId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sketchId), 0)
def FlowDefAddTurnId(builder, turnId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)
def FlowDefAddIntent(builder, intent): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(intent), 0)
def FlowDefAddSteps(builder, steps): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(steps), 0)
def FlowDefStartStepsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FlowDefAddComplexity(builder, complexity): builder.PrependUint8Slot(5, complexity, 0)
def FlowDefAddAgentsRequired(builder, agentsRequired): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(agentsRequired), 0)
def FlowDefStartAgentsRequiredVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def FlowDefAddStatus(builder, status): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(status), 0)
def FlowDefAddCreatedAt(builder, createdAt): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(createdAt), 0)
def FlowDefAddPipelineLatencyMs(builder, pipelineLatencyMs): builder.PrependUint32Slot(9, pipelineLatencyMs, 0)
def FlowDefEnd(builder): return builder.EndObject()
