# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Planning

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlanStep(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPlanStep(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlanStep()
        x.Init(buf, n + offset)
        return x

    # PlanStep
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlanStep
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlanStep
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PlanStep
    def Description(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlanStep
    def Tool(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlanStep
    def Needs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # PlanStep
    def NeedsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PlanStep
    def NeedsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def PlanStepStart(builder): builder.StartObject(5)
def PlanStepAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def PlanStepAddOp(builder, op): builder.PrependUint8Slot(1, op, 0)
def PlanStepAddDescription(builder, description): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)
def PlanStepAddTool(builder, tool): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(tool), 0)
def PlanStepAddNeeds(builder, needs): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(needs), 0)
def PlanStepStartNeedsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PlanStepEnd(builder): return builder.EndObject()
