# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Planning

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Sketch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSketch(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Sketch()
        x.Init(buf, n + offset)
        return x

    # Sketch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Sketch
    def SketchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sketch
    def TurnId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sketch
    def Intent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sketch
    def Steps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from K1.Planning.PlanStep import PlanStep
            obj = PlanStep()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Sketch
    def StepsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Sketch
    def StepsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Sketch
    def Complexity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Sketch
    def ModelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Sketch
    def LlmLatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Sketch
    def PromptTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Sketch
    def CompletionTokens(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Sketch
    def RawLlmOutput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SketchStart(builder): builder.StartObject(10)
def SketchAddSketchId(builder, sketchId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sketchId), 0)
def SketchAddTurnId(builder, turnId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)
def SketchAddIntent(builder, intent): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(intent), 0)
def SketchAddSteps(builder, steps): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(steps), 0)
def SketchStartStepsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SketchAddComplexity(builder, complexity): builder.PrependUint8Slot(4, complexity, 0)
def SketchAddModelId(builder, modelId): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(modelId), 0)
def SketchAddLlmLatencyMs(builder, llmLatencyMs): builder.PrependUint32Slot(6, llmLatencyMs, 0)
def SketchAddPromptTokens(builder, promptTokens): builder.PrependUint32Slot(7, promptTokens, 0)
def SketchAddCompletionTokens(builder, completionTokens): builder.PrependUint32Slot(8, completionTokens, 0)
def SketchAddRawLlmOutput(builder, rawLlmOutput): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(rawLlmOutput), 0)
def SketchEnd(builder): return builder.EndObject()
