# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/memory.write.v1.yaml

"""Generated client for the ``memory.write.v1`` contract.

Producer side. Imported by the k1 kernel as the only legitimate
publishing interface for this contract. The bridge runtime injects a real
transport at boot; in-process tests use ``InProcessHttpTransport``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from bridge._generated.k1.models.memory_write_v1 import (
    MemoryWriteV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from bridge.runtime import BridgeRuntime


class MemoryWriteV1Client:
    """Generated client for ``memory.write.v1``.

    The runtime supplies the transport. Direct construction outside the
    runtime is forbidden by the
    ``manifest_implementation_bound`` CI gate.
    """

    __transport__ = "http"
    __topic__ = "memory.write.v1"
    __schema_uri__ = "bridge://contracts/schemas/memory.write.v1.json"
    __codec__ = "json"
    __codecs_allowed__ = ("json",)
    __codec_negotiation__ = "client_choice_in_allowed"

    def __init__(self, runtime: "BridgeRuntime") -> None:
        self._runtime = runtime

    async def publish(self, payload: MemoryWriteV1) -> Any:
        """Publish ``payload`` on ``memory.write.v1``.

        ``payload`` is a Pydantic v2 ``MemoryWriteV1`` instance;
        the runtime serialises it to bytes via the manifest-declared codec
        (``self.__codec__``), wraps non-JSON bodies as ``{_codec, _b64}``
        inside the canonical-JSON envelope, signs the envelope, and hands
        the bytes to the transport.
        """
        if self._runtime.transport is None:
            raise RuntimeError(
                "MemoryWriteV1Client: no transport bound on BridgeRuntime"
            )
        return await self._runtime.transport.publish(
            topic=self.__topic__,
            schema_uri=self.__schema_uri__,
            payload=payload,
            codec=self.__codec__,
        )
