# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/observability.payload.v1.yaml

"""Generated obs/feedback client for the ``observability.payload.v1`` contract.

Producer side (K1). MS-3e: this client posts ``{kind, body}`` to
``/k0/obs.emit`` via a runtime-bound :class:`bridge.core.transport.obs_emitter.ObsHttpEmitter`.
Bypasses the signed-envelope path used by ``/k0/command.submit`` because
observability/feedback ingestion is unsigned and queueable. The K0 side
dispatches by ``kind`` directly inside :mod:`k0.ports.observe`; no
codegen handler is emitted (the consumer-side stub is a no-op).
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from bridge._generated.k1.models.observability_payload_v1 import (
    ObservabilityPayloadV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from bridge.runtime import BridgeRuntime


class ObservabilityPayloadV1Client:
    """Generated K1-side obs/feedback client for ``observability.payload.v1``.

    Direct construction outside the runtime is forbidden by the
    ``manifest_implementation_bound`` CI gate.
    """

    __transport__ = "obs"
    __topic__ = "observability.payload.v1"
    __schema_uri__ = "bridge://contracts/schemas/observability.payload.v1.json"
    __obs_kind__ = "metrics"

    def __init__(self, runtime: "BridgeRuntime") -> None:
        self._runtime = runtime

    async def publish(self, payload: ObservabilityPayloadV1) -> Any:
        """Publish ``payload`` to ``/k0/obs.emit`` with kind=``metrics``.

        Wraps the Pydantic body as ``{"kind": "metrics", "body": payload}``
        before posting. Raises :class:`NotImplementedError` if the runtime
        has no ``_obs_emitter`` bound (boot-time wiring fault).
        """
        emitter = getattr(self._runtime, "_obs_emitter", None)
        if emitter is None:
            raise NotImplementedError(
                "ObservabilityPayloadV1Client.publish: K1 obs emitter not bound "
                "(MS-3e). Ensure BridgeRuntime.from_registry was called with "
                "an HttpTransport so _obs_emitter could be wired."
            )
        return await emitter.emit(
            topic=self.__topic__,
            kind=self.__obs_kind__,
            schema_uri=self.__schema_uri__,
            payload=payload,
        )
