# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/recall.request.v1.yaml

"""Generated client for the ``recall.request.v1`` contract.

Producer side. Imported by the k1 kernel as the only legitimate
publishing interface for this contract. The bridge runtime injects a real
transport at boot; in-process tests use ``InProcessHttpTransport``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from bridge._generated.k1.models.recall_request_v1 import (
    RecallRequestV1,
)
from bridge._generated.k1.models.recall_response_v1 import (
    RecallResponseV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from bridge.runtime import BridgeRuntime


class RecallRequestV1Client:
    """Generated client for ``recall.request.v1``.

    The runtime supplies the transport. Direct construction outside the
    runtime is forbidden by the
    ``manifest_implementation_bound`` CI gate.
    """

    __transport__ = "http"
    __topic__ = "recall.request.v1"
    __schema_uri__ = "bridge://contracts/schemas/recall.request.v1.json"
    __codec__ = "json"
    __codecs_allowed__ = ("json",)
    __codec_negotiation__ = "client_choice_in_allowed"

    def __init__(self, runtime: "BridgeRuntime") -> None:
        self._runtime = runtime

    async def request(self, payload: RecallRequestV1) -> RecallResponseV1:
        """Send ``payload`` on ``recall.request.v1`` and return the paired response.

        Synchronous request/response: ``transport.publish`` returns the
        parsed HTTP response body as a ``dict``; we validate it through
        the paired ``RecallResponseV1`` model so the
        caller never sees raw dicts. Raises ``RuntimeError`` if no
        transport is bound.
        """
        if self._runtime.transport is None:
            raise RuntimeError(
                "RecallRequestV1Client: no transport bound on BridgeRuntime"
            )
        body = await self._runtime.transport.publish(
            topic=self.__topic__,
            schema_uri=self.__schema_uri__,
            payload=payload,
            codec=self.__codec__,
        )
        if isinstance(body, RecallResponseV1):
            return body
        return RecallResponseV1.model_validate(body)

    async def publish(self, payload: RecallRequestV1) -> Any:
        """Compatibility alias for :meth:`request`. Prefer ``request``."""
        return await self.request(payload)
