# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/k0.proactive.signal.v1.yaml

"""Generated Protocol for the ``k0.proactive.signal.v1`` contract.

Imported by the k0 kernel where strong typing on the
publish/handle surface is needed (e.g. memory_writer batch emitters
type-checking against the published shape).
"""

from __future__ import annotations

from collections.abc import AsyncContextManager, Awaitable, Callable
from typing import Protocol, runtime_checkable

from bridge._generated.k0.models.k0_proactive_signal_v1 import (
    K0ProactiveSignalV1,
)


SubscriberHandler = Callable[[K0ProactiveSignalV1], Awaitable[None]]


@runtime_checkable
class IK0ProactiveSignalV1Port(Protocol):
    """Per-contract emit interface for ``k0.proactive.signal.v1`` (SSE)."""

    __topic__: str
    __schema_uri__: str

    async def emit(self, payload: K0ProactiveSignalV1) -> object: ...


@runtime_checkable
class IK0ProactiveSignalV1Subscriber(Protocol):
    """Per-contract subscribe interface for ``k0.proactive.signal.v1`` (SSE)."""

    __topic__: str
    __schema_uri__: str

    def subscribe(
        self,
        handler: SubscriberHandler,
        *,
        cursor: str | None = None,
    ) -> AsyncContextManager[None]: ...
