# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/p03.gap.detected.v1.yaml

"""Generated Protocol for the ``p03.gap.detected.v1`` contract.

Imported by the k0 kernel where strong typing on the
publish/handle surface is needed (e.g. memory_writer batch emitters
type-checking against the published shape).
"""

from __future__ import annotations

from collections.abc import AsyncContextManager, Awaitable, Callable
from typing import Protocol, runtime_checkable

from bridge._generated.k0.models.p03_gap_detected_v1 import (
    P03GapDetectedV1,
)


SubscriberHandler = Callable[[P03GapDetectedV1], Awaitable[None]]


@runtime_checkable
class IP03GapDetectedV1Port(Protocol):
    """Per-contract emit interface for ``p03.gap.detected.v1`` (SSE)."""

    __topic__: str
    __schema_uri__: str

    async def emit(self, payload: P03GapDetectedV1) -> object: ...


@runtime_checkable
class IP03GapDetectedV1Subscriber(Protocol):
    """Per-contract subscribe interface for ``p03.gap.detected.v1`` (SSE)."""

    __topic__: str
    __schema_uri__: str

    def subscribe(
        self,
        handler: SubscriberHandler,
        *,
        cursor: str | None = None,
    ) -> AsyncContextManager[None]: ...
