"""Constants for the k1.grounding kernel module."""

from __future__ import annotations

CONSUMER_FRONT = "front"
CONSUMER_BACK = "back"
CONSUMER_PLANNER = "planner"
CONSUMER_FABRIC = "fabric"
CONSUMER_AGENT = "agent"
CONSUMER_TOOL = "tool"
CONSUMER_MEMORY = "memory"

CONSUMERS: tuple[str, ...] = (
    CONSUMER_FRONT,
    CONSUMER_BACK,
    CONSUMER_PLANNER,
    CONSUMER_FABRIC,
    CONSUMER_AGENT,
    CONSUMER_TOOL,
    CONSUMER_MEMORY,
)

LEASE_STATUS_ACTIVE = "active"
LEASE_STATUS_EXPIRED = "expired"
LEASE_STATUS_REVOKED = "revoked"
LEASE_STATUS_REFRESH_REQUIRED = "refresh_required"

LEASE_STATUSES: tuple[str, ...] = (
    LEASE_STATUS_ACTIVE,
    LEASE_STATUS_EXPIRED,
    LEASE_STATUS_REVOKED,
    LEASE_STATUS_REFRESH_REQUIRED,
)

REDACTION_PRIVACY_SCOPE = "privacy_scope"
REDACTION_PRECISION_DENIED = "precision_denied"
REDACTION_SOURCE_UNAVAILABLE = "source_unavailable"
REDACTION_STALE_SOURCE = "stale_source"

REDACTION_REASONS: tuple[str, ...] = (
    "privacy_scope",
    "precision_denied",
    "source_unavailable",
    "stale_source",
)

GROUNDING_FRESHNESS_LIVE = "live"
GROUNDING_FRESHNESS_STALE = "stale"
GROUNDING_FRESHNESS_DEGRADED = "degraded"
GROUNDING_FRESHNESS_UNAVAILABLE = "unavailable"

GROUNDING_FRESHNESS_STATES: tuple[str, ...] = (
    GROUNDING_FRESHNESS_LIVE,
    GROUNDING_FRESHNESS_STALE,
    GROUNDING_FRESHNESS_DEGRADED,
    GROUNDING_FRESHNESS_UNAVAILABLE,
)

SPATIAL_CONTEXT_UNKNOWN = "unknown"
SPATIAL_PRECISION_HIDDEN = "hidden"

PROPAGATION_FIELD_ENVELOPE_ID = "grounding_envelope_id"
PROPAGATION_FIELD_TEMPORAL_ANCHOR_ID = "temporal_anchor_id"
PROPAGATION_FIELD_SPATIAL_CONTEXT_ID = "spatial_context_id"
PROPAGATION_FIELD_RESOLVED_TEMPORAL_REFS = "resolved_temporal_refs"
PROPAGATION_FIELD_RESOLVED_SPATIAL_REFS = "resolved_spatial_refs"

__all__ = [
    "CONSUMER_AGENT",
    "CONSUMER_BACK",
    "CONSUMER_FABRIC",
    "CONSUMER_FRONT",
    "CONSUMER_MEMORY",
    "CONSUMER_PLANNER",
    "CONSUMER_TOOL",
    "CONSUMERS",
    "GROUNDING_FRESHNESS_DEGRADED",
    "GROUNDING_FRESHNESS_LIVE",
    "GROUNDING_FRESHNESS_STALE",
    "GROUNDING_FRESHNESS_STATES",
    "GROUNDING_FRESHNESS_UNAVAILABLE",
    "LEASE_STATUS_ACTIVE",
    "LEASE_STATUS_EXPIRED",
    "LEASE_STATUS_REFRESH_REQUIRED",
    "LEASE_STATUS_REVOKED",
    "LEASE_STATUSES",
    "PROPAGATION_FIELD_ENVELOPE_ID",
    "PROPAGATION_FIELD_RESOLVED_SPATIAL_REFS",
    "PROPAGATION_FIELD_RESOLVED_TEMPORAL_REFS",
    "PROPAGATION_FIELD_SPATIAL_CONTEXT_ID",
    "PROPAGATION_FIELD_TEMPORAL_ANCHOR_ID",
    "REDACTION_PRECISION_DENIED",
    "REDACTION_PRIVACY_SCOPE",
    "REDACTION_REASONS",
    "REDACTION_SOURCE_UNAVAILABLE",
    "REDACTION_STALE_SOURCE",
    "SPATIAL_CONTEXT_UNKNOWN",
    "SPATIAL_PRECISION_HIDDEN",
]
