CREATE (user:Person {node_id: "person_user_001", label: "User", name: "Primary User"});
CREATE (mom:Person {node_id: "person_mom_001", label: "Mom", name: "Mother"});
CREATE (dad:Person {node_id: "person_dad_001", label: "Dad", name: "Father"});
CREATE (sibling:Person {node_id: "person_sibling_001", label: "Sibling", name: "Brother"});
CREATE (partner:Person {node_id: "person_partner_001", label: "Partner", name: "Spouse"});
CREATE (home:Location {node_id: "location_home_001", label: "Home", name: "Family Residence"});
CREATE (work:Location {node_id: "location_work_001", label: "Work", name: "Office"});
CREATE (city:Location {node_id: "location_seattle_001", label: "Seattle", name: "Seattle"});
CREATE (employer:Organization {node_id: "org_employer_001", label: "Tech Company", name: "TechCorp Inc."});
MATCH (mom:Person {node_id: "person_mom_001"}), (user:Person {node_id: "person_user_001"}) CREATE (mom)-[:PARENT_OF]->(user);
MATCH (dad:Person {node_id: "person_dad_001"}), (user:Person {node_id: "person_user_001"}) CREATE (dad)-[:PARENT_OF]->(user);
MATCH (user:Person {node_id: "person_user_001"}), (sibling:Person {node_id: "person_sibling_001"}) CREATE (user)-[:SIBLING_OF]->(sibling);
MATCH (user:Person {node_id: "person_user_001"}), (sibling:Person {node_id: "person_sibling_001"}) CREATE (sibling)-[:SIBLING_OF]->(user);
MATCH (mom:Person {node_id: "person_mom_001"}), (dad:Person {node_id: "person_dad_001"}) CREATE (mom)-[:SPOUSE_OF]->(dad);
MATCH (mom:Person {node_id: "person_mom_001"}), (dad:Person {node_id: "person_dad_001"}) CREATE (dad)-[:SPOUSE_OF]->(mom);
MATCH (user:Person {node_id: "person_user_001"}), (partner:Person {node_id: "person_partner_001"}) CREATE (user)-[:SPOUSE_OF]->(partner);
MATCH (user:Person {node_id: "person_user_001"}), (partner:Person {node_id: "person_partner_001"}) CREATE (partner)-[:SPOUSE_OF]->(user);
MATCH (user:Person {node_id: "person_user_001"}), (home:Location {node_id: "location_home_001"}) CREATE (user)-[:LIVES_IN]->(home);
MATCH (partner:Person {node_id: "person_partner_001"}), (home:Location {node_id: "location_home_001"}) CREATE (partner)-[:LIVES_IN]->(home);
MATCH (user:Person {node_id: "person_user_001"}), (city:Location {node_id: "location_seattle_001"}) CREATE (user)-[:LIVES_IN]->(city);
MATCH (user:Person {node_id: "person_user_001"}), (work:Location {node_id: "location_work_001"}) CREATE (user)-[:WORKS_AT]->(work);
MATCH (user:Person {node_id: "person_user_001"}), (employer:Organization {node_id: "org_employer_001"}) CREATE (user)-[:EMPLOYED_BY]->(employer);
MATCH (partner:Person {node_id: "person_partner_001"}), (employer:Organization {node_id: "org_employer_001"}) CREATE (partner)-[:EMPLOYED_BY]->(employer);
