"""
FlatBuffers Serializer - Python Objects â†’ FlatBuffers Binary

Layer: L5 Infrastructure
Component: Serialization (Core)
Priority: P0 (Critical Path)
Status: ðŸš§ STUB - NEEDS_IMPLEMENTATION

Architecture Decision Records:
    - ADR-0011: FlatBuffers for All K1 Serialization
      * Zero-copy binary serialization for 150Ã— performance improvement vs JSON
      * <1ms serialization latency for hot path operations
      * 3Ã— smaller payload size (64KB FlatBuffers vs 192KB JSON)
      * Section: "Decision Matrix: Why FlatBuffers Selected"
      * Performance: Serialize <1ms P95, Deserialize <0.1ms P95 (zero-copy)

    - ADR-0011c: Serialization Performance & Zero-Copy
      * Buffer pooling for allocation reuse (1.4Ã— speedup, 200Ã— fewer allocations)
      * Memory layout optimization (SIMD alignment, string deduplication, padding minimization)
      * Performance targets: SessionState (64KB) <1ms, K0 Event (4KB) <0.5ms, Agent Message (2KB) <0.3ms
      * Section: "Zero-Copy Architecture", "Buffer Pooling", "Performance Benchmarks"

    - ADR-0011d: Schema Evolution & Versioning
      * Forward/backward compatibility with optional fields
      * 3-release deprecation grace period
      * File identifiers for schema validation (4-character codes)
      * Section: "Schema Versioning Strategy", "Backward Compatibility Rules"

Dependencies:
    Internal:
        - k1.l5_infrastructure.serialization.buffer_pool.BufferPool (reusable buffer management)
        - k1.l5_infrastructure.serialization.alignment.align_buffer (SIMD alignment)

    External:
        - flatbuffers (FlatBuffers Python library)
        - typing (type hints)

Connects To:
    Used By:
        - k1.bridge_k0.command_client (K0 command serialization)
        - k1.bridge_k0.state_delta_emitter (SessionState delta serialization)
        - k1.l5_infrastructure.event_bus.event_bus (event serialization)
        - k1.l2_orchestration.orchestrator (agent message serialization)
        - k1.l4_runtime.session_state.manager (SessionState persistence)

Performance Budgets:
    - SessionState (64KB): <1ms P95 serialization
    - K0 Event (4KB): <0.5ms P95 serialization
    - Agent Message (2KB): <0.3ms P95 serialization
    - Batch serialization (100 objects): <80ms P95 (vs 100ms individual)
    - Memory overhead: Buffer + vtables <10% of payload size

Observability:
    - Metrics:
        * k1_flatbuffers_serialize_duration_ms{schema_type, p50, p95, p99} (histogram: serialization latency)
        * k1_flatbuffers_serialize_calls_total{schema_type, status} (counter: success/error)
        * k1_flatbuffers_buffer_size_bytes{schema_type, p50, p95, p99} (histogram: buffer size distribution)
        * k1_flatbuffers_builder_pool_hit_rate{gauge} (gauge: buffer pool hit rate 0.0-1.0)

    - Logs:
        * DEBUG: serialize_started (schema_type, object_size, builder_pool_hit)
        * DEBUG: serialize_completed (schema_type, duration_ms, buffer_size, compression_ratio)
        * WARNING: serialize_slow (schema_type, duration_ms, threshold_ms)
        * ERROR: serialize_failed (schema_type, error, object_repr)

References:
    - ADR-0011: FlatBuffers Serialization Core
    - ADR-0011c: Serialization Performance & Zero-Copy
    - ADR-0011d: Schema Evolution & Versioning
    - Contracts: k1/contracts/flatbuffers/ (130 .fbs schema files)
    - Test: tests/k1/l5_infrastructure/serialization/test_serializer.py
"""

import logging
import threading
import time
from dataclasses import dataclass

# =============================================================================
# SECTION 1: IMPORTS
# =============================================================================
# Standard library imports
from typing import Any, Dict, List, Optional, Type

# Third-party imports
import flatbuffers

# Internal imports
# NOTE: Actual schema imports will be generated by flatc compiler
# Example: from k1.l4_runtime.session_state.model.SessionState import SessionState

# Configure module logger
logger = logging.getLogger(__name__)


# =============================================================================
# SECTION 2: CONSTANTS & CONFIGURATION
# =============================================================================

# Buffer pool size classes (powers of 2)
SIZE_CLASSES = [256, 1024, 4096, 16384, 65536]

# Maximum buffer size to keep in pool (prevent memory bloat)
MAX_POOL_SIZE = 65536  # 64KB

# Maximum total pool memory per thread
MAX_TOTAL_POOL_MEMORY = 262144  # 256KB

# Performance thresholds for warnings
SLOW_SERIALIZATION_THRESHOLD_MS = {
    "session_state": 1.0,  # SessionState (64KB) budget
    "k0_event": 0.5,  # K0 Event (4KB) budget
    "agent_message": 0.3,  # Agent Message (2KB) budget
    "default": 1.0,  # Default threshold
}


# =============================================================================
# SECTION 3: TYPE DEFINITIONS & REGISTRY
# =============================================================================


@dataclass
class SchemaMetadata:
    """
    Metadata for a registered FlatBuffers schema

    Fields:
        schema_name: Unique schema identifier (e.g., "SessionState")
        file_identifier: 4-character file ID for validation (e.g., "SEST")
        version: Schema version (e.g., "1.2")
        root_type: Root table class for schema
        builder_class: FlatBuffers builder class (optional, for custom builders)
        size_hint: Expected serialized size in bytes (for buffer pool optimization)

    ADR-0011d: Schema versioning with file identifiers
    """

    schema_name: str
    file_identifier: str
    version: str
    root_type: Type
    builder_class: Optional[Type] = None
    size_hint: int = 1024


class SchemaRegistry:
    """
    Registry of all 76+ FlatBuffers schemas used in K1

    Schemas organized by layer:
        - Layer 1 (Kernel): AgentState, Proposal, Selection, ExecutionResult, TaskAnnouncement
        - Layer 2 (State): SessionState, Beliefs, Scoreboard, Control, Persona, Multimodal, Meta
        - Layer 4 (Ingress): ASRResult, BargeInEvent, TTSRequest
        - Layer 5 (Infrastructure): MessageEnvelope, CircuitBreakerState
        - K0 Bridge: RecallRequest, MemoryFormationRequest, LearningTickRequest, Receipts

    Purpose:
        1. Centralized schema metadata storage
        2. Version tracking and validation
        3. File identifier mapping for deserialization
        4. Builder class resolution for serialization

    ADR-0011: 76 FlatBuffers schemas across all K1 subsystems
    ADR-0011d: Schema evolution with version tracking
    """

    def __init__(self):
        """
        Initialize schema registry

        TODO(@infrastructure-team): Initialize registry data structures
        Assigned to: Issue #L5-3.1.1
        """
        # Schema registry: {schema_name â†’ SchemaMetadata}
        self._schemas: Dict[str, SchemaMetadata] = {}

        # File identifier reverse index: {file_id â†’ schema_name}
        self._file_id_index: Dict[str, str] = {}

        # Stats
        self._total_registrations = 0

        logger.info("schema_registry_initialized")

    def register_schema(
        self,
        schema_name: str,
        file_identifier: str,
        version: str,
        root_type: Type,
        builder_class: Optional[Type] = None,
        size_hint: int = 1024,
    ) -> None:
        """
        Register a FlatBuffers schema

        Args:
            schema_name: Unique schema identifier (e.g., "SessionState")
            file_identifier: 4-character file ID (e.g., "SEST")
            version: Schema version (e.g., "1.2")
            root_type: Root table class
            builder_class: Optional custom builder class
            size_hint: Expected serialized size for buffer pool

        Raises:
            ValueError: If schema_name or file_identifier already registered
            TypeError: If file_identifier not 4 uppercase ASCII characters

        Usage:
            from k1.l4_runtime.session_state.model.SessionState import SessionState

            registry.register_schema(
                schema_name="SessionState",
                file_identifier="SEST",
                version="1.2",
                root_type=SessionState,
                size_hint=65536,  # 64KB typical
            )

        ADR-0011d: File identifier validation (4-character codes)

        TODO(@infrastructure-team): Implement schema registration
        Assigned to: Issue #L5-3.1.1

        Steps:
            1. Validate file_identifier format (4 uppercase ASCII)
            2. Check for duplicate schema_name or file_identifier
            3. Create SchemaMetadata record
            4. Add to _schemas dict
            5. Add to _file_id_index reverse index
            6. Increment _total_registrations
            7. Log registration event
        """
        # TODO(@infrastructure-team): Validate file_identifier
        if len(file_identifier) != 4:
            raise TypeError(
                f"File identifier must be 4 characters, got {len(file_identifier)}"
            )

        if not file_identifier.isupper() or not file_identifier.isalnum():
            raise TypeError(
                f"File identifier must be 4 uppercase ASCII characters, got: {file_identifier}"
            )

        # TODO(@infrastructure-team): Check for duplicates
        if schema_name in self._schemas:
            raise ValueError(f"Schema {schema_name} already registered")

        if file_identifier in self._file_id_index:
            existing_schema = self._file_id_index[file_identifier]
            raise ValueError(
                f"File identifier {file_identifier} already registered for schema {existing_schema}"
            )

        # TODO(@infrastructure-team): Create metadata record
        metadata = SchemaMetadata(
            schema_name=schema_name,
            file_identifier=file_identifier,
            version=version,
            root_type=root_type,
            builder_class=builder_class,
            size_hint=size_hint,
        )

        # TODO(@infrastructure-team): Add to registries
        self._schemas[schema_name] = metadata
        self._file_id_index[file_identifier] = schema_name
        self._total_registrations += 1

        logger.info(
            "schema_registered",
            schema_name=schema_name,
            file_identifier=file_identifier,
            version=version,
            size_hint=size_hint,
        )

    def get_schema(self, schema_name: str) -> SchemaMetadata:
        """
        Get schema metadata by name

        Args:
            schema_name: Schema identifier

        Returns:
            SchemaMetadata for schema

        Raises:
            KeyError: If schema not registered

        TODO(@infrastructure-team): Implement schema lookup
        Assigned to: Issue #L5-3.1.1
        """
        if schema_name not in self._schemas:
            raise KeyError(
                f"Schema {schema_name} not registered. Available: {list(self._schemas.keys())}"
            )

        return self._schemas[schema_name]

    def get_schema_by_file_id(self, file_identifier: str) -> SchemaMetadata:
        """
        Get schema metadata by file identifier

        Args:
            file_identifier: 4-character file ID (e.g., "SEST")

        Returns:
            SchemaMetadata for schema

        Raises:
            KeyError: If file_identifier not registered

        Used for deserialization (validate file ID from buffer header)

        TODO(@infrastructure-team): Implement reverse lookup
        Assigned to: Issue #L5-3.1.1
        """
        if file_identifier not in self._file_id_index:
            raise KeyError(
                f"File identifier {file_identifier} not registered. Available: {list(self._file_id_index.keys())}"
            )

        schema_name = self._file_id_index[file_identifier]
        return self._schemas[schema_name]

    def list_schemas(self) -> List[str]:
        """
        List all registered schema names

        Returns:
            List of schema names

        TODO(@infrastructure-team): Implement schema listing
        Assigned to: Issue #L5-3.1.1
        """
        return sorted(self._schemas.keys())

    def get_stats(self) -> Dict[str, Any]:
        """
        Get schema registry statistics

        Returns:
            Dict with:
                - total_schemas: Count of registered schemas
                - total_registrations: Lifetime registration count
                - schemas_by_layer: Breakdown by layer

        TODO(@infrastructure-team): Implement stats collection
        Assigned to: Issue #L5-3.1.1
        """
        return {
            "total_schemas": len(self._schemas),
            "total_registrations": self._total_registrations,
            "file_identifiers": list(self._file_id_index.keys()),
        }


# =============================================================================
# SECTION 4: BUFFER POOL (THREAD-LOCAL)
# =============================================================================

# Thread-local buffer pools
_thread_local = threading.local()


def get_builder(size_hint: int = 256) -> flatbuffers.Builder:
    """
    Get a FlatBuffers builder from thread-local pool

    Args:
        size_hint: Expected buffer size in bytes (for size class selection)

    Returns:
        flatbuffers.Builder instance (reused from pool or newly created)

    Performance:
        - Buffer pooling: 1.4Ã— speedup vs no pooling
        - Allocation reduction: 200Ã— fewer allocations
        - GC pause reduction: 7.5Ã— fewer pauses

    Size Classes:
        - 256B: Small messages (agent metadata, tool calls)
        - 1KB: Medium messages (task announcements, proposals)
        - 4KB: Events (K0 events, protocol violations)
        - 16KB: Large messages (plan sketches, agent state)
        - 64KB: SessionState deltas

    Eviction Policy:
        - Buffers >64KB not pooled (created temporarily)
        - Total pool memory capped at 256KB per thread
        - LRU eviction when exceeding memory limit

    ADR-0011c: Buffer pooling for allocation reuse (Section "Buffer Pooling")

    TODO(@infrastructure-team): Implement buffer pool management
    Assigned to: Issue #L5-3.1.1

    Steps:
        1. Ensure thread-local storage initialized
        2. Find appropriate size class (powers of 2)
        3. Evict if size class >MAX_POOL_SIZE (don't pool large buffers)
        4. Evict if total memory >MAX_TOTAL_POOL_MEMORY (LRU policy)
        5. Get or create builder for size class
        6. Reset builder (clear for reuse)
        7. Return builder
    """
    # TODO(@infrastructure-team): Initialize thread-local storage
    if not hasattr(_thread_local, "pools"):
        _thread_local.pools: Dict[int, flatbuffers.Builder] = {}
        _thread_local.total_memory = 0
        _thread_local.pool_hits = 0
        _thread_local.pool_misses = 0

    # TODO(@infrastructure-team): Find size class
    size_class = 256
    for sz in SIZE_CLASSES:
        if sz >= size_hint:
            size_class = sz
            break

    # TODO(@infrastructure-team): Evict if size class too large
    if size_class > MAX_POOL_SIZE:
        _thread_local.pool_misses += 1
        return flatbuffers.Builder(size_class)

    # TODO(@infrastructure-team): Evict if total memory exceeded
    if _thread_local.total_memory + size_class > MAX_TOTAL_POOL_MEMORY:
        # Evict smallest size class first (least likely to be reused)
        if _thread_local.pools:
            evicted = min(_thread_local.pools.keys())
            del _thread_local.pools[evicted]
            _thread_local.total_memory -= evicted
            logger.debug("buffer_pool_evicted", evicted_size_class=evicted)

    # TODO(@infrastructure-team): Get or create builder
    if size_class not in _thread_local.pools:
        _thread_local.pools[size_class] = flatbuffers.Builder(size_class)
        _thread_local.total_memory += size_class
        _thread_local.pool_misses += 1
    else:
        _thread_local.pool_hits += 1

    builder = _thread_local.pools[size_class]
    builder.Reset()  # Clear for reuse
    return builder


def get_pool_stats() -> Dict[str, Any]:
    """
    Get buffer pool statistics for current thread

    Returns:
        Dict with:
            - total_memory: Total memory allocated in pool
            - size_classes: Active size classes
            - hit_rate: Buffer pool hit rate (0.0-1.0)
            - pool_hits: Total pool hits
            - pool_misses: Total pool misses

    TODO(@infrastructure-team): Implement pool stats
    Assigned to: Issue #L5-3.1.1
    """
    if not hasattr(_thread_local, "pools"):
        return {
            "total_memory": 0,
            "size_classes": [],
            "hit_rate": 0.0,
            "pool_hits": 0,
            "pool_misses": 0,
        }

    total_requests = _thread_local.pool_hits + _thread_local.pool_misses
    hit_rate = _thread_local.pool_hits / total_requests if total_requests > 0 else 0.0

    return {
        "total_memory": _thread_local.total_memory,
        "size_classes": sorted(_thread_local.pools.keys()),
        "hit_rate": hit_rate,
        "pool_hits": _thread_local.pool_hits,
        "pool_misses": _thread_local.pool_misses,
    }


# =============================================================================
# SECTION 5: CORE SERIALIZER CLASS
# =============================================================================


class Serializer:
    """
    FlatBuffers Serializer: Python objects â†’ FlatBuffers binary

    Responsibilities:
        1. Convert Python objects to FlatBuffers builder
        2. Support 76+ schema types across all K1 layers
        3. Handle nested objects and repeated fields
        4. Maintain thread-safe builder pool
        5. Implement deterministic serialization (for testing)
        6. Track performance metrics

    Supported Schema Types (76+ schemas):
        - Layer 1 (Kernel): AgentState, Proposal, Selection, ExecutionResult, TaskAnnouncement, PlanSketch, ProtocolState, FeedbackSignal
        - Layer 2 (State): SessionState, Beliefs, Scoreboard, Control, Persona, Multimodal, Meta, StateDelta
        - Layer 4 (Ingress): ASRResult, BargeInEvent, TTSRequest, UserInput
        - Layer 5 (Infrastructure): MessageEnvelope, CircuitBreakerState, Event
        - K0 Bridge: RecallRequest, MemoryFormationRequest, LearningTickRequest, K0Receipt

    Performance Targets (from ADR-0011c):
        - SessionState (64KB): <1ms P95
        - K0 Event (4KB): <0.5ms P95
        - Agent Message (2KB): <0.3ms P95
        - Batch (100 objects): <80ms P95

    ADR-0011: FlatBuffers core serialization design
    ADR-0011c: Performance optimization (buffer pooling, zero-copy)
    ADR-0011d: Schema evolution (versioning, file identifiers)
    """

    def __init__(self, schema_registry: SchemaRegistry):
        """
        Initialize serializer with schema registry

        Args:
            schema_registry: Registry of all FlatBuffers schemas

        TODO(@infrastructure-team): Initialize serializer
        Assigned to: Issue #L5-3.1.1
        """
        self.schema_registry = schema_registry

        # Stats
        self._total_serializations = 0
        self._total_bytes_written = 0

        logger.info(
            "serializer_initialized", total_schemas=len(schema_registry.list_schemas())
        )

    def serialize(
        self,
        obj: Any,
        schema_name: str,
        deterministic: bool = False,
    ) -> bytes:
        """
        Serialize Python object to FlatBuffers binary

        Args:
            obj: Object to serialize (dict, dataclass, or schema-specific type)
            schema_name: Schema type name (e.g., "SessionState")
            deterministic: If True, ensure reproducible output (for testing)

        Returns:
            Binary FlatBuffers buffer

        Raises:
            ValueError: If object doesn't match schema
            KeyError: If schema_name not registered
            TypeError: If object type incompatible with schema

        Performance:
            - SessionState (64KB): <1ms P95
            - K0 Event (4KB): <0.5ms P95
            - Agent Message (2KB): <0.3ms P95

        Usage:
            # Serialize SessionState
            session_state_dict = {
                'session_id': 'sess_xyz',
                'beliefs': {...},
                'scoreboard': {...},
            }

            buffer = serializer.serialize(
                obj=session_state_dict,
                schema_name='SessionState',
            )

            # Send to K0 or store in WAL
            k0_bridge.send(buffer)

        ADR-0011: Core serialization logic
        ADR-0011c: Performance targets and buffer pooling

        TODO(@infrastructure-team): Implement serialization
        Assigned to: Issue #L5-3.1.1

        Steps:
            1. Get schema metadata from registry
            2. Get builder from pool (size hint from metadata)
            3. Recursively build nested structures
            4. Handle repeated fields (vectors)
            5. Call builder.Finish() with file_identifier
            6. Extract bytes from builder
            7. Record metrics (duration_ms, buffer_size)
            8. Return bytes
        """
        start_time = time.perf_counter()

        # TODO(@infrastructure-team): Get schema metadata
        metadata = self.schema_registry.get_schema(schema_name)

        # TODO(@infrastructure-team): Get builder from pool
        builder = get_builder(metadata.size_hint)

        # TODO(@infrastructure-team): Build FlatBuffers structure
        # This is schema-specific and requires custom serialization logic
        # For now, raise NotImplementedError
        raise NotImplementedError(
            f"Serialization for schema '{schema_name}' not yet implemented. "
            f"Schema-specific serialization logic required (see ADR-0011b for codegen approach)."
        )

        # TODO(@infrastructure-team): Finish buffer
        # builder.Finish(root_table, file_identifier=metadata.file_identifier.encode())
        # buf = bytes(builder.Output())

        # TODO(@infrastructure-team): Record metrics
        # end_time = time.perf_counter()
        # duration_ms = (end_time - start_time) * 1000
        # self._total_serializations += 1
        # self._total_bytes_written += len(buf)

        # Check performance budget
        # threshold = SLOW_SERIALIZATION_THRESHOLD_MS.get(schema_name.lower(), SLOW_SERIALIZATION_THRESHOLD_MS['default'])
        # if duration_ms > threshold:
        #     logger.warning(
        #         "serialize_slow",
        #         schema_name=schema_name,
        #         duration_ms=duration_ms,
        #         threshold_ms=threshold,
        #         buffer_size=len(buf),
        #     )

        # return buf

    def serialize_batch(
        self,
        objects: List[Any],
        schema_name: str,
    ) -> List[bytes]:
        """
        Serialize multiple objects efficiently

        Args:
            objects: List of objects to serialize
            schema_name: Schema type (all objects must have same schema)

        Returns:
            List of binary FlatBuffers buffers

        Performance:
            - Batch reuses builder (faster than individual serializations)
            - 100 objects: <80ms P95 (vs 100ms individual)

        Optimization:
            - Single builder reused across all objects
            - String deduplication (reuse common strings)
            - Vtable deduplication (automatic in FlatBuffers)

        ADR-0011c: Batch serialization optimization (Section "Memory Layout Optimization")

        TODO(@infrastructure-team): Implement batch serialization
        Assigned to: Issue #L5-3.1.1

        Steps:
            1. Get schema metadata
            2. Get single builder (reuse for all objects)
            3. For each object:
               a. Reset builder (but keep in pool)
               b. Serialize object
               c. Extract bytes
               d. Append to results list
            4. Return results
        """
        # TODO(@infrastructure-team): Implement batch serialization
        results = []
        metadata = self.schema_registry.get_schema(schema_name)

        for obj in objects:
            # Reuse same builder across objects (reset between uses)
            buf = self.serialize(obj, schema_name)
            results.append(buf)

        return results

    def get_stats(self) -> Dict[str, Any]:
        """
        Get serializer statistics

        Returns:
            Dict with:
                - total_serializations: Lifetime serialization count
                - total_bytes_written: Total bytes serialized
                - buffer_pool_stats: Buffer pool hit rate and memory

        TODO(@infrastructure-team): Implement stats collection
        Assigned to: Issue #L5-3.1.1
        """
        return {
            "total_serializations": self._total_serializations,
            "total_bytes_written": self._total_bytes_written,
            "buffer_pool_stats": get_pool_stats(),
        }


# =============================================================================
# SECTION 6: MODULE EXPORTS
# =============================================================================

__all__ = [
    "Serializer",
    "SchemaRegistry",
    "SchemaMetadata",
    "get_builder",
    "get_pool_stats",
]


# =============================================================================
# OBSERVABILITY INTEGRATION
# =============================================================================
# Metrics to export:
#   - k1_flatbuffers_serialize_duration_ms{schema_type} (histogram: P50/P95/P99 serialization latency)
#   - k1_flatbuffers_serialize_calls_total{schema_type, status} (counter: success/error)
#   - k1_flatbuffers_buffer_size_bytes{schema_type} (histogram: P50/P95/P99 buffer size distribution)
#   - k1_flatbuffers_builder_pool_hit_rate (gauge: buffer pool hit rate 0.0-1.0)
#   - k1_flatbuffers_builder_pool_memory_bytes (gauge: total memory allocated in pool)
#
# Logs to emit:
#   - Level: DEBUG (normal), WARNING (slow serialization), ERROR (failures)
#   - Fields: component="serialization.serializer", schema_name, duration_ms, buffer_size, error
#   - Events: serialize_started, serialize_completed, serialize_slow, serialize_failed
#
# =============================================================================

# =============================================================================
# TESTING REQUIREMENTS (WARD Framework)
# =============================================================================
# Integration tests required:
#   - tests/k1/l5_infrastructure/serialization/test_serializer.py
#   - Test: schema registration (valid/invalid file identifiers)
#   - Test: buffer pooling (hit rate, memory limits, eviction)
#   - Test: performance budgets (SessionState <1ms, K0 Event <0.5ms, Agent Message <0.3ms)
#   - Test: batch serialization (100 objects <80ms, string deduplication)
#   - Test: deterministic serialization (same input â†’ same output)
#   - Test: error handling (invalid schema, type mismatch, missing fields)
#
# Benchmark tests required:
#   - ward-benchmark for performance validation
#   - Measure serialization latency (P50/P95/P99)
#   - Measure buffer pool hit rate (target >80%)
#   - Compare with JSON baseline (expected 48Ã— faster)
#
# No simulation code allowed:
#   - Use real FlatBuffers schemas from k1/contracts/flatbuffers/
#   - Test with actual generated Python bindings
#   - Integration tests > unit tests
#
# =============================================================================

