# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/observability.payload.v1.yaml
# generated by datamodel-codegen:
#   filename:  observability.payload.v1.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Kind(Enum):
    """
    Inner ObservabilityPayload.kind discriminator. Selects the K0 routing branch in /k0/obs.emit.
    """

    metrics = 'metrics'
    logs = 'logs'


class Level(Enum):
    DEBUG = 'DEBUG'
    INFO = 'INFO'
    WARNING = 'WARNING'
    ERROR = 'ERROR'
    CRITICAL = 'CRITICAL'


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    level: Level
    message: constr(min_length=1)
    timestamp: Optional[AwareDatetime] = None
    logger: Optional[str] = None
    trace_id: Optional[str] = None


class ObservabilityPayloadV1(BaseModel):
    """
    K1 -> K0 observability forwarding payload. Carries either a Prometheus-text metrics snapshot or a list of structured log entries. K0 ports.observe routes by the inner kind discriminator.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    """
    Inner ObservabilityPayload.kind discriminator. Selects the K0 routing branch in /k0/obs.emit.
    """
    snapshot: Optional[str] = None
    """
    Prometheus exposition-format text. Required when kind=metrics.
    """
    entries: Optional[List[Entry]] = None
    """
    Structured log entries. Required when kind=logs.
    """
    envelope_id: Optional[str] = None
    """
    Optional idempotency key for dedupe_by_envelope_id.
    """
    tenant_id: Optional[str] = None
    space_id: Optional[str] = None
    trace_id: Optional[str] = None
