# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/p03.complete.v1.yaml
# generated by datamodel-codegen:
#   filename:  p03.complete.v1.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, conint, constr


class P03CompleteV1(BaseModel):
    """
    K0→K1 SSE event payload: P03 consolidation cycle completion. Mirrors the K0-internal ``p03.consolidation.complete.v1`` outbox topic on the cross-kernel surface; lets K1 react (e.g. invalidate concierge caches, refresh KG-derived facts) without polling.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(min_length=1)
    """
    Per-event ULID. Used as the SSE Last-Event-ID cursor token.
    """
    cycle_id: constr(min_length=1)
    """
    Consolidation cycle identifier.
    """
    completed_at_utc_ms: conint(ge=0)
    """
    UTC epoch milliseconds when the cycle completed.
    """
    duration_ms: Optional[conint(ge=0)] = None
    """
    Wall-clock duration of the consolidation cycle.
    """
    atoms_consolidated: conint(ge=0) = 0
    """
    Number of atoms folded into long-term memory this cycle.
    """
    patterns_discovered: conint(ge=0) = 0
    """
    Number of new patterns discovered.
    """
    gaps_emitted: conint(ge=0) = 0
    """
    Number of p03.gap.detected.v1 events emitted during this cycle.
    """
    tenant_id: Optional[str] = None
    """
    Tenant identifier.
    """
    space_id: Optional[str] = None
    """
    Memory-space identifier.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace identifier.
    """
