# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/recall.response.v1.yaml
# generated by datamodel-codegen:
#   filename:  recall.response.v1.json

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, confloat, conint, constr


class RecallHit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    atom_id: constr(min_length=1)
    """
    Stable identifier of the recalled atom.
    """
    content: Dict[str, Any]
    """
    Atom content (shape depends on the selector type).
    """
    score: confloat(ge=0.0, le=1.0)
    """
    Relevance/similarity score (0.0–1.0).
    """
    source: constr(min_length=1)
    """
    K0 storage layer / selector that produced this hit (e.g. wal, pgvector, kg).
    """
    selector_type: Optional[str] = None
    """
    Optional selector kind that produced this hit.
    """
    cursor: Optional[str] = None
    """
    Optional continuation cursor for fetching more from this point.
    """


class RecallResponseV1(BaseModel):
    """
    Response body for recall.request.v1 (K0→K1). Carries the recalled hits plus aggregate latency/truncation flags. Returned synchronously on the same HTTP request — never published independently.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    hits: List[RecallHit]
    """
    Recalled atoms, ordered by relevance/recency depending on selector mix.
    """
    total: conint(ge=0)
    """
    Total matching atoms across selectors (may exceed len(hits) when truncated).
    """
    latency_ms: conint(ge=0)
    """
    K0-side wall-clock latency for the aggregate query.
    """
    truncated: bool
    """
    True when fail_fast or max_results truncated the bundle.
    """
    trace_id: Optional[str] = None
    """
    Echoed cognitive trace identifier.
    """
