# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/curiosity.intent.v1.yaml
# generated by datamodel-codegen:
#   filename:  curiosity.intent.v1.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, conint, constr


class CuriosityIntentV1(BaseModel):
    """
    K0→K1 SSE event payload: a P06 Active-Learning curiosity question pushed to the K1 concierge so it can decide whether to surface it to the user. Carries the originating gap_id (so the answer can be back-correlated to the gap that prompted it), a natural-language question, and the remaining curiosity budget for the active session (the concierge throttles when budget is low).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(min_length=1)
    """
    Per-event ULID. Used as the SSE Last-Event-ID cursor token (D13).
    """
    gap_id: constr(min_length=1)
    """
    Knowledge gap identifier; correlates the answer back to the originating P03 gap.
    """
    question_text: constr(min_length=1)
    """
    Natural-language question to surface to the user.
    """
    budget_remaining: conint(ge=0) = 0
    """
    Remaining curiosity budget for the active session.
    """
    tenant_id: Optional[str] = None
    """
    Tenant identifier; defaults to space owner if absent.
    """
    space_id: Optional[str] = None
    """
    Memory-space identifier the gap was detected in.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace identifier.
    """
