# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/feedback.envelope.v1.yaml
# generated by datamodel-codegen:
#   filename:  feedback.envelope.v1.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class SignalClass(Enum):
    """
    Top-level classification.
    """

    OUTCOME = 'OUTCOME'
    CORRECTION = 'CORRECTION'
    IMPLICIT = 'IMPLICIT'
    EXPLICIT = 'EXPLICIT'
    VALIDATION = 'VALIDATION'


class Source(Enum):
    """
    Originating actor classification.
    """

    K1 = 'K1'
    USER = 'USER'
    SYSTEM = 'SYSTEM'
    AGENT = 'AGENT'


class FeedbackCorrelation(BaseModel):
    """
    Links feedback to originating K0/K1 operations and target entities.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    session_id: Optional[str] = None
    message_id: Optional[str] = None
    query_id: Optional[str] = None
    receipt_id: Optional[str] = None
    recall_id: Optional[str] = None
    response_id: Optional[str] = None
    event_ids: Optional[List[constr(min_length=1)]] = None
    """
    st_hipp_events.event_id values touched by the originating turn.
    """
    wal_positions: Optional[List[conint(ge=0)]] = None
    wal_position: Optional[conint(ge=0)] = None
    """
    Singular form (legacy); merged into wal_positions on the K0 side.
    """
    target_entity_type: Optional[str] = None
    """
    Kind of entity the feedback targets, e.g. event.
    """
    target_entity_id: Optional[str] = None
    """
    Entity id the feedback targets, e.g. st_hipp_events.event_id.
    """


class FeedbackEnvelopeV1(BaseModel):
    """
    Pipeline-agnostic feedback envelope. K1 detectors emit; K0 ports.observe ingests into st_feedback_signals. Wire shape mirrors k0.feedback.envelope.FeedbackEnvelope (Pydantic) with extra=forbid semantics; the K0 side re-validates to apply per-pipeline payload schemas via FeedbackSchemaRegistry.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    feedback_id: Optional[str] = None
    """
    UUID stringified; if absent the K0 side mints one. Idempotency key for dedupe_by_envelope_id.
    """
    feedback_version: str = '1.0'
    """
    Envelope schema version; forward-compat marker.
    """
    pipeline_id: constr(pattern=r'^P\d{2,3}$')
    """
    Target K0 pipeline (e.g. P02, P08, P03).
    """
    signal_class: SignalClass
    """
    Top-level classification.
    """
    signal_subtype: Optional[str] = None
    """
    Optional finer-grained subtype, e.g. user_explicit_correction.
    """
    tenant_id: Optional[str] = None
    """
    Multi-tenant routing; required by K0 schema-registry validation.
    """
    space_id: Optional[str] = None
    """
    Tenant space id; required by K0 schema-registry validation.
    """
    source: Optional[Source] = None
    """
    Originating actor classification.
    """
    source_component: Optional[str] = None
    """
    Component name (e.g. concierge.correction_detector).
    """
    session_id: Optional[str] = None
    """
    Conversation session correlation id.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace id.
    """
    correlation: Optional[FeedbackCorrelation] = None
    provenance: Optional[Dict[str, Any]] = None
    """
    Audit trail; recall_context_hash, source_message_id, feedback_timestamp, etc.
    """
    timestamp: Optional[AwareDatetime] = None
    """
    Emission timestamp (UTC ISO-8601).
    """
    event_timestamp: Optional[AwareDatetime] = None
    """
    Original event time (UTC ISO-8601), if different from emission.
    """
    priority: confloat(ge=0.0, le=1.0) = 0.5
    """
    Scheduling weight; higher = more urgent.
    """
    payload: Dict[str, Any]
    """
    Pipeline-specific payload validated by K0 FeedbackSchemaRegistry against pipeline_id.
    """
    metadata: Optional[Dict[str, Any]] = None
    """
    Optional free-form metadata.
    """
