# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/k0.learning.advisory.v1.yaml
# generated by datamodel-codegen:
#   filename:  k0.learning.advisory.v1.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, constr


class SignalClass(Enum):
    """
    Class of learning signal.
    """

    drift = 'drift'
    regression = 'regression'
    improvement = 'improvement'
    calibration = 'calibration'
    saturation = 'saturation'


class K0LearningAdvisoryV1(BaseModel):
    """
    K0→K1 SSE event payload: P21 learning-loop advisory describing drift, regression, or improvement of a K0 pipeline algorithm. Consumed by the K1 planner/orchestrator to retune local strategies. Free-form ``details`` payload because the advisory shape varies per signal class; the producer guarantees ``signal_class`` selects the schema sub-shape.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(min_length=1)
    """
    Per-event ULID. Used as the SSE Last-Event-ID cursor token.
    """
    advisory_id: constr(min_length=1)
    """
    Stable advisory identifier.
    """
    pipeline_id: constr(min_length=1)
    """
    Pipeline that generated the advisory (e.g. P02, P08).
    """
    signal_class: SignalClass
    """
    Class of learning signal.
    """
    details: Optional[Dict[str, Any]] = None
    """
    Advisory-specific detail payload; the producer-side schema is governed by ``signal_class``.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace identifier.
    """
