# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/k0.proactive.signal.v1.yaml
# generated by datamodel-codegen:
#   filename:  k0.proactive.signal.v1.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, constr


class TriggerType(Enum):
    """
    Kind of proactive trigger.
    """

    reminder = 'reminder'
    suggestion = 'suggestion'
    nudge = 'nudge'
    alert = 'alert'
    followup = 'followup'


class Priority(Enum):
    """
    Signal priority; concierge drops LOW under attentional load.
    """

    LOW = 'LOW'
    NORMAL = 'NORMAL'
    HIGH = 'HIGH'
    CRITICAL = 'CRITICAL'


class K0ProactiveSignalV1(BaseModel):
    """
    K0→K1 SSE event payload: P05 proactive-intelligence trigger telling the K1 concierge to consider unprompted engagement (a reminder, suggestion, or nudge). The concierge filters by priority and current attentional load before surfacing.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(min_length=1)
    """
    Per-event ULID. Used as the SSE Last-Event-ID cursor token.
    """
    trigger_type: TriggerType
    """
    Kind of proactive trigger.
    """
    priority: Priority
    """
    Signal priority; concierge drops LOW under attentional load.
    """
    context: Optional[Dict[str, Any]] = None
    """
    Free-form contextual data accompanying the signal.
    """
    tenant_id: Optional[str] = None
    """
    Tenant identifier.
    """
    space_id: Optional[str] = None
    """
    Memory-space identifier.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace identifier.
    """
