# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/memory.write.v1.yaml
# generated by datamodel-codegen:
#   filename:  memory_atom.v2.schema.json

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class SchemaVersion(Enum):
    """
    Schema version. '2.0' for MW v2, '2.1' for multi-temporal links, '2.2' for K1 correction signals.
    """

    field_2_0 = '2.0'
    field_2_1 = '2.1'
    field_2_2 = '2.2'


class LocationType(Enum):
    """
    Location category. Stripped in AMBER/RED privacy band.
    """

    home = 'home'
    restaurant = 'restaurant'
    hospital = 'hospital'
    school = 'school'
    office = 'office'
    gym = 'gym'
    store = 'store'
    park = 'park'
    church = 'church'
    airport = 'airport'
    hotel = 'hotel'
    other = 'other'


class TransitionMode(Enum):
    """
    Mode of movement from transition_from_place to current location. GAP-002 Epic 4.3.
    """

    NoneType_None = None
    walked = 'walked'
    drove = 'drove'
    flew = 'flew'
    took_bus = 'took_bus'
    took_train = 'took_train'
    biked = 'biked'
    other = 'other'


class ActivityType(Enum):
    """
    Activity classification. 20-value enum merged from K1 12-type + legacy 12-type.
    """

    MEAL = 'MEAL'
    TASK = 'TASK'
    TRAVEL = 'TRAVEL'
    HEALTH = 'HEALTH'
    SOCIAL = 'SOCIAL'
    WORK = 'WORK'
    EDUCATION = 'EDUCATION'
    EXERCISE = 'EXERCISE'
    SHOPPING = 'SHOPPING'
    ENTERTAINMENT = 'ENTERTAINMENT'
    CELEBRATION = 'CELEBRATION'
    APPOINTMENT = 'APPOINTMENT'
    DIARY = 'DIARY'
    FINANCE = 'FINANCE'
    RELATIONSHIP = 'RELATIONSHIP'
    PLANNING = 'PLANNING'
    CONCERN = 'CONCERN'
    GRATITUDE = 'GRATITUDE'
    META = 'META'
    MEMORY = 'MEMORY'


class SentimentLabel(Enum):
    """
    Sentiment classification from affective_now.
    """

    very_negative = 'very_negative'
    negative = 'negative'
    neutral = 'neutral'
    positive = 'positive'
    very_positive = 'very_positive'


class SocialContext(Enum):
    """
    Social context derived from participant_relationships.
    """

    solo = 'solo'
    friends = 'friends'
    colleagues = 'colleagues'
    nuclear_family = 'nuclear_family'
    extended_family = 'extended_family'
    community = 'community'


class SocialIntimacy(Enum):
    """
    Social intimacy level. family=HIGH, friends=MEDIUM, unknown=LOW.
    """

    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class IntentType(Enum):
    """
    Primary intent from control.intents[0] (UltraBERT primary).
    """

    log_memory = 'log_memory'
    query_memory = 'query_memory'
    set_reminder = 'set_reminder'
    express_feeling = 'express_feeling'
    seek_advice = 'seek_advice'
    share_news = 'share_news'
    reflect = 'reflect'
    other = 'other'


class SourceType(Enum):
    """
    Memory provenance. MW cross-references history_active turns vs extraction origin.
    """

    user_stated = 'user_stated'
    user_implied = 'user_implied'
    device_observed = 'device_observed'
    system_inferred = 'system_inferred'


class Novelty(Enum):
    """
    Novelty classification. MW compares against beliefs + scoreboard.
    """

    ROUTINE = 'ROUTINE'
    EXPECTED = 'EXPECTED'
    NOVEL = 'NOVEL'
    SURPRISING = 'SURPRISING'


class ElaborationDepth(Enum):
    """
    How deeply the topic was discussed. MW counts turns on topic from history.
    """

    MENTION = 'MENTION'
    DISCUSSED = 'DISCUSSED'
    ELABORATED = 'ELABORATED'
    DEEPLY_PROCESSED = 'DEEPLY_PROCESSED'


class IdentityDomain(Enum):
    parent = 'parent'
    child = 'child'
    spouse = 'spouse'
    professional = 'professional'
    health_self = 'health_self'
    financial_self = 'financial_self'
    social_self = 'social_self'
    academic_self = 'academic_self'
    spiritual_self = 'spiritual_self'


class TemporalOrientation(Enum):
    """
    Temporal orientation. MW compares resolved_epoch_ms vs now.
    """

    PAST = 'PAST'
    ONGOING = 'ONGOING'
    FUTURE_COMMITMENT = 'FUTURE_COMMITMENT'


class CorrectionSource(Enum):
    """
    How the correction was detected: user_explicit (direct statement), user_implicit (inferred from context shift), context_change (environmental change). R2 Epic 7.2.
    """

    NoneType_None = None
    user_explicit = 'user_explicit'
    user_implicit = 'user_implicit'
    context_change = 'context_change'


class Affect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    valence: confloat(ge=-1.0, le=1.0)
    """
    Emotional valence (-1 negative to +1 positive).
    """
    arousal: confloat(ge=0.0, le=1.0)
    """
    Emotional arousal (0 calm to 1 excited).
    """
    dominance: confloat(ge=0.0, le=1.0)
    """
    Emotional dominance (0 submissive to 1 dominant).
    """


class Type(Enum):
    """
    Relationship type between participant and target.
    """

    PARENT_OF = 'PARENT_OF'
    CHILD_OF = 'CHILD_OF'
    SPOUSE_OF = 'SPOUSE_OF'
    SIBLING_OF = 'SIBLING_OF'
    FRIEND_OF = 'FRIEND_OF'
    COLLEAGUE_OF = 'COLLEAGUE_OF'
    CARETAKER_OF = 'CARETAKER_OF'
    OTHER = 'OTHER'


class ParticipantRelationship(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    """
    Relationship type between participant and target.
    """
    target: constr(pattern=r'^person_[a-z0-9_]+$')
    """
    Target person_id for the relationship.
    """
    confidence: confloat(ge=0.0, le=1.0)
    """
    Confidence score for this relationship.
    """


class ArcPosition(Enum):
    """
    Story arc position from narrative_active.arc.position.
    """

    EXPOSITION = 'EXPOSITION'
    RISING_ACTION = 'RISING_ACTION'
    CLIMAX = 'CLIMAX'
    RESOLUTION = 'RESOLUTION'


class Narrative(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    thread_id: str
    """
    UUID from narrative_active.primary_thread.id.
    """
    arc_position: ArcPosition
    """
    Story arc position from narrative_active.arc.position.
    """
    is_goal_event: bool
    """
    True if extraction matches thread.goal.
    """


class Temporal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mentioned_time: str
    """
    Raw time text like 'yesterday evening'.
    """
    resolved_epoch_ms: int
    """
    Unix milliseconds (resolved absolute time).
    """
    is_backdated: bool
    """
    True if mentioned_time != now (refers to past/future).
    """


class LinkType(Enum):
    """
    Temporal link classification.
    """

    RETROSPECTIVE = 'RETROSPECTIVE'
    PROSPECTIVE = 'PROSPECTIVE'
    CONCURRENT = 'CONCURRENT'
    HABITUAL = 'HABITUAL'
    CONTEXTUAL = 'CONTEXTUAL'
    CONDITIONAL = 'CONDITIONAL'


class TemporalLink(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mentioned_time: constr(min_length=1)
    """
    Raw temporal text from conversation (e.g. 'yesterday evening').
    """
    resolved_epoch_ms: int = 0
    """
    Best-guess absolute time (Unix ms).
    """
    uncertainty_window_ms: conint(ge=0) = 0
    """
    Precision window in ms (60000 for '7:15pm', 86400000 for 'yesterday').
    """
    link_type: LinkType = 'CONCURRENT'
    """
    Temporal link classification.
    """
    confidence: confloat(ge=0.0, le=1.0) = 1.0
    """
    LLM resolution confidence.
    """


class MemoryWriteV1(BaseModel):
    """
    Authoritative JSON Schema for MW v2.2 memory atom. Additive over v2.1: K1 correction signal fields (correction_signal, contradiction_signal, supersedes_concept, correction_source, session_context_id) for EVOLVE/CONTRADICT delegation. All v2.1 atoms validate against v2.2 (new fields have defaults). R2 Epic 7.2.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    """
    Schema version. '2.0' for MW v2, '2.1' for multi-temporal links, '2.2' for K1 correction signals.
    """
    operation: Literal['UPSERT']
    """
    Operation type constant. Always 'UPSERT' for MW v2.
    """
    text: constr(min_length=1)
    """
    Episodic memory text. 1-50 words, past/present tense, self-contained. MW-04 enforced.
    """
    participants: Optional[List[constr(pattern=r'^person_[a-z0-9_]+$')]] = None
    """
    Person IDs of participants. Resolved by PersonResolver. Format: person_*.
    """
    participant_relationships: Optional[Dict[str, ParticipantRelationship]] = None
    """
    Map of person_id to relationship descriptor with type, target, and confidence.
    """
    location_name: Optional[str] = None
    """
    Place name. Stripped in RED privacy band.
    """
    location_type: Optional[LocationType] = None
    """
    Location category. Stripped in AMBER/RED privacy band.
    """
    place_id: Optional[constr(pattern=r'^place_[a-z0-9_]+$')] = None
    """
    Stable place identity from PlaceResolver. Pattern: place_<slug>. GAP-002 Epic 3.1.
    """
    location_hierarchy: List[str] = Field(default=[], max_length=5)
    """
    Spatial hierarchy from most specific to most general. Example: ['kitchen', 'home', 'Capitol Hill', 'Seattle']. GAP-002 Epic 4.2.
    """
    transition_from_place: Optional[str] = None
    """
    Origin place for spatial transition. Raw place name or resolved place_id. GAP-002 Epic 4.3.
    """
    transition_mode: Optional[TransitionMode] = None
    """
    Mode of movement from transition_from_place to current location. GAP-002 Epic 4.3.
    """
    activity_type: Optional[ActivityType] = None
    """
    Activity classification. 20-value enum merged from K1 12-type + legacy 12-type.
    """
    topics: List[str] = Field(..., max_length=3, min_length=1)
    """
    Topic tags. 1-3 tags per atom.
    """
    categories: Optional[List[str]] = None
    """
    Activity categories.
    """
    sentiment_label: SentimentLabel
    """
    Sentiment classification from affective_now.
    """
    emotion_tags: Optional[List[str]] = None
    """
    Emotion labels from 44-class emotion set via affective_now.current_emotion.
    """
    affect: Affect
    """
    Valence-Arousal-Dominance triple from affective_now.dimensions.
    """
    social_context: Optional[SocialContext] = None
    """
    Social context derived from participant_relationships.
    """
    social_intimacy: Optional[SocialIntimacy] = None
    """
    Social intimacy level. family=HIGH, friends=MEDIUM, unknown=LOW.
    """
    entity_salience: Optional[Dict[str, confloat(ge=0.0, le=1.0)]] = None
    """
    Map of person_id to salience score (0-1). From scoreboard.salience_map.
    """
    narrative: Optional[Narrative] = None
    """
    Narrative thread context from narrative_active.
    """
    temporal: Optional[Temporal] = None
    """
    Temporal context from beliefs_active.MentionedTime.
    """
    intent_type: Optional[IntentType] = None
    """
    Primary intent from control.intents[0] (UltraBERT primary).
    """
    goal_context: Optional[str] = None
    """
    Active thread goal if relevant. From narrative_active.primary_thread.goal.
    """
    source_type: SourceType
    """
    Memory provenance. MW cross-references history_active turns vs extraction origin.
    """
    novelty: Novelty
    """
    Novelty classification. MW compares against beliefs + scoreboard.
    """
    elaboration_depth: ElaborationDepth
    """
    How deeply the topic was discussed. MW counts turns on topic from history.
    """
    identity_domains: Optional[List[IdentityDomain]] = None
    """
    Identity categories activated by this memory. MW maps domains + topics + relationships.
    """
    temporal_orientation: TemporalOrientation
    """
    Temporal orientation. MW compares resolved_epoch_ms vs now.
    """
    task_context: Optional[str] = None
    """
    Active task action if extraction relates to a task. From task_state.
    """
    confidence: confloat(ge=0.0, le=1.0)
    """
    LLM self-score confidence. Atoms below 0.30 are dropped.
    """
    session_id: str
    """
    Session UUID from meta.identity.session_id.
    """
    conversation_turn: conint(ge=0)
    """
    Turn ordinal from meta.lifecycle.turn_count.
    """
    extraction_sequence: conint(ge=0, le=5) = 0
    """
    0-based ordinal of this atom within the turn extraction batch.
    """
    language: constr(min_length=2, max_length=5)
    """
    ISO 639-1 language code. Default 'en'.
    """
    conversation_anchor_ms: conint(ge=0) = 0
    """
    K1 Concierge conversation timestamp (unix ms). Authoritative for R2 episode formation. NEVER overwritten by K0 M08. GAP-002 Epic 1.1.
    """
    temporal_links: List[TemporalLink] = Field(default=[], max_length=5)
    """
    0-5 temporal references per atom. Replaces single Temporal object. GAP-002 Epic 2.2.
    """
    correction_signal: bool = False
    """
    K1 LLM detected this atom corrects a previously stored fact. Flags atom as EVOLVE candidate for P03 R3 reconciliation. R2 Epic 7.2.
    """
    contradiction_signal: bool = False
    """
    K1 LLM detected this atom contradicts stored knowledge with no clear resolution. Flags atom as CONTRADICT candidate for P03 R3 reconciliation. R2 Epic 7.2.
    """
    supersedes_concept: Optional[str] = None
    """
    Namespaced concept key being replaced (e.g. 'cuisine_preference:thai', 'school:riverdale'). Gives P03 a targeted truth lookup instead of brute-force embedding search. R2 Epic 7.2.
    """
    correction_source: CorrectionSource = None
    """
    How the correction was detected: user_explicit (direct statement), user_implicit (inferred from context shift), context_change (environmental change). R2 Epic 7.2.
    """
    session_context_id: Optional[str] = None
    """
    Session UUID where correction was detected. Enables P03 audit trail for EVOLVE/CONTRADICT decisions. R2 Epic 7.2.
    """
