# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/p03.gap.detected.v1.yaml
# generated by datamodel-codegen:
#   filename:  p03.gap.detected.v1.json

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, confloat, conint, constr


class GapType(Enum):
    """
    Type of knowledge gap.
    """

    MISSING_CONTEXT = 'MISSING_CONTEXT'
    AMBIGUOUS_REFERENCE = 'AMBIGUOUS_REFERENCE'
    LOW_CONFIDENCE = 'LOW_CONFIDENCE'
    CONTRADICTION = 'CONTRADICTION'
    INCOMPLETE_SEQUENCE = 'INCOMPLETE_SEQUENCE'
    UNKNOWN_RELATIONSHIP = 'UNKNOWN_RELATIONSHIP'


class P03GapDetectedV1(BaseModel):
    """
    K0→K1 SSE event payload: a knowledge-gap detected during P03 consolidation that P06 may want to investigate. Mirrors the K0-internal ``p03.gap.detected.v1`` outbox topic, narrowed to the cross-kernel surface; fields beyond what K1 needs (e.g. ``cycle_id``) are stripped on the K0 emit boundary.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(min_length=1)
    """
    Per-event ULID. Used as the SSE Last-Event-ID cursor token.
    """
    gap_id: constr(min_length=1)
    """
    Stable gap identifier (st_learning_queue.gap_id).
    """
    gap_type: GapType
    """
    Type of knowledge gap.
    """
    detected_at_utc_ms: conint(ge=0)
    """
    UTC epoch milliseconds when the gap was detected.
    """
    question_template: Optional[str] = None
    """
    Suggested natural-language question for P06.
    """
    priority_score: Optional[confloat(ge=0.0, le=1.0)] = None
    """
    Gap priority score (0–1).
    """
    tenant_id: Optional[str] = None
    """
    Tenant identifier.
    """
    space_id: Optional[str] = None
    """
    Memory-space identifier.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace identifier.
    """
