# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/recall.request.v1.yaml
# generated by datamodel-codegen:
#   filename:  recall.request.v1.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class TimeRange(BaseModel):
    """
    Optional UTC epoch-ms time window.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    after_utc_ms: Optional[conint(ge=0)] = None
    """
    Only return atoms created at or after this UTC epoch ms.
    """
    before_utc_ms: Optional[conint(ge=0)] = None
    """
    Only return atoms created at or before this UTC epoch ms.
    """


class Type(Enum):
    """
    Selector kind.
    """

    episodic = 'episodic'
    semantic = 'semantic'
    session = 'session'
    device = 'device'
    belief = 'belief'
    graph = 'graph'


class RecallSelector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    """
    Selector kind.
    """
    topic: Optional[str] = None
    """
    Optional topic filter within the selector kind.
    """
    limit: conint(ge=1, le=256) = 10
    """
    Per-selector cap.
    """
    cursor: Optional[str] = None
    """
    Pagination cursor (selector-specific).
    """
    after: Optional[str] = None
    """
    ISO-8601 timestamp — only return items after this time.
    """
    query: Optional[str] = None
    """
    Free-text query for semantic/graph selectors.
    """


class RecallRequestV1(BaseModel):
    """
    Request body for recall.request.v1 (K1→K0). Carries one or more selectors plus QoS hints. Paired with recall.response.v1.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    selectors: List[RecallSelector] = Field(..., max_length=16, min_length=1)
    """
    One or more recall selectors describing what to fetch from K0.
    """
    space_id: constr(min_length=1)
    """
    Tenant space identifier.
    """
    tenant_id: Optional[str] = None
    """
    Tenant identifier; defaults to space owner if absent.
    """
    max_latency_ms: conint(ge=1, le=10000) = 250
    """
    Client-provided bound on acceptable round-trip latency.
    """
    fail_fast: bool = False
    """
    Return partial results when the latency budget is exhausted instead of waiting for every selector.
    """
    max_results: conint(ge=1, le=256) = 10
    """
    Aggregate cap across all selectors.
    """
    vector_query: Optional[str] = None
    """
    Optional free-text vector query for semantic selectors.
    """
    fts_query: Optional[str] = None
    """
    Optional full-text-search query for episodic/keyword selectors.
    """
    time_range: Optional[TimeRange] = None
    """
    Optional UTC epoch-ms time window.
    """
    trace_id: Optional[str] = None
    """
    Cognitive trace identifier echoed back in the response.
    """
