# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/memory.write.v1.yaml

"""Generated handler-registry stub for the ``memory.write.v1`` contract.

Consumer side. The hand-written implementation
``bridge/_generated/k0/handlers/memory_write_v1_impl.py``
provides the actual K0-side function; this file wires it into the
:class:`bridge.runtime.BridgeRuntime` dispatcher.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING

from bridge._generated.k0.models.memory_write_v1 import (
    MemoryWriteV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from bridge.runtime import BridgeRuntime


HandlerImpl = Callable[[MemoryWriteV1], Awaitable[object]]
"""Type alias for the hand-written impl signature."""


def register_handlers(runtime: "BridgeRuntime", *, impl: HandlerImpl) -> None:
    """Register ``impl`` as the K0-side handler for ``memory.write.v1``.

    The dispatcher looks the topic up by exact match and routes Pydantic
    payloads to ``impl``. Idempotency, signing verification, and audit
    logging happen upstream of this call inside the runtime; ``impl`` may
    assume the body has already been validated against
    ``MemoryWriteV1``.
    """
    runtime.register_handler(
        topic="memory.write.v1",
        model=  MemoryWriteV1,
        impl=impl,
    )


__topic__ = "memory.write.v1"
