# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/observability.payload.v1.yaml

"""Generated obs-channel handler stub for the ``observability.payload.v1`` contract.

Consumer side (K0). Obs/feedback dispatch happens inside
:mod:`k0.ports.observe` directly — the ``/k0/obs.emit`` route routes
by inner ``kind`` (feedback|metrics|logs) and writes either to
``st_feedback_signals`` or to the ForwardedMetricsBuffer / log
re-emitter. There is no per-topic handler registration on the bridge
runtime: the K0 endpoint is the dispatcher.

This stub exists only so the codegen layout stays uniform and so
imports of ``bridge._generated.k0.handlers.observability_payload_v1``
do not fail. It provides the topic constant and the generated model
class for tests that wish to validate fixtures end-to-end without
booting K0.
"""

from __future__ import annotations

from bridge._generated.k0.models.observability_payload_v1 import (
    ObservabilityPayloadV1,
)

__topic__ = "observability.payload.v1"
__model__ = ObservabilityPayloadV1
