# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Active task (in-flight execution)
class ActiveTask(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ActiveTask()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsActiveTask(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ActiveTaskBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # ActiveTask
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ActiveTask
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ActiveTask
    def ParentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ActiveTask
    def TurnId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ActiveTask
    def AgentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ActiveTask
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ActiveTask
    def StartedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ActiveTask
    def DeadlineMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ActiveTask
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ActiveTaskStart(builder):
    builder.StartObject(8)

def Start(builder):
    ActiveTaskStart(builder)

def ActiveTaskAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ActiveTaskAddId(builder, id)

def ActiveTaskAddParentId(builder, parentId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(parentId), 0)

def AddParentId(builder, parentId):
    ActiveTaskAddParentId(builder, parentId)

def ActiveTaskAddTurnId(builder, turnId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)

def AddTurnId(builder, turnId):
    ActiveTaskAddTurnId(builder, turnId)

def ActiveTaskAddAgentId(builder, agentId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(agentId), 0)

def AddAgentId(builder, agentId):
    ActiveTaskAddAgentId(builder, agentId)

def ActiveTaskAddStatus(builder, status):
    builder.PrependUint8Slot(4, status, 0)

def AddStatus(builder, status):
    ActiveTaskAddStatus(builder, status)

def ActiveTaskAddStartedAtMs(builder, startedAtMs):
    builder.PrependUint64Slot(5, startedAtMs, 0)

def AddStartedAtMs(builder, startedAtMs):
    ActiveTaskAddStartedAtMs(builder, startedAtMs)

def ActiveTaskAddDeadlineMs(builder, deadlineMs):
    builder.PrependUint64Slot(6, deadlineMs, 0)

def AddDeadlineMs(builder, deadlineMs):
    ActiveTaskAddDeadlineMs(builder, deadlineMs)

def ActiveTaskAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(7, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    ActiveTaskAddUpdatedAtMs(builder, updatedAtMs)

def ActiveTaskEnd(builder):
    return builder.EndObject()

def End(builder):
    return ActiveTaskEnd(builder)


class ActiveTaskT(object):

    # ActiveTaskT
    def __init__(self):
        self.id = None  # type: str
        self.parentId = None  # type: str
        self.turnId = None  # type: str
        self.agentId = None  # type: str
        self.status = 0  # type: int
        self.startedAtMs = 0  # type: int
        self.deadlineMs = 0  # type: int
        self.updatedAtMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        activeTask = ActiveTask()
        activeTask.Init(buf, pos)
        return cls.InitFromObj(activeTask)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, activeTask):
        x = ActiveTaskT()
        x._UnPack(activeTask)
        return x

    # ActiveTaskT
    def _UnPack(self, activeTask):
        if activeTask is None:
            return
        self.id = activeTask.Id()
        self.parentId = activeTask.ParentId()
        self.turnId = activeTask.TurnId()
        self.agentId = activeTask.AgentId()
        self.status = activeTask.Status()
        self.startedAtMs = activeTask.StartedAtMs()
        self.deadlineMs = activeTask.DeadlineMs()
        self.updatedAtMs = activeTask.UpdatedAtMs()

    # ActiveTaskT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.parentId is not None:
            parentId = builder.CreateString(self.parentId)
        if self.turnId is not None:
            turnId = builder.CreateString(self.turnId)
        if self.agentId is not None:
            agentId = builder.CreateString(self.agentId)
        ActiveTaskStart(builder)
        if self.id is not None:
            ActiveTaskAddId(builder, id)
        if self.parentId is not None:
            ActiveTaskAddParentId(builder, parentId)
        if self.turnId is not None:
            ActiveTaskAddTurnId(builder, turnId)
        if self.agentId is not None:
            ActiveTaskAddAgentId(builder, agentId)
        ActiveTaskAddStatus(builder, self.status)
        ActiveTaskAddStartedAtMs(builder, self.startedAtMs)
        ActiveTaskAddDeadlineMs(builder, self.deadlineMs)
        ActiveTaskAddUpdatedAtMs(builder, self.updatedAtMs)
        activeTask = ActiveTaskEnd(builder)
        return activeTask
