# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Agent score (performance tracking for selection, zero-copy struct)
# Used in hot path for agent selection (MADM 6-factor scoring)
class AgentScore(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # AgentScore
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AgentScore
    def AgentId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # AgentScore
    def Score(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # AgentScore
    def Confidence(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # AgentScore
    def Basis(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # AgentScore
    def TasksCompleted(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))
    # AgentScore
    def TasksFailed(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # AgentScore
    def LatencyP95Ms(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # AgentScore
    def LastUsedMs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateAgentScore(builder, agentId, score, confidence, basis, tasksCompleted, tasksFailed, latencyP95Ms, lastUsedMs):
    builder.Prep(8, 32)
    builder.PrependUint64(lastUsedMs)
    builder.PrependFloat32(latencyP95Ms)
    builder.Pad(2)
    builder.PrependUint16(tasksFailed)
    builder.PrependUint16(tasksCompleted)
    builder.Pad(1)
    builder.PrependUint8(basis)
    builder.PrependFloat32(confidence)
    builder.PrependFloat32(score)
    builder.PrependUint32(agentId)
    return builder.Offset()


class AgentScoreT(object):

    # AgentScoreT
    def __init__(self):
        self.agentId = 0  # type: int
        self.score = 0.0  # type: float
        self.confidence = 0.0  # type: float
        self.basis = 0  # type: int
        self.tasksCompleted = 0  # type: int
        self.tasksFailed = 0  # type: int
        self.latencyP95Ms = 0.0  # type: float
        self.lastUsedMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        agentScore = AgentScore()
        agentScore.Init(buf, pos)
        return cls.InitFromObj(agentScore)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, agentScore):
        x = AgentScoreT()
        x._UnPack(agentScore)
        return x

    # AgentScoreT
    def _UnPack(self, agentScore):
        if agentScore is None:
            return
        self.agentId = agentScore.AgentId()
        self.score = agentScore.Score()
        self.confidence = agentScore.Confidence()
        self.basis = agentScore.Basis()
        self.tasksCompleted = agentScore.TasksCompleted()
        self.tasksFailed = agentScore.TasksFailed()
        self.latencyP95Ms = agentScore.LatencyP95Ms()
        self.lastUsedMs = agentScore.LastUsedMs()

    # AgentScoreT
    def Pack(self, builder):
        return CreateAgentScore(builder, self.agentId, self.score, self.confidence, self.basis, self.tasksCompleted, self.tasksFailed, self.latencyP95Ms, self.lastUsedMs)
