# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

# Backpressure severity tier (3-tier cascade from ADR-0061)
class BackpressureTier(object):
    NONE = 0
    WARN = 1
    DEGRADE = 2
    REJECT = 3
