# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Backpressure state (3-tier cascade, ADR-0061/0061a)
class BackpressureState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BackpressureState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBackpressureState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BackpressureStateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # BackpressureState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BackpressureState
    def Tier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # BackpressureState
    def QueueDepth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BackpressureState
    def LatencyP95Ms(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BackpressureState
    def ThrottlingEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BackpressureState
    def RejectionEnabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # BackpressureState
    def LastEventMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def BackpressureStateStart(builder):
    builder.StartObject(6)

def Start(builder):
    BackpressureStateStart(builder)

def BackpressureStateAddTier(builder, tier):
    builder.PrependUint8Slot(0, tier, 0)

def AddTier(builder, tier):
    BackpressureStateAddTier(builder, tier)

def BackpressureStateAddQueueDepth(builder, queueDepth):
    builder.PrependUint32Slot(1, queueDepth, 0)

def AddQueueDepth(builder, queueDepth):
    BackpressureStateAddQueueDepth(builder, queueDepth)

def BackpressureStateAddLatencyP95Ms(builder, latencyP95Ms):
    builder.PrependFloat32Slot(2, latencyP95Ms, 0.0)

def AddLatencyP95Ms(builder, latencyP95Ms):
    BackpressureStateAddLatencyP95Ms(builder, latencyP95Ms)

def BackpressureStateAddThrottlingEnabled(builder, throttlingEnabled):
    builder.PrependBoolSlot(3, throttlingEnabled, 0)

def AddThrottlingEnabled(builder, throttlingEnabled):
    BackpressureStateAddThrottlingEnabled(builder, throttlingEnabled)

def BackpressureStateAddRejectionEnabled(builder, rejectionEnabled):
    builder.PrependBoolSlot(4, rejectionEnabled, 0)

def AddRejectionEnabled(builder, rejectionEnabled):
    BackpressureStateAddRejectionEnabled(builder, rejectionEnabled)

def BackpressureStateAddLastEventMs(builder, lastEventMs):
    builder.PrependUint64Slot(5, lastEventMs, 0)

def AddLastEventMs(builder, lastEventMs):
    BackpressureStateAddLastEventMs(builder, lastEventMs)

def BackpressureStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return BackpressureStateEnd(builder)


class BackpressureStateT(object):

    # BackpressureStateT
    def __init__(self):
        self.tier = 0  # type: int
        self.queueDepth = 0  # type: int
        self.latencyP95Ms = 0.0  # type: float
        self.throttlingEnabled = False  # type: bool
        self.rejectionEnabled = False  # type: bool
        self.lastEventMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        backpressureState = BackpressureState()
        backpressureState.Init(buf, pos)
        return cls.InitFromObj(backpressureState)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, backpressureState):
        x = BackpressureStateT()
        x._UnPack(backpressureState)
        return x

    # BackpressureStateT
    def _UnPack(self, backpressureState):
        if backpressureState is None:
            return
        self.tier = backpressureState.Tier()
        self.queueDepth = backpressureState.QueueDepth()
        self.latencyP95Ms = backpressureState.LatencyP95Ms()
        self.throttlingEnabled = backpressureState.ThrottlingEnabled()
        self.rejectionEnabled = backpressureState.RejectionEnabled()
        self.lastEventMs = backpressureState.LastEventMs()

    # BackpressureStateT
    def Pack(self, builder):
        BackpressureStateStart(builder)
        BackpressureStateAddTier(builder, self.tier)
        BackpressureStateAddQueueDepth(builder, self.queueDepth)
        BackpressureStateAddLatencyP95Ms(builder, self.latencyP95Ms)
        BackpressureStateAddThrottlingEnabled(builder, self.throttlingEnabled)
        BackpressureStateAddRejectionEnabled(builder, self.rejectionEnabled)
        BackpressureStateAddLastEventMs(builder, self.lastEventMs)
        backpressureState = BackpressureStateEnd(builder)
        return backpressureState
