# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Beliefs section (user model, context, facts)
# Tier 1 eviction priority (evict first under memory pressure)
class BeliefsSection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BeliefsSection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBeliefsSection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BeliefsSectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # BeliefsSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BeliefsSection
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BeliefsSection
    def UserFacts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from k1.l4_runtime.session_state.model.UserFact import UserFact
            obj = UserFact()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BeliefsSection
    def UserFactsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BeliefsSection
    def UserFactsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # BeliefsSection
    def WorldKnowledge(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from k1.l4_runtime.session_state.model.WorldKnowledge import WorldKnowledge
            obj = WorldKnowledge()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BeliefsSection
    def WorldKnowledgeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BeliefsSection
    def WorldKnowledgeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # BeliefsSection
    def Temporal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.TemporalContext import TemporalContext
            obj = TemporalContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BeliefsSection
    def Spatial(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.SpatialContext import SpatialContext
            obj = SpatialContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BeliefsSection
    def SectionSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BeliefsSectionStart(builder):
    builder.StartObject(6)

def Start(builder):
    BeliefsSectionStart(builder)

def BeliefsSectionAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(0, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    BeliefsSectionAddUpdatedAtMs(builder, updatedAtMs)

def BeliefsSectionAddUserFacts(builder, userFacts):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(userFacts), 0)

def AddUserFacts(builder, userFacts):
    BeliefsSectionAddUserFacts(builder, userFacts)

def BeliefsSectionStartUserFactsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartUserFactsVector(builder, numElems):
    return BeliefsSectionStartUserFactsVector(builder, numElems)

def BeliefsSectionAddWorldKnowledge(builder, worldKnowledge):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(worldKnowledge), 0)

def AddWorldKnowledge(builder, worldKnowledge):
    BeliefsSectionAddWorldKnowledge(builder, worldKnowledge)

def BeliefsSectionStartWorldKnowledgeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWorldKnowledgeVector(builder, numElems):
    return BeliefsSectionStartWorldKnowledgeVector(builder, numElems)

def BeliefsSectionAddTemporal(builder, temporal):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(temporal), 0)

def AddTemporal(builder, temporal):
    BeliefsSectionAddTemporal(builder, temporal)

def BeliefsSectionAddSpatial(builder, spatial):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(spatial), 0)

def AddSpatial(builder, spatial):
    BeliefsSectionAddSpatial(builder, spatial)

def BeliefsSectionAddSectionSizeBytes(builder, sectionSizeBytes):
    builder.PrependUint32Slot(5, sectionSizeBytes, 0)

def AddSectionSizeBytes(builder, sectionSizeBytes):
    BeliefsSectionAddSectionSizeBytes(builder, sectionSizeBytes)

def BeliefsSectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return BeliefsSectionEnd(builder)

import k1.l4_runtime.session_state.model.SpatialContext
import k1.l4_runtime.session_state.model.TemporalContext
import k1.l4_runtime.session_state.model.UserFact
import k1.l4_runtime.session_state.model.WorldKnowledge
try:
    from typing import List, Optional
except:
    pass

class BeliefsSectionT(object):

    # BeliefsSectionT
    def __init__(self):
        self.updatedAtMs = 0  # type: int
        self.userFacts = None  # type: List[k1.l4_runtime.session_state.model.UserFact.UserFactT]
        self.worldKnowledge = None  # type: List[k1.l4_runtime.session_state.model.WorldKnowledge.WorldKnowledgeT]
        self.temporal = None  # type: Optional[k1.l4_runtime.session_state.model.TemporalContext.TemporalContextT]
        self.spatial = None  # type: Optional[k1.l4_runtime.session_state.model.SpatialContext.SpatialContextT]
        self.sectionSizeBytes = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        beliefsSection = BeliefsSection()
        beliefsSection.Init(buf, pos)
        return cls.InitFromObj(beliefsSection)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, beliefsSection):
        x = BeliefsSectionT()
        x._UnPack(beliefsSection)
        return x

    # BeliefsSectionT
    def _UnPack(self, beliefsSection):
        if beliefsSection is None:
            return
        self.updatedAtMs = beliefsSection.UpdatedAtMs()
        if not beliefsSection.UserFactsIsNone():
            self.userFacts = []
            for i in range(beliefsSection.UserFactsLength()):
                if beliefsSection.UserFacts(i) is None:
                    self.userFacts.append(None)
                else:
                    userFact_ = k1.l4_runtime.session_state.model.UserFact.UserFactT.InitFromObj(beliefsSection.UserFacts(i))
                    self.userFacts.append(userFact_)
        if not beliefsSection.WorldKnowledgeIsNone():
            self.worldKnowledge = []
            for i in range(beliefsSection.WorldKnowledgeLength()):
                if beliefsSection.WorldKnowledge(i) is None:
                    self.worldKnowledge.append(None)
                else:
                    worldKnowledge_ = k1.l4_runtime.session_state.model.WorldKnowledge.WorldKnowledgeT.InitFromObj(beliefsSection.WorldKnowledge(i))
                    self.worldKnowledge.append(worldKnowledge_)
        if beliefsSection.Temporal() is not None:
            self.temporal = k1.l4_runtime.session_state.model.TemporalContext.TemporalContextT.InitFromObj(beliefsSection.Temporal())
        if beliefsSection.Spatial() is not None:
            self.spatial = k1.l4_runtime.session_state.model.SpatialContext.SpatialContextT.InitFromObj(beliefsSection.Spatial())
        self.sectionSizeBytes = beliefsSection.SectionSizeBytes()

    # BeliefsSectionT
    def Pack(self, builder):
        if self.userFacts is not None:
            userFactslist = []
            for i in range(len(self.userFacts)):
                userFactslist.append(self.userFacts[i].Pack(builder))
            BeliefsSectionStartUserFactsVector(builder, len(self.userFacts))
            for i in reversed(range(len(self.userFacts))):
                builder.PrependUOffsetTRelative(userFactslist[i])
            userFacts = builder.EndVector()
        if self.worldKnowledge is not None:
            worldKnowledgelist = []
            for i in range(len(self.worldKnowledge)):
                worldKnowledgelist.append(self.worldKnowledge[i].Pack(builder))
            BeliefsSectionStartWorldKnowledgeVector(builder, len(self.worldKnowledge))
            for i in reversed(range(len(self.worldKnowledge))):
                builder.PrependUOffsetTRelative(worldKnowledgelist[i])
            worldKnowledge = builder.EndVector()
        if self.temporal is not None:
            temporal = self.temporal.Pack(builder)
        if self.spatial is not None:
            spatial = self.spatial.Pack(builder)
        BeliefsSectionStart(builder)
        BeliefsSectionAddUpdatedAtMs(builder, self.updatedAtMs)
        if self.userFacts is not None:
            BeliefsSectionAddUserFacts(builder, userFacts)
        if self.worldKnowledge is not None:
            BeliefsSectionAddWorldKnowledge(builder, worldKnowledge)
        if self.temporal is not None:
            BeliefsSectionAddTemporal(builder, temporal)
        if self.spatial is not None:
            BeliefsSectionAddSpatial(builder, spatial)
        BeliefsSectionAddSectionSizeBytes(builder, self.sectionSizeBytes)
        beliefsSection = BeliefsSectionEnd(builder)
        return beliefsSection
