# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Blob reference (audio/vision stored in K0, not in SessionState)
# Keeps SessionState <10 MB and deltas tiny (250ms K0 flush cadence)
class BlobRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BlobRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBlobRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BlobRefBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # BlobRef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BlobRef
    def Store(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BlobRef
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BlobRef
    def SizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BlobRef
    def CreatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # BlobRef
    def MimeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BlobRefStart(builder):
    builder.StartObject(5)

def Start(builder):
    BlobRefStart(builder)

def BlobRefAddStore(builder, store):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(store), 0)

def AddStore(builder, store):
    BlobRefAddStore(builder, store)

def BlobRefAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    BlobRefAddKey(builder, key)

def BlobRefAddSizeBytes(builder, sizeBytes):
    builder.PrependUint32Slot(2, sizeBytes, 0)

def AddSizeBytes(builder, sizeBytes):
    BlobRefAddSizeBytes(builder, sizeBytes)

def BlobRefAddCreatedAtMs(builder, createdAtMs):
    builder.PrependUint64Slot(3, createdAtMs, 0)

def AddCreatedAtMs(builder, createdAtMs):
    BlobRefAddCreatedAtMs(builder, createdAtMs)

def BlobRefAddMimeType(builder, mimeType):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(mimeType), 0)

def AddMimeType(builder, mimeType):
    BlobRefAddMimeType(builder, mimeType)

def BlobRefEnd(builder):
    return builder.EndObject()

def End(builder):
    return BlobRefEnd(builder)


class BlobRefT(object):

    # BlobRefT
    def __init__(self):
        self.store = None  # type: str
        self.key = None  # type: str
        self.sizeBytes = 0  # type: int
        self.createdAtMs = 0  # type: int
        self.mimeType = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        blobRef = BlobRef()
        blobRef.Init(buf, pos)
        return cls.InitFromObj(blobRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, blobRef):
        x = BlobRefT()
        x._UnPack(blobRef)
        return x

    # BlobRefT
    def _UnPack(self, blobRef):
        if blobRef is None:
            return
        self.store = blobRef.Store()
        self.key = blobRef.Key()
        self.sizeBytes = blobRef.SizeBytes()
        self.createdAtMs = blobRef.CreatedAtMs()
        self.mimeType = blobRef.MimeType()

    # BlobRefT
    def Pack(self, builder):
        if self.store is not None:
            store = builder.CreateString(self.store)
        if self.key is not None:
            key = builder.CreateString(self.key)
        if self.mimeType is not None:
            mimeType = builder.CreateString(self.mimeType)
        BlobRefStart(builder)
        if self.store is not None:
            BlobRefAddStore(builder, store)
        if self.key is not None:
            BlobRefAddKey(builder, key)
        BlobRefAddSizeBytes(builder, self.sizeBytes)
        BlobRefAddCreatedAtMs(builder, self.createdAtMs)
        if self.mimeType is not None:
            BlobRefAddMimeType(builder, mimeType)
        blobRef = BlobRefEnd(builder)
        return blobRef
