# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

# Checksum algorithm for integrity verification
class ChecksumAlgo(object):
    NONE = 0
    XXH3 = 1
    BLAKE3 = 2
