# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Control section (orchestration, backpressure, saga)
# Tier 3 eviction priority (last resort, keep scoreboard)
class ControlSection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlSection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsControlSection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ControlSectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # ControlSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlSection
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ControlSection
    def ActiveTasks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from k1.l4_runtime.session_state.model.ActiveTask import ActiveTask
            obj = ActiveTask()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ControlSection
    def ActiveTasksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ControlSection
    def ActiveTasksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ControlSection
    def PendingProposals(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from k1.l4_runtime.session_state.model.PendingProposal import PendingProposal
            obj = PendingProposal()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ControlSection
    def PendingProposalsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ControlSection
    def PendingProposalsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ControlSection
    def SagaCheckpoints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from k1.l4_runtime.session_state.model.SagaCheckpoint import SagaCheckpoint
            obj = SagaCheckpoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ControlSection
    def SagaCheckpointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ControlSection
    def SagaCheckpointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ControlSection
    def Backpressure(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.BackpressureState import BackpressureState
            obj = BackpressureState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ControlSection
    def SectionSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ControlSectionStart(builder):
    builder.StartObject(6)

def Start(builder):
    ControlSectionStart(builder)

def ControlSectionAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(0, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    ControlSectionAddUpdatedAtMs(builder, updatedAtMs)

def ControlSectionAddActiveTasks(builder, activeTasks):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(activeTasks), 0)

def AddActiveTasks(builder, activeTasks):
    ControlSectionAddActiveTasks(builder, activeTasks)

def ControlSectionStartActiveTasksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartActiveTasksVector(builder, numElems):
    return ControlSectionStartActiveTasksVector(builder, numElems)

def ControlSectionAddPendingProposals(builder, pendingProposals):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pendingProposals), 0)

def AddPendingProposals(builder, pendingProposals):
    ControlSectionAddPendingProposals(builder, pendingProposals)

def ControlSectionStartPendingProposalsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPendingProposalsVector(builder, numElems):
    return ControlSectionStartPendingProposalsVector(builder, numElems)

def ControlSectionAddSagaCheckpoints(builder, sagaCheckpoints):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sagaCheckpoints), 0)

def AddSagaCheckpoints(builder, sagaCheckpoints):
    ControlSectionAddSagaCheckpoints(builder, sagaCheckpoints)

def ControlSectionStartSagaCheckpointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSagaCheckpointsVector(builder, numElems):
    return ControlSectionStartSagaCheckpointsVector(builder, numElems)

def ControlSectionAddBackpressure(builder, backpressure):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(backpressure), 0)

def AddBackpressure(builder, backpressure):
    ControlSectionAddBackpressure(builder, backpressure)

def ControlSectionAddSectionSizeBytes(builder, sectionSizeBytes):
    builder.PrependUint32Slot(5, sectionSizeBytes, 0)

def AddSectionSizeBytes(builder, sectionSizeBytes):
    ControlSectionAddSectionSizeBytes(builder, sectionSizeBytes)

def ControlSectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ControlSectionEnd(builder)

import k1.l4_runtime.session_state.model.ActiveTask
import k1.l4_runtime.session_state.model.BackpressureState
import k1.l4_runtime.session_state.model.PendingProposal
import k1.l4_runtime.session_state.model.SagaCheckpoint
try:
    from typing import List, Optional
except:
    pass

class ControlSectionT(object):

    # ControlSectionT
    def __init__(self):
        self.updatedAtMs = 0  # type: int
        self.activeTasks = None  # type: List[k1.l4_runtime.session_state.model.ActiveTask.ActiveTaskT]
        self.pendingProposals = None  # type: List[k1.l4_runtime.session_state.model.PendingProposal.PendingProposalT]
        self.sagaCheckpoints = None  # type: List[k1.l4_runtime.session_state.model.SagaCheckpoint.SagaCheckpointT]
        self.backpressure = None  # type: Optional[k1.l4_runtime.session_state.model.BackpressureState.BackpressureStateT]
        self.sectionSizeBytes = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        controlSection = ControlSection()
        controlSection.Init(buf, pos)
        return cls.InitFromObj(controlSection)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, controlSection):
        x = ControlSectionT()
        x._UnPack(controlSection)
        return x

    # ControlSectionT
    def _UnPack(self, controlSection):
        if controlSection is None:
            return
        self.updatedAtMs = controlSection.UpdatedAtMs()
        if not controlSection.ActiveTasksIsNone():
            self.activeTasks = []
            for i in range(controlSection.ActiveTasksLength()):
                if controlSection.ActiveTasks(i) is None:
                    self.activeTasks.append(None)
                else:
                    activeTask_ = k1.l4_runtime.session_state.model.ActiveTask.ActiveTaskT.InitFromObj(controlSection.ActiveTasks(i))
                    self.activeTasks.append(activeTask_)
        if not controlSection.PendingProposalsIsNone():
            self.pendingProposals = []
            for i in range(controlSection.PendingProposalsLength()):
                if controlSection.PendingProposals(i) is None:
                    self.pendingProposals.append(None)
                else:
                    pendingProposal_ = k1.l4_runtime.session_state.model.PendingProposal.PendingProposalT.InitFromObj(controlSection.PendingProposals(i))
                    self.pendingProposals.append(pendingProposal_)
        if not controlSection.SagaCheckpointsIsNone():
            self.sagaCheckpoints = []
            for i in range(controlSection.SagaCheckpointsLength()):
                if controlSection.SagaCheckpoints(i) is None:
                    self.sagaCheckpoints.append(None)
                else:
                    sagaCheckpoint_ = k1.l4_runtime.session_state.model.SagaCheckpoint.SagaCheckpointT.InitFromObj(controlSection.SagaCheckpoints(i))
                    self.sagaCheckpoints.append(sagaCheckpoint_)
        if controlSection.Backpressure() is not None:
            self.backpressure = k1.l4_runtime.session_state.model.BackpressureState.BackpressureStateT.InitFromObj(controlSection.Backpressure())
        self.sectionSizeBytes = controlSection.SectionSizeBytes()

    # ControlSectionT
    def Pack(self, builder):
        if self.activeTasks is not None:
            activeTaskslist = []
            for i in range(len(self.activeTasks)):
                activeTaskslist.append(self.activeTasks[i].Pack(builder))
            ControlSectionStartActiveTasksVector(builder, len(self.activeTasks))
            for i in reversed(range(len(self.activeTasks))):
                builder.PrependUOffsetTRelative(activeTaskslist[i])
            activeTasks = builder.EndVector()
        if self.pendingProposals is not None:
            pendingProposalslist = []
            for i in range(len(self.pendingProposals)):
                pendingProposalslist.append(self.pendingProposals[i].Pack(builder))
            ControlSectionStartPendingProposalsVector(builder, len(self.pendingProposals))
            for i in reversed(range(len(self.pendingProposals))):
                builder.PrependUOffsetTRelative(pendingProposalslist[i])
            pendingProposals = builder.EndVector()
        if self.sagaCheckpoints is not None:
            sagaCheckpointslist = []
            for i in range(len(self.sagaCheckpoints)):
                sagaCheckpointslist.append(self.sagaCheckpoints[i].Pack(builder))
            ControlSectionStartSagaCheckpointsVector(builder, len(self.sagaCheckpoints))
            for i in reversed(range(len(self.sagaCheckpoints))):
                builder.PrependUOffsetTRelative(sagaCheckpointslist[i])
            sagaCheckpoints = builder.EndVector()
        if self.backpressure is not None:
            backpressure = self.backpressure.Pack(builder)
        ControlSectionStart(builder)
        ControlSectionAddUpdatedAtMs(builder, self.updatedAtMs)
        if self.activeTasks is not None:
            ControlSectionAddActiveTasks(builder, activeTasks)
        if self.pendingProposals is not None:
            ControlSectionAddPendingProposals(builder, pendingProposals)
        if self.sagaCheckpoints is not None:
            ControlSectionAddSagaCheckpoints(builder, sagaCheckpoints)
        if self.backpressure is not None:
            ControlSectionAddBackpressure(builder, backpressure)
        ControlSectionAddSectionSizeBytes(builder, self.sectionSizeBytes)
        controlSection = ControlSectionEnd(builder)
        return controlSection
