# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Meta section (schema version, integrity, privacy)
class MetaSection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MetaSection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMetaSection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MetaSectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # MetaSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MetaSection
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MetaSection
    def Checksum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MetaSection
    def ChecksumAlgo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # MetaSection
    def Compression(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MetaSection
    def CreatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MetaSection
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MetaSection
    def Notes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MetaSection
    def RedactionBand(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def MetaSectionStart(builder):
    builder.StartObject(8)

def Start(builder):
    MetaSectionStart(builder)

def MetaSectionAddSchemaVersion(builder, schemaVersion):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(schemaVersion), 0)

def AddSchemaVersion(builder, schemaVersion):
    MetaSectionAddSchemaVersion(builder, schemaVersion)

def MetaSectionAddChecksum(builder, checksum):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(checksum), 0)

def AddChecksum(builder, checksum):
    MetaSectionAddChecksum(builder, checksum)

def MetaSectionAddChecksumAlgo(builder, checksumAlgo):
    builder.PrependUint8Slot(2, checksumAlgo, 1)

def AddChecksumAlgo(builder, checksumAlgo):
    MetaSectionAddChecksumAlgo(builder, checksumAlgo)

def MetaSectionAddCompression(builder, compression):
    builder.PrependUint8Slot(3, compression, 0)

def AddCompression(builder, compression):
    MetaSectionAddCompression(builder, compression)

def MetaSectionAddCreatedAtMs(builder, createdAtMs):
    builder.PrependUint64Slot(4, createdAtMs, 0)

def AddCreatedAtMs(builder, createdAtMs):
    MetaSectionAddCreatedAtMs(builder, createdAtMs)

def MetaSectionAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(5, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    MetaSectionAddUpdatedAtMs(builder, updatedAtMs)

def MetaSectionAddNotes(builder, notes):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(notes), 0)

def AddNotes(builder, notes):
    MetaSectionAddNotes(builder, notes)

def MetaSectionAddRedactionBand(builder, redactionBand):
    builder.PrependUint8Slot(7, redactionBand, 0)

def AddRedactionBand(builder, redactionBand):
    MetaSectionAddRedactionBand(builder, redactionBand)

def MetaSectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return MetaSectionEnd(builder)


class MetaSectionT(object):

    # MetaSectionT
    def __init__(self):
        self.schemaVersion = None  # type: str
        self.checksum = None  # type: str
        self.checksumAlgo = 1  # type: int
        self.compression = 0  # type: int
        self.createdAtMs = 0  # type: int
        self.updatedAtMs = 0  # type: int
        self.notes = None  # type: str
        self.redactionBand = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        metaSection = MetaSection()
        metaSection.Init(buf, pos)
        return cls.InitFromObj(metaSection)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, metaSection):
        x = MetaSectionT()
        x._UnPack(metaSection)
        return x

    # MetaSectionT
    def _UnPack(self, metaSection):
        if metaSection is None:
            return
        self.schemaVersion = metaSection.SchemaVersion()
        self.checksum = metaSection.Checksum()
        self.checksumAlgo = metaSection.ChecksumAlgo()
        self.compression = metaSection.Compression()
        self.createdAtMs = metaSection.CreatedAtMs()
        self.updatedAtMs = metaSection.UpdatedAtMs()
        self.notes = metaSection.Notes()
        self.redactionBand = metaSection.RedactionBand()

    # MetaSectionT
    def Pack(self, builder):
        if self.schemaVersion is not None:
            schemaVersion = builder.CreateString(self.schemaVersion)
        if self.checksum is not None:
            checksum = builder.CreateString(self.checksum)
        if self.notes is not None:
            notes = builder.CreateString(self.notes)
        MetaSectionStart(builder)
        if self.schemaVersion is not None:
            MetaSectionAddSchemaVersion(builder, schemaVersion)
        if self.checksum is not None:
            MetaSectionAddChecksum(builder, checksum)
        MetaSectionAddChecksumAlgo(builder, self.checksumAlgo)
        MetaSectionAddCompression(builder, self.compression)
        MetaSectionAddCreatedAtMs(builder, self.createdAtMs)
        MetaSectionAddUpdatedAtMs(builder, self.updatedAtMs)
        if self.notes is not None:
            MetaSectionAddNotes(builder, notes)
        MetaSectionAddRedactionBand(builder, self.redactionBand)
        metaSection = MetaSectionEnd(builder)
        return metaSection
