# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Multimodal section (audio/text/vision references)
# Tier 2 eviction priority (evict after beliefs)
# Audio/vision stored as blob handles (not raw bytes) to keep deltas tiny
class MultimodalSection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultimodalSection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultimodalSection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MultimodalSectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # MultimodalSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultimodalSection
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MultimodalSection
    def Audio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.BlobRef import BlobRef
            obj = BlobRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MultimodalSection
    def Vision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.BlobRef import BlobRef
            obj = BlobRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MultimodalSection
    def TextHistory(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MultimodalSection
    def TextHistoryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MultimodalSection
    def TextHistoryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # MultimodalSection
    def LastModality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MultimodalSection
    def SectionSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MultimodalSectionStart(builder):
    builder.StartObject(6)

def Start(builder):
    MultimodalSectionStart(builder)

def MultimodalSectionAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(0, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    MultimodalSectionAddUpdatedAtMs(builder, updatedAtMs)

def MultimodalSectionAddAudio(builder, audio):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(audio), 0)

def AddAudio(builder, audio):
    MultimodalSectionAddAudio(builder, audio)

def MultimodalSectionAddVision(builder, vision):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vision), 0)

def AddVision(builder, vision):
    MultimodalSectionAddVision(builder, vision)

def MultimodalSectionAddTextHistory(builder, textHistory):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(textHistory), 0)

def AddTextHistory(builder, textHistory):
    MultimodalSectionAddTextHistory(builder, textHistory)

def MultimodalSectionStartTextHistoryVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTextHistoryVector(builder, numElems):
    return MultimodalSectionStartTextHistoryVector(builder, numElems)

def MultimodalSectionAddLastModality(builder, lastModality):
    builder.PrependUint8Slot(4, lastModality, 0)

def AddLastModality(builder, lastModality):
    MultimodalSectionAddLastModality(builder, lastModality)

def MultimodalSectionAddSectionSizeBytes(builder, sectionSizeBytes):
    builder.PrependUint32Slot(5, sectionSizeBytes, 0)

def AddSectionSizeBytes(builder, sectionSizeBytes):
    MultimodalSectionAddSectionSizeBytes(builder, sectionSizeBytes)

def MultimodalSectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return MultimodalSectionEnd(builder)

import k1.l4_runtime.session_state.model.BlobRef
try:
    from typing import List, Optional
except:
    pass

class MultimodalSectionT(object):

    # MultimodalSectionT
    def __init__(self):
        self.updatedAtMs = 0  # type: int
        self.audio = None  # type: Optional[k1.l4_runtime.session_state.model.BlobRef.BlobRefT]
        self.vision = None  # type: Optional[k1.l4_runtime.session_state.model.BlobRef.BlobRefT]
        self.textHistory = None  # type: List[str]
        self.lastModality = 0  # type: int
        self.sectionSizeBytes = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        multimodalSection = MultimodalSection()
        multimodalSection.Init(buf, pos)
        return cls.InitFromObj(multimodalSection)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, multimodalSection):
        x = MultimodalSectionT()
        x._UnPack(multimodalSection)
        return x

    # MultimodalSectionT
    def _UnPack(self, multimodalSection):
        if multimodalSection is None:
            return
        self.updatedAtMs = multimodalSection.UpdatedAtMs()
        if multimodalSection.Audio() is not None:
            self.audio = k1.l4_runtime.session_state.model.BlobRef.BlobRefT.InitFromObj(multimodalSection.Audio())
        if multimodalSection.Vision() is not None:
            self.vision = k1.l4_runtime.session_state.model.BlobRef.BlobRefT.InitFromObj(multimodalSection.Vision())
        if not multimodalSection.TextHistoryIsNone():
            self.textHistory = []
            for i in range(multimodalSection.TextHistoryLength()):
                self.textHistory.append(multimodalSection.TextHistory(i))
        self.lastModality = multimodalSection.LastModality()
        self.sectionSizeBytes = multimodalSection.SectionSizeBytes()

    # MultimodalSectionT
    def Pack(self, builder):
        if self.audio is not None:
            audio = self.audio.Pack(builder)
        if self.vision is not None:
            vision = self.vision.Pack(builder)
        if self.textHistory is not None:
            textHistorylist = []
            for i in range(len(self.textHistory)):
                textHistorylist.append(builder.CreateString(self.textHistory[i]))
            MultimodalSectionStartTextHistoryVector(builder, len(self.textHistory))
            for i in reversed(range(len(self.textHistory))):
                builder.PrependUOffsetTRelative(textHistorylist[i])
            textHistory = builder.EndVector()
        MultimodalSectionStart(builder)
        MultimodalSectionAddUpdatedAtMs(builder, self.updatedAtMs)
        if self.audio is not None:
            MultimodalSectionAddAudio(builder, audio)
        if self.vision is not None:
            MultimodalSectionAddVision(builder, vision)
        if self.textHistory is not None:
            MultimodalSectionAddTextHistory(builder, textHistory)
        MultimodalSectionAddLastModality(builder, self.lastModality)
        MultimodalSectionAddSectionSizeBytes(builder, self.sectionSizeBytes)
        multimodalSection = MultimodalSectionEnd(builder)
        return multimodalSection
