# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Pending proposal (Contract Net Protocol bidding)
class PendingProposal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PendingProposal()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPendingProposal(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PendingProposalBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # PendingProposal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PendingProposal
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PendingProposal
    def TaskId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PendingProposal
    def ProposerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PendingProposal
    def EstimatedLatencyMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # PendingProposal
    def ConfidenceScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # PendingProposal
    def TtlMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 5000

    # PendingProposal
    def CreatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PendingProposalStart(builder):
    builder.StartObject(7)

def Start(builder):
    PendingProposalStart(builder)

def PendingProposalAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    PendingProposalAddId(builder, id)

def PendingProposalAddTaskId(builder, taskId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(taskId), 0)

def AddTaskId(builder, taskId):
    PendingProposalAddTaskId(builder, taskId)

def PendingProposalAddProposerId(builder, proposerId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(proposerId), 0)

def AddProposerId(builder, proposerId):
    PendingProposalAddProposerId(builder, proposerId)

def PendingProposalAddEstimatedLatencyMs(builder, estimatedLatencyMs):
    builder.PrependUint32Slot(3, estimatedLatencyMs, 0)

def AddEstimatedLatencyMs(builder, estimatedLatencyMs):
    PendingProposalAddEstimatedLatencyMs(builder, estimatedLatencyMs)

def PendingProposalAddConfidenceScore(builder, confidenceScore):
    builder.PrependFloat32Slot(4, confidenceScore, 0.0)

def AddConfidenceScore(builder, confidenceScore):
    PendingProposalAddConfidenceScore(builder, confidenceScore)

def PendingProposalAddTtlMs(builder, ttlMs):
    builder.PrependUint32Slot(5, ttlMs, 5000)

def AddTtlMs(builder, ttlMs):
    PendingProposalAddTtlMs(builder, ttlMs)

def PendingProposalAddCreatedAtMs(builder, createdAtMs):
    builder.PrependUint64Slot(6, createdAtMs, 0)

def AddCreatedAtMs(builder, createdAtMs):
    PendingProposalAddCreatedAtMs(builder, createdAtMs)

def PendingProposalEnd(builder):
    return builder.EndObject()

def End(builder):
    return PendingProposalEnd(builder)


class PendingProposalT(object):

    # PendingProposalT
    def __init__(self):
        self.id = None  # type: str
        self.taskId = None  # type: str
        self.proposerId = None  # type: str
        self.estimatedLatencyMs = 0  # type: int
        self.confidenceScore = 0.0  # type: float
        self.ttlMs = 5000  # type: int
        self.createdAtMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        pendingProposal = PendingProposal()
        pendingProposal.Init(buf, pos)
        return cls.InitFromObj(pendingProposal)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, pendingProposal):
        x = PendingProposalT()
        x._UnPack(pendingProposal)
        return x

    # PendingProposalT
    def _UnPack(self, pendingProposal):
        if pendingProposal is None:
            return
        self.id = pendingProposal.Id()
        self.taskId = pendingProposal.TaskId()
        self.proposerId = pendingProposal.ProposerId()
        self.estimatedLatencyMs = pendingProposal.EstimatedLatencyMs()
        self.confidenceScore = pendingProposal.ConfidenceScore()
        self.ttlMs = pendingProposal.TtlMs()
        self.createdAtMs = pendingProposal.CreatedAtMs()

    # PendingProposalT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.taskId is not None:
            taskId = builder.CreateString(self.taskId)
        if self.proposerId is not None:
            proposerId = builder.CreateString(self.proposerId)
        PendingProposalStart(builder)
        if self.id is not None:
            PendingProposalAddId(builder, id)
        if self.taskId is not None:
            PendingProposalAddTaskId(builder, taskId)
        if self.proposerId is not None:
            PendingProposalAddProposerId(builder, proposerId)
        PendingProposalAddEstimatedLatencyMs(builder, self.estimatedLatencyMs)
        PendingProposalAddConfidenceScore(builder, self.confidenceScore)
        PendingProposalAddTtlMs(builder, self.ttlMs)
        PendingProposalAddCreatedAtMs(builder, self.createdAtMs)
        pendingProposal = PendingProposalEnd(builder)
        return pendingProposal
