# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Persona section (user-facing personality model)
class PersonaSection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersonaSection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPersonaSection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PersonaSectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # PersonaSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PersonaSection
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PersonaSection
    def AgentType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PersonaSection
    def Traits(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # PersonaSection
    def TraitsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PersonaSection
    def TraitsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # PersonaSection
    def Tone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PersonaSection
    def Language(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PersonaSection
    def SectionSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def PersonaSectionStart(builder):
    builder.StartObject(6)

def Start(builder):
    PersonaSectionStart(builder)

def PersonaSectionAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(0, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    PersonaSectionAddUpdatedAtMs(builder, updatedAtMs)

def PersonaSectionAddAgentType(builder, agentType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(agentType), 0)

def AddAgentType(builder, agentType):
    PersonaSectionAddAgentType(builder, agentType)

def PersonaSectionAddTraits(builder, traits):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(traits), 0)

def AddTraits(builder, traits):
    PersonaSectionAddTraits(builder, traits)

def PersonaSectionStartTraitsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTraitsVector(builder, numElems):
    return PersonaSectionStartTraitsVector(builder, numElems)

def PersonaSectionAddTone(builder, tone):
    builder.PrependUint8Slot(3, tone, 0)

def AddTone(builder, tone):
    PersonaSectionAddTone(builder, tone)

def PersonaSectionAddLanguage(builder, language):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(language), 0)

def AddLanguage(builder, language):
    PersonaSectionAddLanguage(builder, language)

def PersonaSectionAddSectionSizeBytes(builder, sectionSizeBytes):
    builder.PrependUint32Slot(5, sectionSizeBytes, 0)

def AddSectionSizeBytes(builder, sectionSizeBytes):
    PersonaSectionAddSectionSizeBytes(builder, sectionSizeBytes)

def PersonaSectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return PersonaSectionEnd(builder)

try:
    from typing import List
except:
    pass

class PersonaSectionT(object):

    # PersonaSectionT
    def __init__(self):
        self.updatedAtMs = 0  # type: int
        self.agentType = None  # type: str
        self.traits = None  # type: List[str]
        self.tone = 0  # type: int
        self.language = None  # type: str
        self.sectionSizeBytes = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        personaSection = PersonaSection()
        personaSection.Init(buf, pos)
        return cls.InitFromObj(personaSection)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, personaSection):
        x = PersonaSectionT()
        x._UnPack(personaSection)
        return x

    # PersonaSectionT
    def _UnPack(self, personaSection):
        if personaSection is None:
            return
        self.updatedAtMs = personaSection.UpdatedAtMs()
        self.agentType = personaSection.AgentType()
        if not personaSection.TraitsIsNone():
            self.traits = []
            for i in range(personaSection.TraitsLength()):
                self.traits.append(personaSection.Traits(i))
        self.tone = personaSection.Tone()
        self.language = personaSection.Language()
        self.sectionSizeBytes = personaSection.SectionSizeBytes()

    # PersonaSectionT
    def Pack(self, builder):
        if self.agentType is not None:
            agentType = builder.CreateString(self.agentType)
        if self.traits is not None:
            traitslist = []
            for i in range(len(self.traits)):
                traitslist.append(builder.CreateString(self.traits[i]))
            PersonaSectionStartTraitsVector(builder, len(self.traits))
            for i in reversed(range(len(self.traits))):
                builder.PrependUOffsetTRelative(traitslist[i])
            traits = builder.EndVector()
        if self.language is not None:
            language = builder.CreateString(self.language)
        PersonaSectionStart(builder)
        PersonaSectionAddUpdatedAtMs(builder, self.updatedAtMs)
        if self.agentType is not None:
            PersonaSectionAddAgentType(builder, agentType)
        if self.traits is not None:
            PersonaSectionAddTraits(builder, traits)
        PersonaSectionAddTone(builder, self.tone)
        if self.language is not None:
            PersonaSectionAddLanguage(builder, language)
        PersonaSectionAddSectionSizeBytes(builder, self.sectionSizeBytes)
        personaSection = PersonaSectionEnd(builder)
        return personaSection
