# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

# Privacy/PII band (ADR P10 redaction policy)
class RedactionBand(object):
    GREEN = 0
    AMBER = 1
    RED = 2
