# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Saga checkpoint (distributed transaction rollback, Garcia-Molina 1987)
class SagaCheckpoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SagaCheckpoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSagaCheckpoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SagaCheckpointBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # SagaCheckpoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SagaCheckpoint
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SagaCheckpoint
    def TaskId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SagaCheckpoint
    def Stage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SagaCheckpoint
    def PayloadHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SagaCheckpoint
    def CompensationAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SagaCheckpoint
    def CreatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def SagaCheckpointStart(builder):
    builder.StartObject(6)

def Start(builder):
    SagaCheckpointStart(builder)

def SagaCheckpointAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    SagaCheckpointAddId(builder, id)

def SagaCheckpointAddTaskId(builder, taskId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(taskId), 0)

def AddTaskId(builder, taskId):
    SagaCheckpointAddTaskId(builder, taskId)

def SagaCheckpointAddStage(builder, stage):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(stage), 0)

def AddStage(builder, stage):
    SagaCheckpointAddStage(builder, stage)

def SagaCheckpointAddPayloadHash(builder, payloadHash):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(payloadHash), 0)

def AddPayloadHash(builder, payloadHash):
    SagaCheckpointAddPayloadHash(builder, payloadHash)

def SagaCheckpointAddCompensationAction(builder, compensationAction):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(compensationAction), 0)

def AddCompensationAction(builder, compensationAction):
    SagaCheckpointAddCompensationAction(builder, compensationAction)

def SagaCheckpointAddCreatedAtMs(builder, createdAtMs):
    builder.PrependUint64Slot(5, createdAtMs, 0)

def AddCreatedAtMs(builder, createdAtMs):
    SagaCheckpointAddCreatedAtMs(builder, createdAtMs)

def SagaCheckpointEnd(builder):
    return builder.EndObject()

def End(builder):
    return SagaCheckpointEnd(builder)


class SagaCheckpointT(object):

    # SagaCheckpointT
    def __init__(self):
        self.id = None  # type: str
        self.taskId = None  # type: str
        self.stage = None  # type: str
        self.payloadHash = None  # type: str
        self.compensationAction = None  # type: str
        self.createdAtMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sagaCheckpoint = SagaCheckpoint()
        sagaCheckpoint.Init(buf, pos)
        return cls.InitFromObj(sagaCheckpoint)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sagaCheckpoint):
        x = SagaCheckpointT()
        x._UnPack(sagaCheckpoint)
        return x

    # SagaCheckpointT
    def _UnPack(self, sagaCheckpoint):
        if sagaCheckpoint is None:
            return
        self.id = sagaCheckpoint.Id()
        self.taskId = sagaCheckpoint.TaskId()
        self.stage = sagaCheckpoint.Stage()
        self.payloadHash = sagaCheckpoint.PayloadHash()
        self.compensationAction = sagaCheckpoint.CompensationAction()
        self.createdAtMs = sagaCheckpoint.CreatedAtMs()

    # SagaCheckpointT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.taskId is not None:
            taskId = builder.CreateString(self.taskId)
        if self.stage is not None:
            stage = builder.CreateString(self.stage)
        if self.payloadHash is not None:
            payloadHash = builder.CreateString(self.payloadHash)
        if self.compensationAction is not None:
            compensationAction = builder.CreateString(self.compensationAction)
        SagaCheckpointStart(builder)
        if self.id is not None:
            SagaCheckpointAddId(builder, id)
        if self.taskId is not None:
            SagaCheckpointAddTaskId(builder, taskId)
        if self.stage is not None:
            SagaCheckpointAddStage(builder, stage)
        if self.payloadHash is not None:
            SagaCheckpointAddPayloadHash(builder, payloadHash)
        if self.compensationAction is not None:
            SagaCheckpointAddCompensationAction(builder, compensationAction)
        SagaCheckpointAddCreatedAtMs(builder, self.createdAtMs)
        sagaCheckpoint = SagaCheckpointEnd(builder)
        return sagaCheckpoint
