# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Scoreboard section (performance metrics for agent selection)
# Uses zero-copy structs for hot-path MADM scoring
class ScoreboardSection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScoreboardSection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScoreboardSection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ScoreboardSectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # ScoreboardSection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScoreboardSection
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ScoreboardSection
    def AgentScores(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 32
            from k1.l4_runtime.session_state.model.AgentScore import AgentScore
            obj = AgentScore()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScoreboardSection
    def AgentScoresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScoreboardSection
    def AgentScoresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # ScoreboardSection
    def ToolScores(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 32
            from k1.l4_runtime.session_state.model.ToolScore import ToolScore
            obj = ToolScore()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ScoreboardSection
    def ToolScoresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ScoreboardSection
    def ToolScoresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ScoreboardSection
    def SectionSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ScoreboardSectionStart(builder):
    builder.StartObject(4)

def Start(builder):
    ScoreboardSectionStart(builder)

def ScoreboardSectionAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(0, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    ScoreboardSectionAddUpdatedAtMs(builder, updatedAtMs)

def ScoreboardSectionAddAgentScores(builder, agentScores):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(agentScores), 0)

def AddAgentScores(builder, agentScores):
    ScoreboardSectionAddAgentScores(builder, agentScores)

def ScoreboardSectionStartAgentScoresVector(builder, numElems):
    return builder.StartVector(32, numElems, 8)

def StartAgentScoresVector(builder, numElems):
    return ScoreboardSectionStartAgentScoresVector(builder, numElems)

def ScoreboardSectionAddToolScores(builder, toolScores):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(toolScores), 0)

def AddToolScores(builder, toolScores):
    ScoreboardSectionAddToolScores(builder, toolScores)

def ScoreboardSectionStartToolScoresVector(builder, numElems):
    return builder.StartVector(32, numElems, 8)

def StartToolScoresVector(builder, numElems):
    return ScoreboardSectionStartToolScoresVector(builder, numElems)

def ScoreboardSectionAddSectionSizeBytes(builder, sectionSizeBytes):
    builder.PrependUint32Slot(3, sectionSizeBytes, 0)

def AddSectionSizeBytes(builder, sectionSizeBytes):
    ScoreboardSectionAddSectionSizeBytes(builder, sectionSizeBytes)

def ScoreboardSectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScoreboardSectionEnd(builder)

import k1.l4_runtime.session_state.model.AgentScore
import k1.l4_runtime.session_state.model.ToolScore
try:
    from typing import List
except:
    pass

class ScoreboardSectionT(object):

    # ScoreboardSectionT
    def __init__(self):
        self.updatedAtMs = 0  # type: int
        self.agentScores = None  # type: List[k1.l4_runtime.session_state.model.AgentScore.AgentScoreT]
        self.toolScores = None  # type: List[k1.l4_runtime.session_state.model.ToolScore.ToolScoreT]
        self.sectionSizeBytes = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        scoreboardSection = ScoreboardSection()
        scoreboardSection.Init(buf, pos)
        return cls.InitFromObj(scoreboardSection)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, scoreboardSection):
        x = ScoreboardSectionT()
        x._UnPack(scoreboardSection)
        return x

    # ScoreboardSectionT
    def _UnPack(self, scoreboardSection):
        if scoreboardSection is None:
            return
        self.updatedAtMs = scoreboardSection.UpdatedAtMs()
        if not scoreboardSection.AgentScoresIsNone():
            self.agentScores = []
            for i in range(scoreboardSection.AgentScoresLength()):
                if scoreboardSection.AgentScores(i) is None:
                    self.agentScores.append(None)
                else:
                    agentScore_ = k1.l4_runtime.session_state.model.AgentScore.AgentScoreT.InitFromObj(scoreboardSection.AgentScores(i))
                    self.agentScores.append(agentScore_)
        if not scoreboardSection.ToolScoresIsNone():
            self.toolScores = []
            for i in range(scoreboardSection.ToolScoresLength()):
                if scoreboardSection.ToolScores(i) is None:
                    self.toolScores.append(None)
                else:
                    toolScore_ = k1.l4_runtime.session_state.model.ToolScore.ToolScoreT.InitFromObj(scoreboardSection.ToolScores(i))
                    self.toolScores.append(toolScore_)
        self.sectionSizeBytes = scoreboardSection.SectionSizeBytes()

    # ScoreboardSectionT
    def Pack(self, builder):
        if self.agentScores is not None:
            ScoreboardSectionStartAgentScoresVector(builder, len(self.agentScores))
            for i in reversed(range(len(self.agentScores))):
                self.agentScores[i].Pack(builder)
            agentScores = builder.EndVector()
        if self.toolScores is not None:
            ScoreboardSectionStartToolScoresVector(builder, len(self.toolScores))
            for i in reversed(range(len(self.toolScores))):
                self.toolScores[i].Pack(builder)
            toolScores = builder.EndVector()
        ScoreboardSectionStart(builder)
        ScoreboardSectionAddUpdatedAtMs(builder, self.updatedAtMs)
        if self.agentScores is not None:
            ScoreboardSectionAddAgentScores(builder, agentScores)
        if self.toolScores is not None:
            ScoreboardSectionAddToolScores(builder, toolScores)
        ScoreboardSectionAddSectionSizeBytes(builder, self.sectionSizeBytes)
        scoreboardSection = ScoreboardSectionEnd(builder)
        return scoreboardSection
