# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

# Score basis (selection algorithm used)
class ScoreBasis(object):
    UNKNOWN = 0
    MADM_6FACTOR = 1
    BANDIT_UCB = 2
    HEURISTIC = 3
    THERMAL = 4
