# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Top-level SessionState (production-ready, delta-efficient, WAL-friendly)
#
# Delta protocol (ADR-0038b):
# - change_mask bits 0..5 → {beliefs, scoreboard, control, persona, multimodal, meta}
# - Deltas carry only changed sections; receiver merges by seq_no (idempotent)
# - Blob lifecycles handled by K0 Bridge (250ms cadence, hash-addressed immutables)
#
# Performance budgets:
# - Serialization: <1ms P95 (target: 0.5ms typical)
# - Deserialization: <1ms P95 (zero-copy reads)
# - Delta merge: <10ms P95
# - Memory footprint: <10MB per session
#
# Eviction priorities (3-tier cascade):
# - Tier 1: beliefs (least recent user_facts)
# - Tier 2: multimodal (oldest blob references)
# - Tier 3: scoreboard (last resort, keep control)
class SessionState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SessionState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSessionState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SessionStateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # SessionState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SessionState
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SessionState
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SessionState
    def TraceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SessionState
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # SessionState
    def SeqNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SessionState
    def ChangeMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SessionState
    def TotalSizeBytes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SessionState
    def Beliefs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.BeliefsSection import BeliefsSection
            obj = BeliefsSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SessionState
    def Scoreboard(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.ScoreboardSection import ScoreboardSection
            obj = ScoreboardSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SessionState
    def Control(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.ControlSection import ControlSection
            obj = ControlSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SessionState
    def Persona(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.PersonaSection import PersonaSection
            obj = PersonaSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SessionState
    def Multimodal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.MultimodalSection import MultimodalSection
            obj = MultimodalSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SessionState
    def Meta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from k1.l4_runtime.session_state.model.MetaSection import MetaSection
            obj = MetaSection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SessionStateStart(builder):
    builder.StartObject(13)

def Start(builder):
    SessionStateStart(builder)

def SessionStateAddSessionId(builder, sessionId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sessionId), 0)

def AddSessionId(builder, sessionId):
    SessionStateAddSessionId(builder, sessionId)

def SessionStateAddUserId(builder, userId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(userId), 0)

def AddUserId(builder, userId):
    SessionStateAddUserId(builder, userId)

def SessionStateAddTraceId(builder, traceId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)

def AddTraceId(builder, traceId):
    SessionStateAddTraceId(builder, traceId)

def SessionStateAddVersion(builder, version):
    builder.PrependUint16Slot(3, version, 1)

def AddVersion(builder, version):
    SessionStateAddVersion(builder, version)

def SessionStateAddSeqNo(builder, seqNo):
    builder.PrependUint64Slot(4, seqNo, 0)

def AddSeqNo(builder, seqNo):
    SessionStateAddSeqNo(builder, seqNo)

def SessionStateAddChangeMask(builder, changeMask):
    builder.PrependUint64Slot(5, changeMask, 0)

def AddChangeMask(builder, changeMask):
    SessionStateAddChangeMask(builder, changeMask)

def SessionStateAddTotalSizeBytes(builder, totalSizeBytes):
    builder.PrependUint32Slot(6, totalSizeBytes, 0)

def AddTotalSizeBytes(builder, totalSizeBytes):
    SessionStateAddTotalSizeBytes(builder, totalSizeBytes)

def SessionStateAddBeliefs(builder, beliefs):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(beliefs), 0)

def AddBeliefs(builder, beliefs):
    SessionStateAddBeliefs(builder, beliefs)

def SessionStateAddScoreboard(builder, scoreboard):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(scoreboard), 0)

def AddScoreboard(builder, scoreboard):
    SessionStateAddScoreboard(builder, scoreboard)

def SessionStateAddControl(builder, control):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(control), 0)

def AddControl(builder, control):
    SessionStateAddControl(builder, control)

def SessionStateAddPersona(builder, persona):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(persona), 0)

def AddPersona(builder, persona):
    SessionStateAddPersona(builder, persona)

def SessionStateAddMultimodal(builder, multimodal):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(multimodal), 0)

def AddMultimodal(builder, multimodal):
    SessionStateAddMultimodal(builder, multimodal)

def SessionStateAddMeta(builder, meta):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(meta), 0)

def AddMeta(builder, meta):
    SessionStateAddMeta(builder, meta)

def SessionStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SessionStateEnd(builder)

import k1.l4_runtime.session_state.model.BeliefsSection
import k1.l4_runtime.session_state.model.ControlSection
import k1.l4_runtime.session_state.model.MetaSection
import k1.l4_runtime.session_state.model.MultimodalSection
import k1.l4_runtime.session_state.model.PersonaSection
import k1.l4_runtime.session_state.model.ScoreboardSection
try:
    from typing import Optional
except:
    pass

class SessionStateT(object):

    # SessionStateT
    def __init__(self):
        self.sessionId = None  # type: str
        self.userId = None  # type: str
        self.traceId = None  # type: str
        self.version = 1  # type: int
        self.seqNo = 0  # type: int
        self.changeMask = 0  # type: int
        self.totalSizeBytes = 0  # type: int
        self.beliefs = None  # type: Optional[k1.l4_runtime.session_state.model.BeliefsSection.BeliefsSectionT]
        self.scoreboard = None  # type: Optional[k1.l4_runtime.session_state.model.ScoreboardSection.ScoreboardSectionT]
        self.control = None  # type: Optional[k1.l4_runtime.session_state.model.ControlSection.ControlSectionT]
        self.persona = None  # type: Optional[k1.l4_runtime.session_state.model.PersonaSection.PersonaSectionT]
        self.multimodal = None  # type: Optional[k1.l4_runtime.session_state.model.MultimodalSection.MultimodalSectionT]
        self.meta = None  # type: Optional[k1.l4_runtime.session_state.model.MetaSection.MetaSectionT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sessionState = SessionState()
        sessionState.Init(buf, pos)
        return cls.InitFromObj(sessionState)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sessionState):
        x = SessionStateT()
        x._UnPack(sessionState)
        return x

    # SessionStateT
    def _UnPack(self, sessionState):
        if sessionState is None:
            return
        self.sessionId = sessionState.SessionId()
        self.userId = sessionState.UserId()
        self.traceId = sessionState.TraceId()
        self.version = sessionState.Version()
        self.seqNo = sessionState.SeqNo()
        self.changeMask = sessionState.ChangeMask()
        self.totalSizeBytes = sessionState.TotalSizeBytes()
        if sessionState.Beliefs() is not None:
            self.beliefs = k1.l4_runtime.session_state.model.BeliefsSection.BeliefsSectionT.InitFromObj(sessionState.Beliefs())
        if sessionState.Scoreboard() is not None:
            self.scoreboard = k1.l4_runtime.session_state.model.ScoreboardSection.ScoreboardSectionT.InitFromObj(sessionState.Scoreboard())
        if sessionState.Control() is not None:
            self.control = k1.l4_runtime.session_state.model.ControlSection.ControlSectionT.InitFromObj(sessionState.Control())
        if sessionState.Persona() is not None:
            self.persona = k1.l4_runtime.session_state.model.PersonaSection.PersonaSectionT.InitFromObj(sessionState.Persona())
        if sessionState.Multimodal() is not None:
            self.multimodal = k1.l4_runtime.session_state.model.MultimodalSection.MultimodalSectionT.InitFromObj(sessionState.Multimodal())
        if sessionState.Meta() is not None:
            self.meta = k1.l4_runtime.session_state.model.MetaSection.MetaSectionT.InitFromObj(sessionState.Meta())

    # SessionStateT
    def Pack(self, builder):
        if self.sessionId is not None:
            sessionId = builder.CreateString(self.sessionId)
        if self.userId is not None:
            userId = builder.CreateString(self.userId)
        if self.traceId is not None:
            traceId = builder.CreateString(self.traceId)
        if self.beliefs is not None:
            beliefs = self.beliefs.Pack(builder)
        if self.scoreboard is not None:
            scoreboard = self.scoreboard.Pack(builder)
        if self.control is not None:
            control = self.control.Pack(builder)
        if self.persona is not None:
            persona = self.persona.Pack(builder)
        if self.multimodal is not None:
            multimodal = self.multimodal.Pack(builder)
        if self.meta is not None:
            meta = self.meta.Pack(builder)
        SessionStateStart(builder)
        if self.sessionId is not None:
            SessionStateAddSessionId(builder, sessionId)
        if self.userId is not None:
            SessionStateAddUserId(builder, userId)
        if self.traceId is not None:
            SessionStateAddTraceId(builder, traceId)
        SessionStateAddVersion(builder, self.version)
        SessionStateAddSeqNo(builder, self.seqNo)
        SessionStateAddChangeMask(builder, self.changeMask)
        SessionStateAddTotalSizeBytes(builder, self.totalSizeBytes)
        if self.beliefs is not None:
            SessionStateAddBeliefs(builder, beliefs)
        if self.scoreboard is not None:
            SessionStateAddScoreboard(builder, scoreboard)
        if self.control is not None:
            SessionStateAddControl(builder, control)
        if self.persona is not None:
            SessionStateAddPersona(builder, persona)
        if self.multimodal is not None:
            SessionStateAddMultimodal(builder, multimodal)
        if self.meta is not None:
            SessionStateAddMeta(builder, meta)
        sessionState = SessionStateEnd(builder)
        return sessionState
