# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Spatial context (location-based session info)
class SpatialContext(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpatialContext()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpatialContext(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SpatialContextBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # SpatialContext
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpatialContext
    def Room(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialContext
    def CoarseLocation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialContext
    def Latitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SpatialContext
    def Longitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SpatialContext
    def AccuracyMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SpatialContextStart(builder):
    builder.StartObject(5)

def Start(builder):
    SpatialContextStart(builder)

def SpatialContextAddRoom(builder, room):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(room), 0)

def AddRoom(builder, room):
    SpatialContextAddRoom(builder, room)

def SpatialContextAddCoarseLocation(builder, coarseLocation):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(coarseLocation), 0)

def AddCoarseLocation(builder, coarseLocation):
    SpatialContextAddCoarseLocation(builder, coarseLocation)

def SpatialContextAddLatitude(builder, latitude):
    builder.PrependFloat64Slot(2, latitude, 0.0)

def AddLatitude(builder, latitude):
    SpatialContextAddLatitude(builder, latitude)

def SpatialContextAddLongitude(builder, longitude):
    builder.PrependFloat64Slot(3, longitude, 0.0)

def AddLongitude(builder, longitude):
    SpatialContextAddLongitude(builder, longitude)

def SpatialContextAddAccuracyMeters(builder, accuracyMeters):
    builder.PrependFloat32Slot(4, accuracyMeters, 0.0)

def AddAccuracyMeters(builder, accuracyMeters):
    SpatialContextAddAccuracyMeters(builder, accuracyMeters)

def SpatialContextEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpatialContextEnd(builder)


class SpatialContextT(object):

    # SpatialContextT
    def __init__(self):
        self.room = None  # type: str
        self.coarseLocation = None  # type: str
        self.latitude = 0.0  # type: float
        self.longitude = 0.0  # type: float
        self.accuracyMeters = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        spatialContext = SpatialContext()
        spatialContext.Init(buf, pos)
        return cls.InitFromObj(spatialContext)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, spatialContext):
        x = SpatialContextT()
        x._UnPack(spatialContext)
        return x

    # SpatialContextT
    def _UnPack(self, spatialContext):
        if spatialContext is None:
            return
        self.room = spatialContext.Room()
        self.coarseLocation = spatialContext.CoarseLocation()
        self.latitude = spatialContext.Latitude()
        self.longitude = spatialContext.Longitude()
        self.accuracyMeters = spatialContext.AccuracyMeters()

    # SpatialContextT
    def Pack(self, builder):
        if self.room is not None:
            room = builder.CreateString(self.room)
        if self.coarseLocation is not None:
            coarseLocation = builder.CreateString(self.coarseLocation)
        SpatialContextStart(builder)
        if self.room is not None:
            SpatialContextAddRoom(builder, room)
        if self.coarseLocation is not None:
            SpatialContextAddCoarseLocation(builder, coarseLocation)
        SpatialContextAddLatitude(builder, self.latitude)
        SpatialContextAddLongitude(builder, self.longitude)
        SpatialContextAddAccuracyMeters(builder, self.accuracyMeters)
        spatialContext = SpatialContextEnd(builder)
        return spatialContext
