# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

# Task/proposal status
class TaskStatus(object):
    PENDING = 0
    NEGOTIATING = 1
    EXECUTING = 2
    COMPLETED = 3
    FAILED = 4
    CANCELLED = 5
