# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Temporal context (time-based session info)
class TemporalContext(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TemporalContext()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTemporalContext(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TemporalContextBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # TemporalContext
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TemporalContext
    def NowMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TemporalContext
    def Timezone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TemporalContext
    def SessionStartMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TemporalContextStart(builder):
    builder.StartObject(3)

def Start(builder):
    TemporalContextStart(builder)

def TemporalContextAddNowMs(builder, nowMs):
    builder.PrependUint64Slot(0, nowMs, 0)

def AddNowMs(builder, nowMs):
    TemporalContextAddNowMs(builder, nowMs)

def TemporalContextAddTimezone(builder, timezone):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(timezone), 0)

def AddTimezone(builder, timezone):
    TemporalContextAddTimezone(builder, timezone)

def TemporalContextAddSessionStartMs(builder, sessionStartMs):
    builder.PrependUint64Slot(2, sessionStartMs, 0)

def AddSessionStartMs(builder, sessionStartMs):
    TemporalContextAddSessionStartMs(builder, sessionStartMs)

def TemporalContextEnd(builder):
    return builder.EndObject()

def End(builder):
    return TemporalContextEnd(builder)


class TemporalContextT(object):

    # TemporalContextT
    def __init__(self):
        self.nowMs = 0  # type: int
        self.timezone = None  # type: str
        self.sessionStartMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        temporalContext = TemporalContext()
        temporalContext.Init(buf, pos)
        return cls.InitFromObj(temporalContext)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, temporalContext):
        x = TemporalContextT()
        x._UnPack(temporalContext)
        return x

    # TemporalContextT
    def _UnPack(self, temporalContext):
        if temporalContext is None:
            return
        self.nowMs = temporalContext.NowMs()
        self.timezone = temporalContext.Timezone()
        self.sessionStartMs = temporalContext.SessionStartMs()

    # TemporalContextT
    def Pack(self, builder):
        if self.timezone is not None:
            timezone = builder.CreateString(self.timezone)
        TemporalContextStart(builder)
        TemporalContextAddNowMs(builder, self.nowMs)
        if self.timezone is not None:
            TemporalContextAddTimezone(builder, timezone)
        TemporalContextAddSessionStartMs(builder, self.sessionStartMs)
        temporalContext = TemporalContextEnd(builder)
        return temporalContext
