# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

# Persona tone (conversation style)
class Tone(object):
    DEFAULT = 0
    FORMAL = 1
    CASUAL = 2
    EMPATHETIC = 3
    PROFESSIONAL = 4
