# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Tool score (tool success rate tracking, zero-copy struct)
class ToolScore(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # ToolScore
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ToolScore
    def ToolId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ToolScore
    def Score(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # ToolScore
    def Confidence(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ToolScore
    def Basis(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # ToolScore
    def CallsTotal(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(14))
    # ToolScore
    def CallsSuccess(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # ToolScore
    def AvgLatencyMs(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # ToolScore
    def LastUsedMs(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))

def CreateToolScore(builder, toolId, score, confidence, basis, callsTotal, callsSuccess, avgLatencyMs, lastUsedMs):
    builder.Prep(8, 32)
    builder.PrependUint64(lastUsedMs)
    builder.PrependFloat32(avgLatencyMs)
    builder.Pad(2)
    builder.PrependUint16(callsSuccess)
    builder.PrependUint16(callsTotal)
    builder.Pad(1)
    builder.PrependUint8(basis)
    builder.PrependFloat32(confidence)
    builder.PrependFloat32(score)
    builder.PrependUint32(toolId)
    return builder.Offset()


class ToolScoreT(object):

    # ToolScoreT
    def __init__(self):
        self.toolId = 0  # type: int
        self.score = 0.0  # type: float
        self.confidence = 0.0  # type: float
        self.basis = 0  # type: int
        self.callsTotal = 0  # type: int
        self.callsSuccess = 0  # type: int
        self.avgLatencyMs = 0.0  # type: float
        self.lastUsedMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        toolScore = ToolScore()
        toolScore.Init(buf, pos)
        return cls.InitFromObj(toolScore)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, toolScore):
        x = ToolScoreT()
        x._UnPack(toolScore)
        return x

    # ToolScoreT
    def _UnPack(self, toolScore):
        if toolScore is None:
            return
        self.toolId = toolScore.ToolId()
        self.score = toolScore.Score()
        self.confidence = toolScore.Confidence()
        self.basis = toolScore.Basis()
        self.callsTotal = toolScore.CallsTotal()
        self.callsSuccess = toolScore.CallsSuccess()
        self.avgLatencyMs = toolScore.AvgLatencyMs()
        self.lastUsedMs = toolScore.LastUsedMs()

    # ToolScoreT
    def Pack(self, builder):
        return CreateToolScore(builder, self.toolId, self.score, self.confidence, self.basis, self.callsTotal, self.callsSuccess, self.avgLatencyMs, self.lastUsedMs)
