# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# User fact (single belief with provenance and privacy band)
class UserFact(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserFact()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserFact(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UserFactBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # UserFact
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserFact
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserFact
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserFact
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserFact
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # UserFact
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserFact
    def TurnId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # UserFact
    def CreatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # UserFact
    def UpdatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # UserFact
    def LastAccessedMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # UserFact
    def PiiBand(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def UserFactStart(builder):
    builder.StartObject(10)

def Start(builder):
    UserFactStart(builder)

def UserFactAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    UserFactAddId(builder, id)

def UserFactAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    UserFactAddKey(builder, key)

def UserFactAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    UserFactAddValue(builder, value)

def UserFactAddConfidence(builder, confidence):
    builder.PrependFloat32Slot(3, confidence, 1.0)

def AddConfidence(builder, confidence):
    UserFactAddConfidence(builder, confidence)

def UserFactAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    UserFactAddSource(builder, source)

def UserFactAddTurnId(builder, turnId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(turnId), 0)

def AddTurnId(builder, turnId):
    UserFactAddTurnId(builder, turnId)

def UserFactAddCreatedAtMs(builder, createdAtMs):
    builder.PrependUint64Slot(6, createdAtMs, 0)

def AddCreatedAtMs(builder, createdAtMs):
    UserFactAddCreatedAtMs(builder, createdAtMs)

def UserFactAddUpdatedAtMs(builder, updatedAtMs):
    builder.PrependUint64Slot(7, updatedAtMs, 0)

def AddUpdatedAtMs(builder, updatedAtMs):
    UserFactAddUpdatedAtMs(builder, updatedAtMs)

def UserFactAddLastAccessedMs(builder, lastAccessedMs):
    builder.PrependUint64Slot(8, lastAccessedMs, 0)

def AddLastAccessedMs(builder, lastAccessedMs):
    UserFactAddLastAccessedMs(builder, lastAccessedMs)

def UserFactAddPiiBand(builder, piiBand):
    builder.PrependUint8Slot(9, piiBand, 0)

def AddPiiBand(builder, piiBand):
    UserFactAddPiiBand(builder, piiBand)

def UserFactEnd(builder):
    return builder.EndObject()

def End(builder):
    return UserFactEnd(builder)


class UserFactT(object):

    # UserFactT
    def __init__(self):
        self.id = None  # type: str
        self.key = None  # type: str
        self.value = None  # type: str
        self.confidence = 1.0  # type: float
        self.source = None  # type: str
        self.turnId = None  # type: str
        self.createdAtMs = 0  # type: int
        self.updatedAtMs = 0  # type: int
        self.lastAccessedMs = 0  # type: int
        self.piiBand = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        userFact = UserFact()
        userFact.Init(buf, pos)
        return cls.InitFromObj(userFact)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, userFact):
        x = UserFactT()
        x._UnPack(userFact)
        return x

    # UserFactT
    def _UnPack(self, userFact):
        if userFact is None:
            return
        self.id = userFact.Id()
        self.key = userFact.Key()
        self.value = userFact.Value()
        self.confidence = userFact.Confidence()
        self.source = userFact.Source()
        self.turnId = userFact.TurnId()
        self.createdAtMs = userFact.CreatedAtMs()
        self.updatedAtMs = userFact.UpdatedAtMs()
        self.lastAccessedMs = userFact.LastAccessedMs()
        self.piiBand = userFact.PiiBand()

    # UserFactT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.key is not None:
            key = builder.CreateString(self.key)
        if self.value is not None:
            value = builder.CreateString(self.value)
        if self.source is not None:
            source = builder.CreateString(self.source)
        if self.turnId is not None:
            turnId = builder.CreateString(self.turnId)
        UserFactStart(builder)
        if self.id is not None:
            UserFactAddId(builder, id)
        if self.key is not None:
            UserFactAddKey(builder, key)
        if self.value is not None:
            UserFactAddValue(builder, value)
        UserFactAddConfidence(builder, self.confidence)
        if self.source is not None:
            UserFactAddSource(builder, source)
        if self.turnId is not None:
            UserFactAddTurnId(builder, turnId)
        UserFactAddCreatedAtMs(builder, self.createdAtMs)
        UserFactAddUpdatedAtMs(builder, self.updatedAtMs)
        UserFactAddLastAccessedMs(builder, self.lastAccessedMs)
        UserFactAddPiiBand(builder, self.piiBand)
        userFact = UserFactEnd(builder)
        return userFact
