# automatically generated by the FlatBuffers compiler, do not modify

# namespace: model

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# World knowledge (general facts, relations)
class WorldKnowledge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldKnowledge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldKnowledge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WorldKnowledgeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x53\x53\x4E", size_prefixed=size_prefixed)

    # WorldKnowledge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldKnowledge
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldKnowledge
    def Entity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldKnowledge
    def Relation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldKnowledge
    def Target(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldKnowledge
    def Confidence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # WorldKnowledge
    def Hash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldKnowledge
    def CreatedAtMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def WorldKnowledgeStart(builder):
    builder.StartObject(7)

def Start(builder):
    WorldKnowledgeStart(builder)

def WorldKnowledgeAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    WorldKnowledgeAddId(builder, id)

def WorldKnowledgeAddEntity(builder, entity):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(entity), 0)

def AddEntity(builder, entity):
    WorldKnowledgeAddEntity(builder, entity)

def WorldKnowledgeAddRelation(builder, relation):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(relation), 0)

def AddRelation(builder, relation):
    WorldKnowledgeAddRelation(builder, relation)

def WorldKnowledgeAddTarget(builder, target):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder, target):
    WorldKnowledgeAddTarget(builder, target)

def WorldKnowledgeAddConfidence(builder, confidence):
    builder.PrependFloat32Slot(4, confidence, 1.0)

def AddConfidence(builder, confidence):
    WorldKnowledgeAddConfidence(builder, confidence)

def WorldKnowledgeAddHash(builder, hash):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(hash), 0)

def AddHash(builder, hash):
    WorldKnowledgeAddHash(builder, hash)

def WorldKnowledgeAddCreatedAtMs(builder, createdAtMs):
    builder.PrependUint64Slot(6, createdAtMs, 0)

def AddCreatedAtMs(builder, createdAtMs):
    WorldKnowledgeAddCreatedAtMs(builder, createdAtMs)

def WorldKnowledgeEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldKnowledgeEnd(builder)


class WorldKnowledgeT(object):

    # WorldKnowledgeT
    def __init__(self):
        self.id = None  # type: str
        self.entity = None  # type: str
        self.relation = None  # type: str
        self.target = None  # type: str
        self.confidence = 1.0  # type: float
        self.hash = None  # type: str
        self.createdAtMs = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        worldKnowledge = WorldKnowledge()
        worldKnowledge.Init(buf, pos)
        return cls.InitFromObj(worldKnowledge)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, worldKnowledge):
        x = WorldKnowledgeT()
        x._UnPack(worldKnowledge)
        return x

    # WorldKnowledgeT
    def _UnPack(self, worldKnowledge):
        if worldKnowledge is None:
            return
        self.id = worldKnowledge.Id()
        self.entity = worldKnowledge.Entity()
        self.relation = worldKnowledge.Relation()
        self.target = worldKnowledge.Target()
        self.confidence = worldKnowledge.Confidence()
        self.hash = worldKnowledge.Hash()
        self.createdAtMs = worldKnowledge.CreatedAtMs()

    # WorldKnowledgeT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.entity is not None:
            entity = builder.CreateString(self.entity)
        if self.relation is not None:
            relation = builder.CreateString(self.relation)
        if self.target is not None:
            target = builder.CreateString(self.target)
        if self.hash is not None:
            hash = builder.CreateString(self.hash)
        WorldKnowledgeStart(builder)
        if self.id is not None:
            WorldKnowledgeAddId(builder, id)
        if self.entity is not None:
            WorldKnowledgeAddEntity(builder, entity)
        if self.relation is not None:
            WorldKnowledgeAddRelation(builder, relation)
        if self.target is not None:
            WorldKnowledgeAddTarget(builder, target)
        WorldKnowledgeAddConfidence(builder, self.confidence)
        if self.hash is not None:
            WorldKnowledgeAddHash(builder, hash)
        WorldKnowledgeAddCreatedAtMs(builder, self.createdAtMs)
        worldKnowledge = WorldKnowledgeEnd(builder)
        return worldKnowledge
