# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: manifests/k0.proactive.signal.v1.yaml

"""Generated SSE emitter for the ``k0.proactive.signal.v1`` contract.

Producer side (K0). Real K0 emit goes through the K0 SSE replay buffer
(see :mod:`k0.sse.replay_buffer`, MS-3d Epic 3d.3) before fanning out
to live SSE subscribers. The :meth:`K0ProactiveSignalV1Client.emit`
method is the typed seam K0 emitters call once the body is built.

In Epic 3d.1 the runtime binding is intentionally left for Epic 3d.3
to fill in: until then, ``emit`` raises :class:`NotImplementedError`
so accidental cross-kernel calls fail loudly rather than silently
dropping events.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from bridge._generated.k0.models.k0_proactive_signal_v1 import (
    K0ProactiveSignalV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from bridge.runtime import BridgeRuntime


class K0ProactiveSignalV1Client:
    """Generated K0-side emitter for ``k0.proactive.signal.v1``.

    Direct construction outside the runtime is forbidden by the
    ``manifest_implementation_bound`` CI gate. The replay-buffer wiring
    lands in MS-3d Epic 3d.3.
    """

    __transport__ = "sse"
    __topic__ = "k0.proactive.signal.v1"
    __schema_uri__ = "bridge://contracts/schemas/k0.proactive.signal.v1.json"

    def __init__(self, runtime: "BridgeRuntime") -> None:
        self._runtime = runtime

    async def emit(self, payload: K0ProactiveSignalV1) -> Any:
        """Emit ``payload`` on the ``k0.proactive.signal.v1`` SSE stream.

        K0-only call site. Wiring to the replay buffer + live fanout
        ships in MS-3d Epic 3d.3.
        """
        emitter = getattr(self._runtime, "_sse_emitter", None)
        if emitter is None:
            raise NotImplementedError(
                "K0ProactiveSignalV1Client.emit: K0 SSE emitter not bound "
                "(MS-3d Epic 3d.3)."
            )
        return await emitter.emit(
            topic=self.__topic__,
            schema_uri=self.__schema_uri__,
            payload=payload,
        )
