# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/p03.gap.detected.v1.yaml

"""Generated SSE emitter for the ``p03.gap.detected.v1`` contract.

Producer side (K0). Real K0 emit goes through the K0 SSE replay buffer
(see :mod:`k0.sse.replay_buffer`, MS-3d Epic 3d.3) before fanning out
to live SSE subscribers. The :meth:`P03GapDetectedV1Client.emit`
method is the typed seam K0 emitters call once the body is built.

In Epic 3d.1 the runtime binding is intentionally left for Epic 3d.3
to fill in: until then, ``emit`` raises :class:`NotImplementedError`
so accidental cross-kernel calls fail loudly rather than silently
dropping events.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from bridge._generated.k0.models.p03_gap_detected_v1 import (
    P03GapDetectedV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from bridge.runtime import BridgeRuntime


class P03GapDetectedV1Client:
    """Generated K0-side emitter for ``p03.gap.detected.v1``.

    Direct construction outside the runtime is forbidden by the
    ``manifest_implementation_bound`` CI gate. The replay-buffer wiring
    lands in MS-3d Epic 3d.3.
    """

    __transport__ = "sse"
    __topic__ = "p03.gap.detected.v1"
    __schema_uri__ = "bridge://contracts/schemas/p03.gap.detected.v1.json"

    def __init__(self, runtime: "BridgeRuntime") -> None:
        self._runtime = runtime

    async def emit(self, payload: P03GapDetectedV1) -> Any:
        """Emit ``payload`` on the ``p03.gap.detected.v1`` SSE stream.

        K0-only call site. Wiring to the replay buffer + live fanout
        ships in MS-3d Epic 3d.3.
        """
        emitter = getattr(self._runtime, "_sse_emitter", None)
        if emitter is None:
            raise NotImplementedError(
                "P03GapDetectedV1Client.emit: K0 SSE emitter not bound "
                "(MS-3d Epic 3d.3)."
            )
        return await emitter.emit(
            topic=self.__topic__,
            schema_uri=self.__schema_uri__,
            payload=payload,
        )
