# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k1: 5 topic(s)

"""Auto-generated client stub for kernel ``k1``."""

from __future__ import annotations

from typing import Any


class K1BridgeClient:
    """Generated thin client. Real transport binding lands in MS-3a."""

    __transport__ = "in_process"

    def __init__(self, runtime: Any) -> None:
        self._runtime = runtime

