# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: k1: 5 topic(s)

"""Auto-generated client stub for kernel ``k1``."""

from __future__ import annotations

from typing import Any


class K1BridgeClient:
    """Generated thin client. Real transport binding lands in MS-3a."""

    __transport__ = "in_process"

    def __init__(self, runtime: Any) -> None:
        self._runtime = runtime

