# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k1: 5 topic(s)

"""Auto-generated handler registry for kernel ``k1``."""

from __future__ import annotations

from typing import Any, Callable


def register_handlers(runtime: Any, impl: Any) -> None:
    """Wire ``impl`` methods into ``runtime`` for kernel ``k1``.

    Compile-time check: every topic listed in the manifests for this kernel
    must have a corresponding ``impl.<method>`` callable.
    """
    # No topics yet for this kernel.
    return
