# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: k1: 5 topic(s)

"""Auto-generated handler registry for kernel ``k1``."""

from __future__ import annotations

from typing import Any, Callable


def register_handlers(runtime: Any, impl: Any) -> None:
    """Wire ``impl`` methods into ``runtime`` for kernel ``k1``.

    Compile-time check: every topic listed in the manifests for this kernel
    must have a corresponding ``impl.<method>`` callable.
    """
    # No topics yet for this kernel.
    return
