# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k1: 5 topic(s)

"""Auto-generated package index for kernel ``k1``.

Lists every contract topic routed to / from this kernel.
"""

from __future__ import annotations

TOPICS: tuple[str, ...] = (
    "curiosity.intent.v1",
    "k0.learning.advisory.v1",
    "k0.proactive.signal.v1",
    "p03.complete.v1",
    "p03.gap.detected.v1",
)
