# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: k1: 5 topic(s)

"""Auto-generated port protocol for kernel ``k1``."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IK1BridgePort(Protocol):
    """Generated facade. Methods are added once contracts ship payloads."""

    # No active contracts route through this port yet (MS-2.5 placeholder).
    pass
