# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 9f14df579b56fd33a0ab4d0f16f05855a317ef13bfb2bea705d1ab001b55d9a0
# source manifest: k1: 5 topic(s)

"""Auto-generated port protocol for kernel ``k1``."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IK1BridgePort(Protocol):
    """Generated facade. Methods are added once contracts ship payloads."""

    # No active contracts route through this port yet (MS-2.5 placeholder).
    pass
