"""
scripts.codegen_envelope -- Generate FlatBuffers Python bindings from schema.fbs.

Usage:
    python scripts/codegen_envelope.py

Requires:
    flatc >= 1.12.0  (FlatBuffers compiler)

Workflow:
    1. Runs ``flatc --python`` into a temp directory.
    2. Copies the generated BusEnvelope.py to k1/bus/envelope/_fb_generated.py
       with a header comment and an extra ``PayloadBytes()`` convenience method.
    3. Optionally runs ``flatc --rust`` for future Rust crate codegen.

The _fb_generated.py module is the ONLY import target for envelope.py.
The nested generated/ directory is kept for reference but NOT imported.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SCHEMA = _ROOT / "k1" / "bus" / "envelope" / "schema.fbs"
_GENERATED_DIR = _ROOT / "k1" / "bus" / "envelope" / "generated"
_FLAT_TARGET = _ROOT / "k1" / "bus" / "envelope" / "_fb_generated.py"

# Header prepended to the flattened copy
_HEADER = """\
# -- DO NOT EDIT -- Auto-generated by flatc from schema.fbs
# Re-generate: python scripts/codegen_envelope.py
#
# Source schema: k1/bus/envelope/schema.fbs
# Flattened to this location for clean Python imports.
#
# namespace: k1.bus.envelope
"""

# Extra method injected into the BusEnvelope class for direct payload access
_PAYLOAD_BYTES_METHOD = '''
    # -- Direct buffer access for zero-copy payload reads --

    def PayloadBytes(self) -> bytes:
        """Return payload as bytes via direct buffer slice (no per-byte calls)."""
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o == 0:
            return b""
        a = self._tab.Vector(o)
        length = self._tab.VectorLen(o)
        return bytes(self._tab.Bytes[a : a + length])
'''


def _run_flatc_python() -> Path:
    """Run flatc --python and return path to generated BusEnvelope.py."""
    _GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    cmd = [
        "flatc",
        "--python",
        "-o",
        str(_GENERATED_DIR),
        str(_SCHEMA),
    ]
    print(f"[codegen] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        print(f"[codegen] flatc failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)

    # flatc places output under namespace dirs: generated/k1/bus/envelope/BusEnvelope.py
    generated_file = _GENERATED_DIR / "k1" / "bus" / "envelope" / "BusEnvelope.py"
    if not generated_file.exists():
        print(f"[codegen] Expected file not found: {generated_file}", file=sys.stderr)
        sys.exit(1)
    return generated_file


def _flatten(generated_file: Path) -> None:
    """Copy generated file to flat location with header and extra methods."""
    content = generated_file.read_text(encoding="utf-8")

    # Inject PayloadBytes() method before the builder functions
    marker = "def BusEnvelopeStart"
    if marker in content:
        # Insert just before the builder functions, after the class body
        # Find the last method in the class (PayloadIsNone)
        insert_point = content.rfind("        return o == 0")
        if insert_point != -1:
            # Find end of that line
            end_of_line = content.index("\n", insert_point) + 1
            content = content[:end_of_line] + _PAYLOAD_BYTES_METHOD + "\n" + content[end_of_line:]

    full_content = _HEADER + "\n" + content
    _FLAT_TARGET.write_text(full_content, encoding="utf-8")
    print(f"[codegen] Flattened to: {_FLAT_TARGET}")


def _run_flatc_rust() -> None:
    """Run flatc --rust (optional, for future Rust crate)."""
    rust_out = _ROOT / "k1_bus_core" / "src" / "generated"
    if not rust_out.parent.exists():
        print("[codegen] Skipping Rust codegen (k1_bus_core/ not found)")
        return
    rust_out.mkdir(parents=True, exist_ok=True)
    cmd = ["flatc", "--rust", "-o", str(rust_out), str(_SCHEMA)]
    print(f"[codegen] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        print(f"[codegen] Rust codegen failed (non-fatal):\n{result.stderr}")
    else:
        print(f"[codegen] Rust bindings generated at: {rust_out}")


def main() -> None:
    """Run full codegen pipeline."""
    if not _SCHEMA.exists():
        print(f"[codegen] Schema not found: {_SCHEMA}", file=sys.stderr)
        sys.exit(1)

    # Check flatc availability
    try:
        ver = subprocess.run(["flatc", "--version"], capture_output=True, text=True, check=True)
        print(f"[codegen] {ver.stdout.strip()}")
    except FileNotFoundError:
        print("[codegen] flatc not found. Install FlatBuffers compiler.", file=sys.stderr)
        sys.exit(1)

    generated_file = _run_flatc_python()
    _flatten(generated_file)
    _run_flatc_rust()
    print("[codegen] Done.")


if __name__ == "__main__":
    main()
