"""k1.tools.family.chores.definition -- declarative spec for the Chores adapter.

Exposes :data:`CHORES_DEFINITION`, the single source of truth consumed by:

* :func:`k1.fabric.manifest_translator.register_definition` -- registers
  each :class:`ActionSpec` as a Fabric ``CapabilityContract``.
* :func:`k1.tools.family.manifest.ui_manifest` -- role-filtered UI manifest.
* :func:`k1.tools.family.manifest.llm_tool_specs` -- LLM tool specs with
  ``use_when`` / ``avoid_when`` / ``examples`` hints.
* :class:`ChoresToolService` -- consumes ``DEFINITION.tables_sql`` at
  construction time to create the SQLite projection tables.

9 actions
---------
Templates (3):
    1. ``create_template``  write  GREEN  idempotent  (parent+ only)
    2. ``update_template``  write  GREEN              (parent+ only)
    3. ``delete_template``  delete GREEN              (parent+ only)

Occurrences (6):
    4. ``assign_chore``     write  GREEN              (parent+ or guardian+)
    5. ``complete_chore``   write  GREEN              (assignee | parent+)
    6. ``skip_chore``       write  GREEN              (assignee | parent+)
    7. ``reopen_chore``     write  GREEN              (parent+ only)
  8. ``list_chores``      read   GREEN              (all roles incl. guest)
  9. ``chore_summary``    read   GREEN              (all roles incl. guest)
"""

from __future__ import annotations

import os

from k1.tools.family.definition import (
    ActionSpec,
    FieldSpec,
    LLMHints,
    SSESpec,
    ToolDefinition,
)

_HERE = os.path.dirname(__file__)
with open(os.path.join(_HERE, "tables.sql"), encoding="utf-8") as _f:
    _CHORES_DDL: str = _f.read()

# ---------------------------------------------------------------------------
# Shared field helpers
# ---------------------------------------------------------------------------

_VISIBILITY_FIELD = FieldSpec(
    name="visibility",
    type="string",
    required=False,
    description="Row-level band: ``family`` | ``adults`` | ``named`` | ``private``.",
)
_TEMPLATE_ID_FIELD = FieldSpec(
    name="template_id",
    type="string",
    required=True,
    description="``ChoreTemplate.id``.",
)
_OCCURRENCE_ID_FIELD = FieldSpec(
    name="occurrence_id",
    type="string",
    required=True,
    description="``ChoreOccurrence.id``.",
)

_ALL_ROLES = ["guest", "child", "elder", "guardian", "parent", "system"]
_WRITE_ROLES = ["child", "elder", "guardian", "parent", "system"]
_PARENT_PLUS = ["parent", "system"]
_GUARDIAN_PLUS = ["guardian", "parent", "system"]

# ---------------------------------------------------------------------------
# CHORES_DEFINITION
# ---------------------------------------------------------------------------

CHORES_DEFINITION = ToolDefinition(
    adapter_id="chores",
    version="1.0.0",
    category="coordination",
    summary=(
        "Recurring family chore management with gamification points — "
        "create templates, generate occurrences, complete or skip them."
    ),
    title="Family Chores",
    icon="checklist_rtl",
    description=(
        "FamilyOS native chore tracker.  Parents define chore templates with "
        "a frequency and base points.  Occurrences are generated by the "
        "scheduler (or on-demand) and assigned to family members.  Members "
        "complete or skip occurrences; points are tallied for leaderboard "
        "display.  Distinct from Tasks (one-shot) and Reminders (time/location "
        "alerts)."
    ),
    entity_type="chore_occurrence",
    views=["board", "list", "leaderboard"],
    activity_profile="chores.v1",
    domain_tags=["chores", "recurrence", "gamification", "reward_tracking"],
    filters=[
        FieldSpec(
            name="assigned_to",
            type="string",
            required=False,
            description="Filter by assignee ``member_id``.",
        ),
        FieldSpec(
            name="status",
            type="string",
            required=False,
            description="Filter by status: pending | done | skipped.",
        ),
    ],
    can_reference=["task_item", "calendar_event", "reminder"],
    feature_flags=["m15_chores"],
    tables_sql=_CHORES_DDL,
    actions=[
        # ── Template management ──────────────────────────────────────────
        ActionSpec(
            name="create_template",
            kind="write",
            summary="Create a new recurring chore template.",
            min_band="GREEN",
            idempotent=True,
            prompt_template="chores_activity_v1",
            allowed_roles=_PARENT_PLUS,
            params=[
                FieldSpec(
                    name="title",
                    type="string",
                    required=True,
                    description="Short name, e.g. 'Vacuum living room'.",
                ),
                FieldSpec(
                    name="description",
                    type="string",
                    required=False,
                    description="Extended instructions for the assignee.",
                ),
                FieldSpec(
                    name="assigned_to",
                    type="string",
                    required=False,
                    description="Default assignee member_id; ``null`` = pool.",
                ),
                FieldSpec(
                    name="frequency",
                    type="string",
                    required=False,
                    description=(
                        "daily | weekly | monthly | once, or a natural recurrence "
                        "phrase such as 'every 3 days'. Default: weekly."
                    ),
                ),
                FieldSpec(
                    name="base_points",
                    type="integer",
                    required=False,
                    description="Gamification points per completion. Default: 0.",
                ),
                FieldSpec(
                    name="due_at",
                    type="datetime",
                    required=False,
                    description="Optional ISO 8601 due timestamp for the first pending occurrence.",
                ),
                _VISIBILITY_FIELD,
            ],
            result=[
                FieldSpec(name="success", type="boolean", required=True),
                FieldSpec(name="template_id", type="string", required=True),
                FieldSpec(name="occurrence_id", type="string", required=True),
                FieldSpec(name="version", type="integer", required=True),
            ],
            sse=SSESpec(
                emits=["family.chores.create_template.write.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=[
                    "user wants to set up a recurring household chore",
                    "parent asks to add a new chore to the rota",
                    "chore needs to repeat daily, weekly, or monthly",
                ],
                avoid_when=[
                    "task is one-off — use tasks.create_task instead",
                    "user wants a time-based alert — use reminders.create_reminder",
                ],
                examples=[
                    "create_template(title='Take out trash', frequency='weekly', assigned_to='riley', base_points=5)",
                    "create_template(title='Unload dishwasher', frequency='daily', base_points=3)",
                ],
            ),
        ),
        ActionSpec(
            name="update_template",
            kind="write",
            summary="Edit a chore template (title, frequency, base_points, assigned_to).",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_PARENT_PLUS,
            params=[
                _TEMPLATE_ID_FIELD,
                FieldSpec(name="title", type="string", required=False),
                FieldSpec(name="description", type="string", required=False),
                FieldSpec(name="assigned_to", type="string", required=False),
                FieldSpec(
                    name="frequency",
                    type="string",
                    required=False,
                    description="daily | weekly | monthly | once, or a natural recurrence phrase.",
                ),
                FieldSpec(name="base_points", type="integer", required=False),
                FieldSpec(
                    name="is_active",
                    type="boolean",
                    required=False,
                    description="Set false to pause occurrence generation.",
                ),
                _VISIBILITY_FIELD,
            ],
            sse=SSESpec(
                emits=["family.chores.update_template.write.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=[
                    "parent wants to change chore frequency or point value",
                    "pause a chore temporarily with is_active=false",
                ],
                avoid_when=[
                    "user wants to mark an occurrence done — use complete_chore",
                ],
                examples=[
                    "update_template(template_id='t1', base_points=10)",
                    "update_template(template_id='t1', is_active=false)",
                ],
            ),
        ),
        ActionSpec(
            name="delete_template",
            kind="delete",
            summary="Soft-delete a chore template and all its pending occurrences.",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_PARENT_PLUS,
            params=[_TEMPLATE_ID_FIELD],
            sse=SSESpec(
                emits=["family.chores.delete_template.delete.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=["parent removes a chore from the family rota permanently"],
                avoid_when=["use update_template(is_active=false) to pause instead"],
                examples=["delete_template(template_id='t1')"],
            ),
        ),
        # ── Occurrence management ────────────────────────────────────────
        ActionSpec(
            name="assign_chore",
            kind="write",
            summary="Create or re-assign a chore occurrence to a family member.",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_GUARDIAN_PLUS,
            params=[
                _TEMPLATE_ID_FIELD,
                FieldSpec(
                    name="assigned_to",
                    type="string",
                    required=True,
                    description="member_id of the assignee.",
                ),
                FieldSpec(
                    name="due_at",
                    type="datetime",
                    required=False,
                    description="ISO 8601 UTC due timestamp.",
                ),
                FieldSpec(
                    name="points_awarded",
                    type="integer",
                    required=False,
                    description="Override base_points for this occurrence.",
                ),
                _VISIBILITY_FIELD,
            ],
            sse=SSESpec(
                emits=["family.chores.assign_chore.write.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=[
                    "explicitly assign a chore occurrence to a specific member",
                    "swap chore assignment for this week",
                ],
                avoid_when=[
                    "create_template already sets a default assignee; only use this to override",
                ],
                examples=[
                    "assign_chore(template_id='t1', assigned_to='alex', due_at='2026-05-19T08:00:00Z')",
                ],
            ),
        ),
        ActionSpec(
            name="complete_chore",
            kind="write",
            summary="Mark a chore occurrence as done and award points.",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_WRITE_ROLES,
            params=[
                _OCCURRENCE_ID_FIELD,
                FieldSpec(
                    name="completed_by",
                    type="string",
                    required=False,
                    description="member_id completing the chore; defaults to caller.",
                ),
                FieldSpec(
                    name="points_override",
                    type="integer",
                    required=False,
                    description="Parent may override points; child callers are ignored.",
                ),
            ],
            sse=SSESpec(
                emits=["family.chores.complete_chore.write.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=[
                    "member says they finished their chore",
                    "'I did the dishes', 'I vacuumed' — mark occurrence done",
                ],
                avoid_when=[
                    "chore is already done — operation is idempotent but noisy",
                ],
                examples=[
                    "complete_chore(occurrence_id='o1')",
                    "complete_chore(occurrence_id='o1', completed_by='riley')",
                ],
            ),
        ),
        ActionSpec(
            name="skip_chore",
            kind="write",
            summary="Mark a chore occurrence as skipped (no points awarded).",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_WRITE_ROLES,
            params=[
                _OCCURRENCE_ID_FIELD,
                FieldSpec(
                    name="skip_reason",
                    type="string",
                    required=False,
                    description="Optional note explaining why it was skipped.",
                ),
            ],
            sse=SSESpec(
                emits=["family.chores.skip_chore.write.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=[
                    "member explicitly says they are skipping a chore",
                    "parent excuses a chore for this week",
                ],
                avoid_when=[
                    "use complete_chore if the chore was actually done",
                ],
                examples=[
                    "skip_chore(occurrence_id='o1', skip_reason='school trip')",
                ],
            ),
        ),
        ActionSpec(
            name="reopen_chore",
            kind="write",
            summary="Revert a done or skipped occurrence back to pending.",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_PARENT_PLUS,
            params=[
                _OCCURRENCE_ID_FIELD,
                FieldSpec(
                    name="reason",
                    type="string",
                    required=False,
                    description="Optional note for the audit log.",
                ),
            ],
            sse=SSESpec(
                emits=["family.chores.reopen_chore.write.v1"],
                redact_fields=[],
            ),
            llm=LLMHints(
                use_when=[
                    "parent wants to undo a completion (chore not actually done properly)",
                    "mistaken skip needs to be reopened",
                ],
                avoid_when=[
                    "chore is already pending — no-op",
                ],
                examples=[
                    "reopen_chore(occurrence_id='o1', reason='dishes were still dirty')",
                ],
            ),
        ),
        ActionSpec(
            name="list_chores",
            kind="read",
            summary="List chore occurrences for a space, optionally filtered by assignee, status, or due window.",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_ALL_ROLES,
            params=[
                FieldSpec(
                    name="assigned_to",
                    type="string",
                    required=False,
                    description="Filter by assignee member_id.",
                ),
                FieldSpec(
                    name="status",
                    type="string",
                    required=False,
                    description="Filter by status: pending | done | skipped.",
                ),
                FieldSpec(
                    name="due_before",
                    type="datetime",
                    required=False,
                    description="Return only occurrences due before this ISO 8601 timestamp.",
                ),
                FieldSpec(
                    name="template_id",
                    type="string",
                    required=False,
                    description="Filter to occurrences of a specific template.",
                ),
            ],
            llm=LLMHints(
                use_when=[
                    "display family chore board or child's chore list",
                    "check what chores are due this week",
                    "answer 'what chores does Riley still have to do?'",
                ],
                avoid_when=[
                    "user wants one-shot tasks — use tasks.list_tasks",
                    "user wants reminders — use reminders.list_reminders",
                ],
                examples=[
                    "list_chores(assigned_to='riley', status='pending')",
                    "list_chores(due_before='2026-05-19T00:00:00Z')",
                ],
            ),
        ),
        ActionSpec(
            name="chore_summary",
            kind="read",
            summary="Return per-member points tally and completion stats for the space.",
            min_band="GREEN",
            prompt_template="chores_activity_v1",
            allowed_roles=_ALL_ROLES,
            params=[
                FieldSpec(
                    name="since",
                    type="datetime",
                    required=False,
                    description="Summarise completions on or after this ISO timestamp.",
                ),
            ],
            llm=LLMHints(
                use_when=[
                    "display chore leaderboard or points totals",
                    "answer 'who has the most points this week?'",
                    "parent wants a weekly chore completion report",
                ],
                avoid_when=[
                    "user wants the raw list of occurrences — use list_chores",
                ],
                examples=[
                    "chore_summary()",
                    "chore_summary(since='2026-05-12T00:00:00Z')",
                ],
            ),
        ),
    ],
)
