"""Domain catalog — 50 ServiceDefinition instances across 5 domains.

Phase 1, Epic 2 (Issue 2.4).  Source of truth for what connectors exist
in the kernel.  Each ``ServiceDefinition`` is expanded to a full
``ConnectorDefinition`` by ``build_connector_definition()``.
"""

from __future__ import annotations

from .builder import build_connector_definition
from .definition import ConnectorDefinition, ServiceDefinition

# ── 50 service definitions ──────────────────────────────────────────────

DOMAIN_SERVICES: dict[str, list[ServiceDefinition]] = {
    # ── family (10) ──────────────────────────────────────────────────
    "family": [
        ServiceDefinition(
            id="calendar",
            label="Calendar",
            resource="calendar_event",
            resource_kinds=["appointment"],
            desc="Shared family calendar with conflict detection.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "start", "end", "resource_id", "idempotency_key"],
            read_inputs=["resource_id", "time_min", "time_max"],
        ),
        ServiceDefinition(
            id="tasks",
            label="Tasks",
            resource="task",
            desc="Family task management with assignments and priorities.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "assignee", "due_date"],
            read_inputs=["assignee", "status"],
        ),
        ServiceDefinition(
            id="reminders",
            label="Reminders",
            resource="reminder",
            desc="Time-based reminders for household members.",
            read_op="list",
            write_op="create",
            write_inputs=["person", "time", "message"],
            read_inputs=["person", "status"],
        ),
        ServiceDefinition(
            id="chores",
            label="Chores",
            resource="chore",
            desc="Household chore assignments with points and scheduling.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "assignee", "due_date"],
            read_inputs=["assignee", "status"],
        ),
        ServiceDefinition(
            id="shopping",
            label="Shopping",
            resource="shopping_item",
            desc="Shared shopping lists with item tracking.",
            read_op="list",
            write_op="create",
            write_inputs=["name", "quantity"],
            read_inputs=["status"],
        ),
        ServiceDefinition(
            id="notes",
            label="Notes",
            resource="note",
            desc="Shared family notes and documents.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "content"],
            read_inputs=["author"],
        ),
        ServiceDefinition(
            id="contacts",
            label="Contacts",
            resource="contact",
            desc="Household contact directory.",
            read_op="list",
            write_op="create",
            write_inputs=["name"],
            read_inputs=["name"],
        ),
        ServiceDefinition(
            id="habits",
            label="Habits",
            resource="habit",
            desc="Habit tracking and streaks.",
            read_op="list",
            write_op="create",
            write_inputs=["name", "frequency"],
            read_inputs=["person"],
        ),
        ServiceDefinition(
            id="budgets",
            label="Budgets",
            resource="budget",
            desc="Household budget tracking.",
            read_op="list",
            write_op="create",
            write_inputs=["name", "amount", "category"],
            read_inputs=["category"],
        ),
        ServiceDefinition(
            id="documents",
            label="Documents",
            resource="document",
            desc="Shared family document storage.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "content"],
            read_inputs=["author"],
        ),
    ],
    # ── enterprise (10) ──────────────────────────────────────────────
    "enterprise": [
        ServiceDefinition(
            id="meetings",
            label="Meetings",
            resource="meeting",
            desc="Enterprise meeting scheduling with room booking.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "start", "end", "attendees"],
            read_inputs=["attendee", "time_min", "time_max"],
        ),
        ServiceDefinition(
            id="bug_tracker",
            label="Bug Tracker",
            resource="bug",
            desc="Software bug tracking and triage.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "severity", "project"],
            read_inputs=["assignee", "status"],
        ),
        ServiceDefinition(
            id="feature_tracker",
            label="Feature Tracker",
            resource="feature",
            desc="Feature request and roadmap tracking.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "priority", "project"],
            read_inputs=["status"],
        ),
        ServiceDefinition(
            id="doc_repo",
            label="Document Repository",
            resource="doc",
            desc="Enterprise document storage and search.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "content", "project"],
            read_inputs=["author", "project"],
        ),
        ServiceDefinition(
            id="it_helpdesk",
            label="IT Helpdesk",
            resource="ticket",
            desc="IT support ticketing system.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "category", "priority"],
            read_inputs=["assignee", "status"],
        ),
        ServiceDefinition(
            id="team_chat",
            label="Team Chat",
            resource="message",
            desc="Team messaging and channels.",
            read_op="list",
            write_op="send",
            write_inputs=["content", "channel"],
            read_inputs=["channel"],
        ),
        ServiceDefinition(
            id="tasks",
            label="Tasks",
            resource="task",
            desc="Enterprise task management.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "assignee", "project"],
            read_inputs=["assignee", "status"],
        ),
        ServiceDefinition(
            id="code_review",
            label="Code Review",
            resource="review",
            desc="Code review request tracking.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "repository", "branch"],
            read_inputs=["reviewer", "status"],
        ),
        ServiceDefinition(
            id="oncall_schedule",
            label="On-Call Schedule",
            resource="oncall_shift",
            desc="On-call rotation scheduling.",
            read_op="list",
            write_op="create",
            write_inputs=["person", "start", "end"],
            read_inputs=["person"],
        ),
        ServiceDefinition(
            id="analytics",
            label="Analytics",
            resource="report",
            desc="Business analytics and reporting.",
            read_op="list",
            write_op=None,
            read_inputs=["metric", "time_range"],
        ),
    ],
    # ── government (10) ──────────────────────────────────────────────
    "government": [
        ServiceDefinition(
            id="permits",
            label="Permits",
            resource="permit",
            desc="Building and zoning permits.",
            read_op="list",
            write_op="create",
            write_inputs=["type", "applicant", "location"],
            read_inputs=["applicant", "status"],
        ),
        ServiceDefinition(
            id="licenses",
            label="Licenses",
            resource="license",
            desc="Professional and business licenses.",
            read_op="list",
            write_op="create",
            write_inputs=["type", "holder", "expiry"],
            read_inputs=["holder"],
        ),
        ServiceDefinition(
            id="violations",
            label="Violations",
            resource="violation",
            desc="Code violation tracking and enforcement.",
            read_op="list",
            write_op="create",
            write_inputs=["type", "location", "description"],
            read_inputs=["status"],
        ),
        ServiceDefinition(
            id="meetings",
            label="Meetings",
            resource="meeting",
            desc="Public meeting scheduling and minutes.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "date", "agenda"],
            read_inputs=["date_range"],
        ),
        ServiceDefinition(
            id="records",
            label="Records",
            resource="record",
            desc="Public records management.",
            read_op="list",
            write_op="create",
            write_inputs=["title", "category", "content"],
            read_inputs=["category"],
        ),
        ServiceDefinition(
            id="inspections",
            label="Inspections",
            resource="inspection",
            desc="Building and safety inspections.",
            read_op="list",
            write_op="create",
            write_inputs=["type", "location", "date"],
            read_inputs=["inspector", "status"],
        ),
        ServiceDefinition(
            id="tax_records",
            label="Tax Records",
            resource="tax_record",
            desc="Property and business tax records.",
            read_op="list",
            write_op=None,
            read_inputs=["parcel_id", "year"],
        ),
        ServiceDefinition(
            id="court_docket",
            label="Court Docket",
            resource="case",
            desc="Court case and docket management.",
            read_op="list",
            write_op="create",
            write_inputs=["case_number", "title", "court_date"],
            read_inputs=["case_number"],
        ),
        ServiceDefinition(
            id="dispatch",
            label="Dispatch",
            resource="call",
            desc="Emergency and non-emergency dispatch.",
            read_op="list",
            write_op="create",
            write_inputs=["caller", "location", "nature"],
            read_inputs=["status"],
        ),
        ServiceDefinition(
            id="voter_registry",
            label="Voter Registry",
            resource="voter",
            desc="Voter registration records.",
            read_op="list",
            write_op=None,
            read_inputs=["name", "precinct"],
        ),
    ],
    # ── agriculture (10) ─────────────────────────────────────────────
    "agriculture": [
        ServiceDefinition(
            id="field_planner",
            label="Field Planner",
            resource="field_plan",
            desc="Crop field planning and rotation.",
            read_op="list",
            write_op="create",
            write_inputs=["field_id", "crop", "season"],
            read_inputs=["field_id"],
        ),
        ServiceDefinition(
            id="livestock",
            label="Livestock",
            resource="animal",
            desc="Livestock herd management.",
            read_op="list",
            write_op="create",
            write_inputs=["tag_id", "species", "location"],
            read_inputs=["species"],
        ),
        ServiceDefinition(
            id="equipment_log",
            label="Equipment Log",
            resource="equipment_log",
            desc="Farm equipment maintenance logs.",
            read_op="list",
            write_op="create",
            write_inputs=["equipment_id", "action", "hours"],
            read_inputs=["equipment_id"],
        ),
        ServiceDefinition(
            id="ag_weather",
            label="Ag Weather",
            resource="weather_record",
            desc="Agricultural weather data and forecasts.",
            read_op="list",
            write_op=None,
            read_inputs=["location", "date"],
        ),
        ServiceDefinition(
            id="farm_inventory",
            label="Farm Inventory",
            resource="inventory_item",
            desc="Seed, feed, and supply inventory.",
            read_op="list",
            write_op="create",
            write_inputs=["item", "quantity", "location"],
            read_inputs=["category"],
        ),
        ServiceDefinition(
            id="soil_analyzer",
            label="Soil Analyzer",
            resource="soil_sample",
            desc="Soil testing and analysis records.",
            read_op="list",
            write_op="create",
            write_inputs=["field_id", "sample_date", "results"],
            read_inputs=["field_id"],
        ),
        ServiceDefinition(
            id="irrigation",
            label="Irrigation",
            resource="irrigation_schedule",
            desc="Irrigation scheduling and monitoring.",
            read_op="list",
            write_op="create",
            write_inputs=["field_id", "start", "duration"],
            read_inputs=["field_id"],
        ),
        ServiceDefinition(
            id="harvest_planner",
            label="Harvest Planner",
            resource="harvest_plan",
            desc="Harvest planning and yield tracking.",
            read_op="list",
            write_op="create",
            write_inputs=["field_id", "crop", "estimated_date"],
            read_inputs=["field_id"],
        ),
        ServiceDefinition(
            id="grain_storage",
            label="Grain Storage",
            resource="storage_bin",
            desc="Grain storage monitoring and management.",
            read_op="list",
            write_op="create",
            write_inputs=["bin_id", "crop", "quantity"],
            read_inputs=["bin_id"],
        ),
        ServiceDefinition(
            id="market_prices",
            label="Market Prices",
            resource="price_quote",
            desc="Commodity market price tracking.",
            read_op="list",
            write_op=None,
            read_inputs=["commodity", "date"],
        ),
    ],
    # ── healthcare (10) ──────────────────────────────────────────────
    "healthcare": [
        ServiceDefinition(
            id="ehr",
            label="Electronic Health Records",
            resource="health_record",
            desc="Patient electronic health records.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "record_type", "content"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="appointments",
            label="Appointments",
            resource="appointment",
            desc="Patient appointment scheduling.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "provider_id", "start", "end"],
            read_inputs=["patient_id", "provider_id", "date"],
        ),
        ServiceDefinition(
            id="prescriptions",
            label="Prescriptions",
            resource="prescription",
            desc="Medication prescription management.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "medication", "dosage", "provider_id"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="lab_orders",
            label="Lab Orders",
            resource="lab_order",
            desc="Laboratory test ordering and results.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "test_type", "provider_id"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="messaging",
            label="Messaging",
            resource="message",
            desc="Secure patient-provider messaging.",
            read_op="list",
            write_op="send",
            write_inputs=["recipient_id", "content"],
            read_inputs=["sender_id"],
        ),
        ServiceDefinition(
            id="imaging",
            label="Imaging",
            resource="imaging_order",
            desc="Medical imaging orders and results.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "modality", "body_part", "provider_id"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="billing",
            label="Billing",
            resource="claim",
            desc="Medical billing and claims processing.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "service_date", "codes"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="immunizations",
            label="Immunizations",
            resource="immunization",
            desc="Vaccination and immunization records.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "vaccine", "date"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="referrals",
            label="Referrals",
            resource="referral",
            desc="Specialist referral management.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "to_provider_id", "reason"],
            read_inputs=["patient_id"],
        ),
        ServiceDefinition(
            id="vitals",
            label="Vitals",
            resource="vital_sign",
            desc="Patient vital sign records.",
            read_op="list",
            write_op="create",
            write_inputs=["patient_id", "type", "value", "measured_at"],
            read_inputs=["patient_id"],
        ),
    ],
}


def build_domain_corpus(domain_id: str) -> list[ConnectorDefinition]:
    """Build all ConnectorDefinitions for a domain."""
    services = DOMAIN_SERVICES[domain_id]
    return [build_connector_definition(domain_id, svc) for svc in services]


def build_all_corpora() -> dict[str, list[ConnectorDefinition]]:
    """Build ConnectorDefinitions for all 5 domains."""
    return {did: build_domain_corpus(did) for did in DOMAIN_SERVICES}
