"""
k1.orchestrator -- Core Orchestrator module.

Public API surface for the Orchestrator. All domain types, events,
port interfaces, and configuration are re-exported from this package root.
"""

from k1.orchestrator.config import OrchestratorConfig
from k1.orchestrator.connectors.connector_lifecycle import ConnectorLifecycleManager
from k1.orchestrator.events import (  # Emitted events; Consumed events
    AGENT_LLM_CALL,
    AGENT_TOOL_CALL,
    ALL_CONSUMED,
    ALL_EMITTED,
    CAPABILITY_COMPLETED,
    CAPABILITY_FAILED,
    CONTRACT_UPDATED,
    MICRO_REPLAN_READY,
    ORCH_DAG_COMPLETED,
    ORCH_DAG_MICRO_REPLAN,
    ORCH_DAG_NODE_FAILED,
    ORCH_DAG_STARTED,
    ORCH_DELTA_V1,
    ORCH_MCP_TOOL_REGISTERED,
    ORCH_PLAN_REQUESTED,
    ORCH_SAGA_COMPENSATING,
    ORCH_STEP_CANCELLED,
    ORCH_STEP_COMPLETED,
    ORCH_STEP_FAILED,
    ORCH_STEP_RETRYING,
    ORCH_STEP_SCHEMA_RETRY,
    ORCH_STEP_SKIPPED,
    ORCH_STEP_STARTED,
    ORCH_TASK_ACCEPTED,
    ORCH_WORKFLOW_COMPLETED,
    ORCH_WORKFLOW_TRIGGERED,
    PLAN_CANCELLED,
    PLAN_FAILED,
    PLAN_READY,
    WORKFLOW_TRIGGER_DUE,
)
from k1.orchestrator.factory import OrchestratorFactory
from k1.orchestrator.orchestration.constraint_resolver import ConstraintResolver
from k1.orchestrator.orchestration.dag_executor import DAGExecutor
from k1.orchestrator.orchestration.error_router import ErrorRouter
from k1.orchestrator.orchestration.orchestrator_service import OrchestratorService
from k1.orchestrator.orchestration.step_runner import StepRunner
from k1.orchestrator.ports import (
    IAdminPort,
    IBridgeWritePort,
    IDeltaEmitPort,
    IEventSubscriptionPort,
    IFabricGatewayPort,
    IMailboxPort,
    IPlannerPort,
    IStateReadPort,
    IWorkflowStoragePort,
    MailboxFullError,
    MailboxMessage,
)
from k1.orchestrator.types import (  # Enums; Leaf types; Core envelopes; Plan & result types; Workflow types; Context types; CB, Guard, Admin types
    ActiveDAGInfo,
    AdapterError,
    AggregatedResult,
    AlternativeCapability,
    AlternativeMapping,
    CapabilityCheck,
    CircuitBreakerConfig,
    CircuitBreakerState,
    CommittedPlan,
    CompensationRecord,
    ConditionExpr,
    Discovery,
    DrainResult,
    ErrorSeverity,
    FailureContext,
    GuardAction,
    GuardDecision,
    HealthStatus,
    InterruptRequest,
    IPostStepGuard,
    IPostWaveGuard,
    IPreWaveGuard,
    MCPServerRegistration,
    MicroReplanRequest,
    PendingPlanContext,
    PlanAck,
    PlanRequest,
    PlanStep,
    PreDispatchGuard,
    ProactiveGap,
    ProactiveGapStatus,
    ProcessingContext,
    ProcessResult,
    RecoveryResult,
    RegistryEntry,
    ResolutionResult,
    SchemaResult,
    StepResult,
    StepStatus,
    TaskAck,
    TaskEnvelope,
    TriggerSpec,
    TriggerType,
    ValidationResult,
    Wave,
    WaveResult,
    WorkflowRunRequest,
    WorkflowSaveRequest,
)
from k1.orchestrator.workflows.workflow_engine import WorkflowEngine

__all__ = [
    # Config
    "OrchestratorConfig",
    # Core services
    "OrchestratorService",
    "DAGExecutor",
    "StepRunner",
    "ConstraintResolver",
    "ErrorRouter",
    # Workflow services
    "WorkflowEngine",
    # Connector services
    "ConnectorLifecycleManager",
    # Factory
    "OrchestratorFactory",
    # Port Protocols
    "IAdminPort",
    "IBridgeWritePort",
    "IDeltaEmitPort",
    "IEventSubscriptionPort",
    "IFabricGatewayPort",
    "IMailboxPort",
    "IPlannerPort",
    "IStateReadPort",
    "IWorkflowStoragePort",
    # Port supporting types
    "MailboxFullError",
    "MailboxMessage",
    # Enums
    "ErrorSeverity",
    "GuardAction",
    "ProactiveGapStatus",
    "ProcessResult",
    "StepStatus",
    "TriggerType",
    # Leaf types
    "AdapterError",
    "AlternativeCapability",
    "AlternativeMapping",
    "CapabilityCheck",
    "CompensationRecord",
    "ConditionExpr",
    "Discovery",
    "FailureContext",
    "InterruptRequest",
    "MCPServerRegistration",
    "PlanAck",
    "RegistryEntry",
    "ResolutionResult",
    "SchemaResult",
    "TaskAck",
    "TriggerSpec",
    "ValidationResult",
    # Core envelopes
    "PlanStep",
    "StepResult",
    "TaskEnvelope",
    "Wave",
    # Plan & result types
    "AggregatedResult",
    "CommittedPlan",
    "MicroReplanRequest",
    "PlanRequest",
    "WaveResult",
    # Workflow types
    "ProactiveGap",
    "WorkflowRunRequest",
    "WorkflowSaveRequest",
    # Context types
    "PendingPlanContext",
    "ProcessingContext",
    # CB, Guard, Admin types
    "ActiveDAGInfo",
    "CircuitBreakerConfig",
    "CircuitBreakerState",
    "DrainResult",
    "RecoveryResult",
    "GuardDecision",
    "HealthStatus",
    "IPostStepGuard",
    "IPostWaveGuard",
    "IPreWaveGuard",
    "PreDispatchGuard",
    # Event constants
    "ALL_CONSUMED",
    "ALL_EMITTED",
    "ORCH_TASK_ACCEPTED",
    "ORCH_PLAN_REQUESTED",
    "ORCH_DAG_STARTED",
    "ORCH_DAG_MICRO_REPLAN",
    "ORCH_DAG_NODE_FAILED",
    "ORCH_DAG_COMPLETED",
    "ORCH_STEP_STARTED",
    "ORCH_STEP_COMPLETED",
    "ORCH_STEP_FAILED",
    "ORCH_STEP_CANCELLED",
    "ORCH_STEP_SKIPPED",
    "ORCH_STEP_RETRYING",
    "ORCH_STEP_SCHEMA_RETRY",
    "ORCH_SAGA_COMPENSATING",
    "ORCH_DELTA_V1",
    "ORCH_WORKFLOW_TRIGGERED",
    "ORCH_WORKFLOW_COMPLETED",
    "ORCH_MCP_TOOL_REGISTERED",
    "PLAN_READY",
    "PLAN_FAILED",
    "PLAN_CANCELLED",
    "MICRO_REPLAN_READY",
    "CAPABILITY_COMPLETED",
    "CAPABILITY_FAILED",
    "CONTRACT_UPDATED",
    "AGENT_TOOL_CALL",
    "AGENT_LLM_CALL",
    "WORKFLOW_TRIGGER_DUE",
]
