apiVersion: 1

datasources:
  - uid: tempo
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags:
          - key: 'service.name'
            value: 'service'
          - key: 'span.name'
            value: 'operation'
        queries:
          - name: 'Request Rate'
            query: 'rate(k0_http_requests_total{$$__tags}[5m])'
          - name: 'Request Latency'
            query: 'histogram_quantile(0.95, rate(k0_command_latency_seconds_bucket{$$__tags}[5m]))'
