# AUTOGENERATED — DO NOT EDIT — regenerate with: python -m tooling.contracts.codegen
# manifest_bundle_sha: 1a058d4e8e215f9f6f820aed8ad89afe17b30665d07d871be0fe21905bd84161
# source manifest: manifests/curiosity.intent.v1.yaml

"""Generated SSE subscriber for the ``curiosity.intent.v1`` contract.

Consumer side. The K1 kernel reaches the live K0\u2192K1 stream through
:class:`CuriosityIntentV1Subscriber.subscribe(handler)`, which
returns an async context manager backed by the real chunked SSE
transport (:mod:`bridge.core.transport.sse_client`). Cursor resume,
backpressure, and reconnect-with-jittered-backoff are handled there;
the subscriber is the typed seam that decodes the on-the-wire JSON
payload into a Pydantic ``CuriosityIntentV1`` instance before
calling the user handler.

The legacy ``register_handlers(runtime, impl)`` shape used by HTTP
request/response contracts does not apply to SSE: SSE is push-only
and there is no idempotent dispatcher mapping topic\u2192handler. The
:func:`register_subscriber` helper kept below records the subscriber
class on the runtime under :attr:`runtime.sse` so callers can write
``runtime.sse.curiosity_intent_v1.subscribe(handler)``.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from contextlib import asynccontextmanager
from typing import TYPE_CHECKING

from bridge._generated.k1.models.curiosity_intent_v1 import (
    CuriosityIntentV1,
)

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import AsyncIterator

    from bridge.core.transport.sse_client import SSEClient
    from bridge.runtime import BridgeRuntime


SubscriberHandler = Callable[[CuriosityIntentV1], Awaitable[None]]
"""Type alias for the user-supplied event handler."""


class CuriosityIntentV1Subscriber:
    """Generated SSE subscriber for ``curiosity.intent.v1``.

    The runtime supplies an :class:`SSEClient`. Direct construction
    outside the runtime is forbidden by the
    ``manifest_implementation_bound`` CI gate.
    """

    __transport__ = "sse"
    __topic__ = "curiosity.intent.v1"
    __schema_uri__ = "bridge://contracts/schemas/curiosity.intent.v1.json"

    def __init__(self, sse_client: "SSEClient") -> None:
        self._sse_client = sse_client

    @asynccontextmanager
    async def subscribe(
        self,
        handler: SubscriberHandler,
        *,
        cursor: str | None = None,
    ) -> "AsyncIterator[None]":
        """Open a chunked SSE stream and pump events through ``handler``.

        The async context manager owns the wire connection and the
        backpressure-aware internal queue. On exit, the wire is closed
        cleanly and the cursor (last successfully-handled envelope_id)
        is persisted by the underlying :class:`SSEClient`.

        ``handler`` receives a Pydantic-validated ``CuriosityIntentV1``
        instance per event. Exceptions raised by ``handler`` propagate
        out of the context manager.
        """
        async with self._sse_client.subscribe(
            topic=self.__topic__,
            model=CuriosityIntentV1,
            handler=handler,
            cursor=cursor,
        ):
            yield


def register_subscriber(runtime: "BridgeRuntime") -> None:
    """Bind a :class:`CuriosityIntentV1Subscriber` onto ``runtime.sse``.

    Called once at boot from :meth:`BridgeRuntime.from_registry`. The
    runtime is responsible for constructing (and supplying) the shared
    :class:`SSEClient`; this helper is the typed seam that knows the
    topic / model / schema URI for ``curiosity.intent.v1``.
    """
    sse_client = getattr(runtime, "_sse_client", None)
    if sse_client is None:
        # SSE transport not bound \u2014 leave the slot None so callers can
        # detect offline mode.
        return
    bag = runtime.sse if runtime.sse is not None else _SSEBag()
    setattr(bag, "curiosity_intent_v1", CuriosityIntentV1Subscriber(sse_client))
    object.__setattr__(runtime, "sse", bag)


class _SSEBag:
    """Plain attribute bag populated with one subscriber per SSE manifest."""


__topic__ = "curiosity.intent.v1"
